### ISSUE TITLE
How make fingerprint same in different browser?

### ISSUE THREAD

**Issue by 12th** [Valve/fingerprintjs2#10]
Hello.
Is it possible to do something that the fingerprint was the same in different browsers?
Because these settings do not help:

var fp = new Fingerprint2({excludeUserAgent: true});

**Comment by mfurlend** [comment]
I can answer that for you: no. The only information that the plugin draws from is browser-specific.

**Comment by 12th** [comment]
Also anonymous Chrome window (41.0.2272.89) creates a new fingerprint hash.

**Comment by brentpayne** [comment]
I got the followup, yes it does and would b/c it is only capturing incognito plugins and not all plugins.  Fingerprint works similarly to cookies without requiring a cookie.  While this is an oversimplification, lets run with it. Tracking cookies are different based on browser, machine, and privacy mode, so it is a reasonable expectation that fingerprints would be as well.  If you need cross-browser and cross privacy tracking of people ask them to sign in or download your plugin (which I bet they won't b/c you are doing something shady).

**Comment by Valve** [comment]
Yes, this library is called 'browser fingerprint', not identity fingerprint or person fingerprint, so it's not possible. You can try making the sign-up/sign-in process as easy as possible to have most of your users authenticated, but besides that, I don't think much is possible.

**Comment by maman8** [comment]
Then how this website done it?
Its fingerprint for cross browser. Try to change any browser. It will almost identify you

https://fingerprint.pet-portal.eu

**Comment by mfurlend** [comment]
@maman8 I tried your link in Chrome and Safari, and got different fingerprints. However, I did get the same fingerprint in Chrome regular, incognito, and canary windows. I am guessing that they use your IP address - that is why it sometimes works across browsers.

**Comment by seancsy** [comment]
You can try this fingerprint browser detection website
[https://ipdog.io/](url)
