### ISSUE TITLE
Is it planned to implement ETAG mechanism ?

### ISSUE THREAD

**Issue by Maj0rrush** [Valve/fingerprintjs2#100]
Hi, 

for mobile tracking, we use an ETAG implementation. This gives us a better tracking as the standard fingerprint.

Is it planned to integrate so sort of Etag ?
Greetz,

Markus

**Comment by Valve** [comment]
Hi, please explain what you mean by ETAG implementation? Are you referring to the HTTP header?

**Comment by Maj0rrush** [comment]
Yes i mean the HTTP Header.

**Comment by Valve** [comment]
According to wikipedia article: https://en.wikipedia.org/wiki/HTTP_ETag

>An ETag is an opaque identifier assigned by a web server to a specific version of a resource found at a URL.

Which implies server-side code too. I think it's currently out of scope of this library. 

However I'm planning to work on a complete (front + back + analytics) project where I will look into it again.
