### ISSUE TITLE
ad block detection code failing

### ISSUE THREAD

**Issue by pschlump** [Valve/fingerprintjs2#102]
This is similar to #77 that is closed - however, I get:

Uncaught TypeError: Cannot read property 'appendChild' of null 

on line 751 of the code.  I replaced the code with the following

	  try {
	    document.body.appendChild(ads);
	    return document.getElementById("ads") ? false : true;
	  } catch(e) {
		return false;
	  }

That resolved the error - I do not have ad block installed.  This is in Chrome on Mac - current version.

**Comment by pschlump** [comment]
I have found the cause.  The page was running through a HTML compression that removed the
body tag.  No body tag and document.body is NULL.

**Comment by Valve** [comment]
Thanks for letting me know. I'm going to fix it now. Please note that in version 2, this code will be removed entirely, because AdBlock detection is not working.

**Comment by maex78** [comment]
Hello. I got the same problem. Any way to fix this on my page ?

**Comment by Valve** [comment]
No, this issue is not fixed and will not be. Please use another javascript library to detect AdBlock

**Comment by maex78** [comment]
I dont want to detect Adblock :-) i want to generate a fingerprint. Cant generate because of this failure.

**Comment by Valve** [comment]
Which version are you using?

**Comment by maex78** [comment]
Thanks for fast answere. github is new resource for me. Dont saw you updated v1.0.0 to v1.0.3 - will test new version. Thanks!

**Comment by saarp** [comment]
AdBlock detection seems to still be failing. 

My test on https://www.google.com/ (after page loads):
```
// Inject Fingerprintjs2
var fpjs = document.createElement('script'); fpjs.type='text/javascript'; 
fpjs.src="https://cdnjs.cloudflare.com/ajax/libs/fingerprintjs2/1.5.1/fingerprint2.min.js"; 
document.getElementsByTagName('body')[0].appendChild(fpjs);
// Calculate fingerprint
var fp_options = {'excludeJsFonts': true, 'excludeFlashFonts': true};
var fp_obj = new Fingerprint2(fp_options);
// Check for Ad Blocker.
fp_obj.getAdBlock(); // <-- returns false
```
Should I pass in options to ignore the adblock setting?
