### ISSUE TITLE
Error IE

### ISSUE THREAD

**Issue by pedrofeijo1** [Valve/fingerprintjs2#104]
When i try to use this library in IE9 i got the error: "pair.value.join undefined".
Sorry for my bad english.

original:
newKeys.forEach(function(pair) {
    var value = pair.value;
    if (typeof pair.value.join !== "undefined") {
        value = pair.value.join(";");
    }
    values.push(value);
});

modify:
newKeys.forEach(function(pair) {
    var value = pair.value;
    if (typeof pair.value !== "undefined" && typeof pair.value.join !== "undefined") {
        value = pair.value.join(";");
    }
    values.push(value);
});

**Comment by Valve** [comment]
@pedrofeijo1 Did you test this on the demo page here: http://valve.github.io/fingerprintjs2/?

If so, then it's fine, yesterday there was a dev version, I've changed it to stable version again now (1.0.1)

**Comment by pedrofeijo1** [comment]
Yes, i test on demo page, get the same error.

**Comment by Valve** [comment]
Which IE version? Are you testing now and seeing this error?

**Comment by Valve** [comment]
Fixed, grab version 1.0.2, verified on IE 5-11 and IE Edge.
