### ISSUE TITLE
Firegloves plugin

### ISSUE THREAD

**Issue by Moskow** [Valve/fingerprintjs2#106]
Hi, what do you think about this plugin. 
"It replaces many of your browser to common values and carries out a banal cloaking browser-print, constantly changing values of the screen resolution, platform, language, and other identifiers to do surveillance even theoretically impossible."
Btw, next summer I'm going to do a site with tournaments. It is very important that users do not create a lot off fakes accounts but I do not understand anything in the code. Will the developers do it all takes place automatically when registering? For each registered account created fingerprint and if two users are the same to me comes notification in admin panel?

**Comment by Valve** [comment]
Never heard about this particular plugin, but I know they exist, but they're not very successful, because they break many existing JavaScript applications by changing browser properties.

> I'm going to do a site with tournaments

and

>I do not understand anything in the code

kind of contradict with each other

**Comment by Moskow** [comment]
Ya budu prosto adminom i avtorom idei. Sam sait sdelayut v agenstve. Mne prosto vazhno znat slozno eto budet sdelat ili net (t.e. cena voprosa), potomuchto useri budut delat ne desatki dazhe a sotni feikov v nadezhde na halavy. T.e. chtobi pri registracii nomer otpechatka otobrazhalsa  vmeste s IP v adminke  v razdele POLZOVATELI.

**Comment by Valve** [comment]
такое сделать возможно, но опытного спамера это не остановит. Есть спамеры, которые обходят все виды защиты. Но снизить процент фейковых аккаунтов в 10 раз FPJS2 поможет точно.

**Comment by Moskow** [comment]
Большое спасибо за ваши старания. Еще вопрос, я правильно понимаю, что для того чтобы сделать ваш плагин еще более эффективным нужно создавать сайт так, чтобы без JavaScript он не работал\открывался?

**Comment by Valve** [comment]
Без JavaScript он работать не будет, все верно, поэтому если хотите для всех пользователей получать FP то да, нужно обязательно требовать наличие JS в браузере.

**Comment by Moskow** [comment]
Большое спасибо за ответы. Т.е. в тех. задании просьба все пальчики отображать в админке в разделе "пользователи" будет равносильно созданию модуля?

**Comment by Valve** [comment]
все пальчики отображать в админке в разделе "пользователи" будет равносильна созданию модуля?

Непонятно что здесь написано :) Вы не через Google Translate пишете?

**Comment by Moskow** [comment]
:) я же говорил, не разбираюсь в сайтостроении, мне просто нужно будет ясно объяснить людям, что я от них хочу при том при всем, что люди в моем городе привыкли клепать дефолтные сайты для стоматологических клиник и фирм по продаже окон. В итоге просьба, чтобы пальчики отображались в админке рядом с каждым пользователем может вызвать бурю эмоций и неадекватный ценник. Вот я и пытаюсь выяснить, моя просьба - это должна быть рядовая процедура для команды, специализирующейся на создании сайтов или что-то из ряда вон выходящее. Чтобы просто зашел я в админку, вижу в графе "ПОЛЬЗОВАТЕЛИ" воск. знак - значит 2 и более одинаковых отпечатка - пошел банить\выдавать предупреждения\удалять.

**Comment by Valve** [comment]
Меня смутило слово "Пальчики", теперь я понял что вы имели в виду. Для студии из провинциального городка может быть и непосильной задачей, сложно сказать.  Нужно еще помнить, что библиотека определяет только 9 пользователей из 10, поэтому нельзя на нее полагаться как на стопроцентное средство, а только вместе с другими признаками. В компании где я работаю есть свой фильтр отлова мошенников, у нас пара десятков критериев, помимо отпечатка браузера. Работает очень надежно, но это разработка достаточно сложная (особенно опять же для "студии")

**Comment by Moskow** [comment]
9 из 10 - это идеально. За турнир надо заплатить + еще и выиграть. Если подбить 90 из 100 фейков - быстро отпадет интерес, при условии, что человек расстается со вступительными на фейковом счете и может ничего не получить взамен (условия тяжелые, но приз получает КАЖДЫЙ, кто его выполнит, именно поэтому так важно определить уникальность юзера).  
Т.е. в тех. задании - это будет "модуль вывода отпечатков в админ панель"?

**Comment by Valve** [comment]
да

**Comment by Moskow** [comment]
Большое спасибо за ответы, извините за назойливость.

**Comment by PatSpiegel** [comment]
мне стало интересно, а какие способы идентификации вы используете в компании (кроме fpjs)?

**Comment by Valve** [comment]
Guys, I suggest we move the discussion in Russian to gitter.im chat, it's more appropriate there. I can answer all questions there. Thanks!
