### ISSUE TITLE
Test for ability to access nonstandard DNS TLD's

### ISSUE THREAD

**Issue by JeremyRand** [Valve/fingerprintjs2#107]
I think it would be quite interesting to fingerprint users based on their ability to access nonstandard top-level domains.  For example, .onion (Tor), .i2p (I2P), .bit (Namecoin), and the OpenNIC TLD's.  Maybe also test for IPv4 and IPv6 connectivity.  This is a bit more tricky to deploy than the other things that you currently do, since I guess a website that deploys this would need to know of a cooperating server that listens on each of these.

Thoughts on whether it's doable?

**Comment by Valve** [comment]
@JeremyRand this library is a no-dependencies/stateless library currently. It does not make any network calls or store the info in the browser and thus hard to block/detect. If I added the domain probing as you suggest, this would violate the above browser properties, so I think I cannot built it directly into the library. 

However, if you really need this, I can create a plugin ability for the library and have the interested parties develop plugins that do the specific tasks of fingerprinting. Please let me know what you think. 
Also I would like to apologize for the late response, the NY in Russia is a landslide event.

**Comment by JeremyRand** [comment]
It's not an urgently needed feature for me, I just think it would be cool.  A plugin capability would definitely be cool, and if it's convenient for you to add, that would be great.  But certainly not urgent for me, so feel free to take your time on it.
