### ISSUE TITLE
TypeError: this.userAgentKey is not a function

### ISSUE THREAD

**Issue by drchav** [Valve/fingerprintjs2#11]
When i'm trying to use i get this error
TypeError: this.userAgentKey is not a function

Anyone has an idea of what i can do?

Best

**Comment by Valve** [comment]
@drchav please update with your browser & OS versions

**Comment by drchav** [comment]
Firefox with MACOS all latests versions

**Comment by Valve** [comment]
Works for me, FF 36, OSX 10.10.2

**Comment by Valve** [comment]
I cannot reproduce this of OSX in any browser. Please let me know any additional details of this error. Line number, if you have any custom FF settings, any plugins installed etc
