### ISSUE TITLE
Google Chrome issue

### ISSUE THREAD

**Issue by drstyv** [Valve/fingerprintjs2#111]
I am using testing our Fingerprint 2 on a large site and a lot of people are reporting this error in the Google Chrome console: "Fingerprint2 is not defined"

Any idea why this is appearing? i am my self using the latest Google Chrome and i don´t get the same error

**Comment by Valve** [comment]
I never saw this error. Please ensure they're using the latest version (1.0.3)

**Comment by drstyv** [comment]
I have users reporting that they are getting this error when using Google Chrome version 47.0.2526.106 

Also they are getting some collisions, any advice?

**Comment by Valve** [comment]
Are you using the latest version (1.0.3)?

**Comment by drstyv** [comment]
Sorry i forgot to mention that, yes i am using 1.03 latest version.

**Comment by Valve** [comment]
That's weird, I'm on Chrome 47.0.2526.106 (64bit) - OSX and I don't have errors.

**Comment by drstyv** [comment]
i had the issue on a few browsers but the issue seems to get fixed when i refresh browser cache with ctrl+f5 so it might just be some kind of cache issue?

However there seems to be browser collisions with same browser keys with some chrome browsers, i am not sure why.

**Comment by Valve** [comment]
Don't know about the cache, never seen this error, so I cannot really say anything unless I reproduce.
As for collisions - if the input is the same, the output will be the same. To determine this, you need to log all components to be able to compare them
