### ISSUE TITLE
Different WebGL values on devices

### ISSUE THREAD

**Issue by alexber220** [Valve/fingerprintjs2#112]
I don't have with devices.

1) different webgl bits
User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; ASUS_T00J Build/KVT49L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36

"key":"webgl","value":" ... ~webgl alpha bits:8~webgl antialiasing:yes~webgl blue bits:8~webgl depth bits:16~webgl green bits:8~ ...

"key":"webgl","value":" ... ~webgl alpha bits:0~webgl antialiasing:yes~webgl blue bits:0~webgl depth bits:0~webgl green bits:0~ ...

2) different canvas
User-Agent: Mozilla/5.0 (Linux; Android 5.0.1; GT-I9500 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36

"key":"webgl","value":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAANC0lEQVR4Xu2dTYhlRxXHb/UgkkUIIhKCzGKQMGAIEkUhyNAdBSWLgCGLgI ...
"key":"webgl","value":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAANAklEQVR4Xu2dS4ilRxXHv+pBJIsgIhIkDCFIGDAEiaIQwtAdBSWLgJJFQF ...

3) different canvas
User-Agent: Mozilla/5.0 (Linux; Android 4.2.2; IdeaTab S6000-H Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Safari/537.36

**Comment by Valve** [comment]
Hi @alexber220 

I don't think I understand your question (or was there a question?)

**Comment by alexber220** [comment]
why change webgl canvas?

**Comment by Valve** [comment]
Sorry, I still cannot understand your question. Please elaborate on this.

**Comment by alexber220** [comment]
On some device change webgl canvas or webgl bits.

**Comment by Valve** [comment]
man, you need to be more descriptive or use someone with a better English. Sorry, can't help you now.
What's your native language?

**Comment by alexber220** [comment]
Russian

**Comment by Valve** [comment]
Ну другое дело, пиши по русски

**Comment by alexber220** [comment]
:) почему-то на некоторых устройствах меняется значение webgl. в некоторых случаях webgl canvas, и иногда webgl bits возвращает 0.

**Comment by Valve** [comment]
что за устройства, что за версия браузера, какая операционка, есть ли внешняя видео-карта?

**Comment by alexber220** [comment]
и с обычным canvas в устройствах от apple беда какая-то

**Comment by alexber220** [comment]
судя по user agent мобильники

**Comment by Valve** [comment]
нужны детали, у меня все работает

**Comment by alexber220** [comment]
список устройств где меняется?

**Comment by Valve** [comment]
что за устройства, что за версия браузера, какая операционка, есть ли внешняя видео-карта?
И описать подробнее что значит "меняется"

**Comment by alexber220** [comment]
то что в самом начале написал не достаточно? 
В User Agent есть и устройство и браузер и операционка и что меняется.

**Comment by Valve** [comment]
ты же на писал "устройства apple" а там андроиды. и неясно что значит меняется

**Comment by alexber220** [comment]
у apple обычный canvas меняется, а не тот что webgl, его пришлось из-за этого отключить.
меняется это значит что в рамках одной сессии был один fingerprint, а стал другой. начали выяснять, оказалось меняется значение canvas и webgl.

**Comment by Valve** [comment]
Во, теперь понял. Вот на этой странице (http://valve.github.io/fingerprintjs2/) меняется в рамках сессии? (если нажимать много раз - то каждый раз будут разные отпечатки?)
и какие устройства эппл? У меня есть 5c и Ipad и там все ок (сейчас перепроверю)

**Comment by alexber220** [comment]
это у пользователей

**Comment by alexber220** [comment]
проверить у себя нет возможности

**Comment by alexber220** [comment]
может из-за смены ориентации экрана или ещё из-за чего

**Comment by alexber220** [comment]
может в фоне игрушка какая ещё висит

**Comment by alexber220** [comment]
не получилось воспроизвести?

**Comment by Valve** [comment]
Только что перепроверил, iPad mini (retina), iPhone 5c, Sony xperia Z3 compact (Android 5) - везде одинаковые отпечатки. Ориентация экрана - тоже одинаково. На андроиде проверил на Google Chrome и на Mobile Firefox. Везде работает.

Пока закрываю тикет, как появится возможность воспроизвести надежено (если получится) переоткрывай и пиши, посмотрим.

**Comment by alexber220** [comment]
хорошо, спасибо
