### ISSUE TITLE
Изменение отпечатка из-за canvas и webgl

### ISSUE THREAD

**Issue by alexber220** [Valve/fingerprintjs2#113]
Fingerprintjs2 1.0.3

var options = {swfPath: '', excludeUserAgent: true, excludeFlashFonts: true,
        excludeScreenResolution: true, excludePlugins: true, excludeHasLiedBrowser: true,
        excludeHasLiedResolution: true};
    new Fingerprint2(options).get(function(result, data){
        $('#fp').val(result);
        $('#fpv').val(JSON.stringify(data));
    });

собрал информацию за сутки. к сожалению, возможность воспроизвести изменение отсутствует.

Узнать устройство и версию браузера по UA можно здесь http://useragentstring.com/index.php

[canvas.txt](https://github.com/Valve/fingerprintjs2/files/86992/canvas.txt)
[webgl.txt](https://github.com/Valve/fingerprintjs2/files/86995/webgl.txt)

**Comment by Valve** [comment]
если нельзя воспроизвести, как исправить тогда?

**Comment by alexber220** [comment]
отключением canvas и webgl похоже :(

**Comment by Valve** [comment]
чтобы поправить - нужно воспроизвести. Пока нет информации как воспроизвести - я закрываю тикет. Т.к. суть тикета - сообщить о дефекте. Если дефекта никто не видит и никто его воспроизвести не может, значит дефекта нет.
