### ISSUE TITLE
Claimed iPhone has Flash plugin

### ISSUE THREAD

**Issue by k0dek0mmand0** [Valve/fingerprintjs2#114]
I've been getting requests from a bot that claims to be an iPhone, but has Flash and Java plugins installed. It seems like there's another simple test that could be added to has_lied_os.

**Comment by Valve** [comment]
Agree, thanks

**Comment by Valve** [comment]
I'm sorry for closing, but we'll be concentrating on stabilizing the library, not on adding new features in the foreseeable future. Closing as a non-feature.
