### ISSUE TITLE
IE11 does not return any plugins

### ISSUE THREAD

**Issue by kralikba** [Valve/fingerprintjs2#116]
For Internet Explorer 11, the ie_plugins key is always empty. However, this version already has a nonempty navigator.plugins field; I'd suggest testing for that and including its value in the hash. (However, I do not know how many plugins that contains in general; for me, it is suspiciously short.)

**Comment by Valve** [comment]
Thanks for the issue. I will only be able to look at it in a couple of weeks or so. Please submit a PR if you need to speed things up.

**Comment by masubi** [comment]
@Valve - updated to actually pull IE11 plugins, let me know if i should be doing this differently

**Comment by Valve** [comment]
@kralikba, @masubi thank you for your contributions. I will definitely look into it but later, currently I'm moving to another country and completely out of time.
Thanks!
