### ISSUE TITLE
2 Same Model Android Phones Generated Same Fingerprint ;)

### ISSUE THREAD

**Issue by stuart-lam** [Valve/fingerprintjs2#117]
I've just tested on 2 same model android phone using default browser, and it generate the same Fingerprint. Deeper investigating showing that the Canvas Image generated is exactly the same. I tried to hash that image alone and we got same hashes in both devices

**Comment by Valve** [comment]
Yep, that's expected.

**Comment by stuart-lam** [comment]
Yeah what a pitty man, I'm thinking of making a fallback to Etag checking when Android Phone and Touch Support detected.

**Comment by Valve** [comment]
You can use evercookie + FPJS2 or something different. Don't rely on FPJS2 alone, it's not reliable on mobile

**Comment by stuart-lam** [comment]
yeah, but I want something "light" evercookie is not good enough (slow) for what I'm doing now ^__^.... Thank you a bunch of this wonderful git.

**Comment by Valve** [comment]
ok, if evercookie is slow you should just use regular cookies + FPJS2 should work fine
