### ISSUE TITLE
different fingerprint value in iframe and out of iframe in firefox

### ISSUE THREAD

**Issue by alirezaDavid** [Valve/fingerprintjs2#118]
In firefox browser fingerprint in iframe and fingerprint out of iframe not the same.
Thanks

**Comment by Valve** [comment]
Thanks for letting me know, I will look into it

**Comment by Valve** [comment]
Just as an update, I'm currently not working on the library because I'm traveling, but I will definitely look into it

**Comment by alirezaDavid** [comment]
@Valve Thanks buddy

**Comment by alirezaDavid** [comment]
**UPDATE**
I found this issue also in android browser and firefox mobile.

**Comment by Valve** [comment]
@alirezaDavid hi, thanks for waiting :) Could you please send a link to jsbin or similar to reproduce?

**Comment by Valve** [comment]
closing due to inability to reproduce and lack of JavaScript example on JSbin or similar.
