### ISSUE TITLE
duplicates increasing over the time  

### ISSUE THREAD

**Issue by Adnation** [Valve/fingerprintjs2#119]
I have used this code and added three more parameters of my own (i.e. Mimetypes, DPI & java) and initially I got many 10 digit fingerprint ID's which over the time have reduced but when first I tested with 1091 clients and the result was 3% of duplicate's and after that when I tested with 1900 clients the result was 5% duplicates. Now I believe this inaccuracy will increase over the time.

**Comment by Valve** [comment]
Hi, this library must have duplicates, it's absolutely normal. it should produce around 10% of collisions (duplicates) during normal operation. So I'm closing the issue, feel free to reopen with more questions

**Comment by DmonteiroD** [comment]
@Valve There is any suggestions to confirm if a collision is real or not? Suppose that an user create multiples accounts to fake a polling, and there is a collision in one of theses accounts with a legitimate user. 

How can be identified? 

Also, 5-7 collisions per ~200K is +-0.0025%. Now there is 10% of collisions? the number is incredible high in comparison with fingerprint 1.

thanks

**Comment by Valve** [comment]
You can use cookies to identify collisions. Also , FP1 has > 11% of collisions. There are hash collisions (which are very rare) and just identical devices that produce identical FPs. I call them collisions too

**Comment by DmonteiroD** [comment]
> You can use cookies to identify collisions. 

If a user create multiples accounts, each account will have a single and unique cookie to make a login. So each malicious or good account will have always an unique cookie.

What I am missing here? 

Or you mean an anonymous cookie to each visit only for tracking the id? Anyway, he could delete his cookies. Sorry, if I am missing something obvious.

@Valve thanks for the answer.

**Comment by Valve** [comment]
@DmonteiroD, sorry for the vague reply. I think you cannot identify duplicates for anonymous users. If user is anonymous, uses multiple devices and erases cookies, there is nothing you can do. There is no magic here. You can use a combination of (super)cookies/ip addresses/fingerprintjs to guess at a certain level of confidence, not more. If user wants to be anonymous and knows how to stay anonymous, nothing will identify him.

**Comment by DmonteiroD** [comment]
@valve, exactly what I am thinking. In relation to registered users, how can cookies be useful to identify collisions, since each user will have always an unique cookie that allow the login?

So, the combination of cookie + fingerprint will be always unique. 

Also, what is the point of using fingerprint when you have an account with an unique cookie that identify a specific user?

Sorry, but this is a bit complicated of understand.
