### ISSUE TITLE
Research WebRTC related fingerprinting

### ISSUE THREAD

**Issue by Valve** [Valve/fingerprintjs2#12]

**Comment by antoinevastel** [comment]
Do you have already any ideas ?

**Comment by Valve** [comment]
Yeah, I saw the code in augur.js, need to look into it some time.

**Comment by Valve** [comment]
@antoinevastel , here is a more or less relevant piece from Augur.js

```javascript
 webRTC: function() {
                var c, d, e, f, a = window,
                    b = [],
                    g = a.webkitRTCPeerConnection || a.mozRTCPeerConnection || a.RTCPeerConnection;
                return g ? (f = new g({
                    iceServers: []
                }), f.createDataChannel("", {
                    reliable: !1
                }), f.onicecandidate = function(a) {
                    var b = a.candidate;
                    b && e("a=" + b.candidate)
                }, f.createOffer(function(a) {
                    e(a.sdp), f.setLocalDescription(a)
                }, function() {}), d = function(a) {
                    -1 == b.indexOf(a) && "0.0.0.0" != a && (b.push(a), clearTimeout(c), c = setTimeout(function() {
                        var a = window.augur,
                            c = b.sort().toString();
                        a.cake.getSet("IP", c), a.FP.routerFingerprint = c, a.sub.brain({
                            type: "rc"
                        })
                    }, 20))
                }, e = function(a) {
                    a.split("\r\n").forEach(function(a) {
                        if (~a.indexOf("a=candidate")) {
                            var b = a.split(" ");
                            "host" == b[7] && d(b[4])
                        } else ~a.indexOf("c=") && d(a.split(" ")[2])
                    })
                }, void 0) : (a.augur.sub.brain({
                    type: "rd"
                }), void 0)
            }
        },
        record: {
            performance: function(a) {
                var b = window.augur;
                (new Image).src = "//analytics.augur.io/performance?t=" + (Date.now() - b.start) + "&m=" + a + "&c=" + b.CID
            }
        },
        sub: {
            brain: function(a) {
                var c, d, b = window.augur;
                if (!b.MEM.fn) switch (b.MEM[a.type] = a.override ? !1 : !0, c = window.augur.MEM, d = (c.fc || c.fd) && (c.sc || c.sd) && (c.rc || c.rd), !0) {
                    case d && c.cc:
                        b.sub.destruct();
                        break;
                    case d && c.fp && !!c.cds && !c.cs:
                        b.cake.send(), b.MEM.cs = !0
                }
            },
            destruct: function() {
                var d, e, a = window.augur,
                    b = ["augurSilverlightCallback", "augur_se"],
                    c = b.length,
                    f = a.FP,
                    g = a.anynomous;
                for (document.getElementById("exQuadrupedibus"), window.augur = {
                        Auspice: a.Auspice,
                        CID: a.CID,
                        CNT: a.CNT,
                        DID: a.DID,
                        ERR: a.ERR,
                        MEM: a.MEM,
                        UID: a.UID,
                        client: {
                            plugins: a.client.plugins
                        },
                        json: a.json
                    }, "exCaelo" == a.Auspice && (window.augur.anynomous = g, window.augur.FP = f); c--;) {
                    e = b[c], d = window[e], d && (window[e] = null);
                    try {
                        delete window[e]
                    } catch (i) {}
                }
                delete window.augur.MEM.cds, a.MEM.fn = !0
            },
```

**Comment by NawarA** [comment]
Hi, you've accidently (hopefully) infringed on our copyright by pasting our software source code here without our consent or approval. Please remove our source code from this repo. If you don't contact me back within 24 hours, I will file a Github DCMA Takedown Request against your repo. 

I don't want your repo to be shutdown or get in trouble without first giving you the chance to do the right thing.

**Comment by graemeblackwood** [comment]
I presume you have something like this in mind? https://www.browserleaks.com/webrtc

**Comment by Valve** [comment]
@graemeblackwood yes, exactly. Unfortunately I haven't been able to evolve FPJS2 lately, too much work on my day job

**Comment by mhuisman** [comment]
@Valve I'll take a look at it.

**Comment by graemeblackwood** [comment]
@mhuisman Brilliant. Of all the possibles on the to do list, I have a feeling this would probably be the most beneficial given the media device enumeration.

**Comment by Valve** [comment]
@mhuisman :+1: thank you

**Comment by jenic** [comment]
@mhuisman I've [added this](https://github.com/jenic/fingerprintjs2/commit/30210a8e12fde10da17443fb5dd2fb2c98634427) for something I was doing for myself, perhaps you might be interested in it. It seems to work fine though I have not done extensive testing. I am using the IPs returned from mozilla's STUN server though, perhaps not desired. Can decide for yourself though, thanks for your guys' work on this project!

**Comment by graemeblackwood** [comment]
@jenic 

This works well for latest Chrome and FF on Mac. But completely breaks Safari:

![image](https://cloud.githubusercontent.com/assets/646863/10614671/6843e684-7753-11e5-8fdf-a7fd2cf5d2b6.png)

**Comment by jenic** [comment]
@graemeblackwood 

So, I will preface this by saying I only use Linux and know very little about Safari so please don't crucify if I'm wrong! But, it looks like Safari doesn't support this feature just yet based on these two sites ([1](http://iswebrtcreadyyet.com/) [2](http://caniuse.com/rtcpeerconnection/))
Though it looks like once it does support it we may need to do something about the iframe sandboxing issue.

If I'm mistaken please advise!

**Comment by graemeblackwood** [comment]
Yes, I think you're right about lack of support. But it should fail silently, not break the whole script.

We should do some checks first before attempting to run it.

**Comment by jenic** [comment]
@graemeblackwood Ah I see what you mean, I'm slow, ha. [This commit](https://github.com/jenic/fingerprintjs2/commit/1452932c98410c04c85a5b653445a88de8f6f987) attempts to address that though for obvious reasons I cannot test it.

**Comment by graemeblackwood** [comment]
@jenic Getting there. The device ID hash generates but it generates a keys error now.

![image](https://cloud.githubusercontent.com/assets/646863/10734153/c1bf5284-7bf9-11e5-89f2-1ed3d85a8200.png)

**Comment by jenic** [comment]
@graemeblackwood Well I've been looking at those lines but I have no idea why it says keys isn't defined. Any ideas?

**Comment by Jnull** [comment]
I hope this is useful, but i rewrote the webrtc function [Gist](https://gist.github.com/Jnull/f3c7f28cca3ba13e5e62).  I mainly wrote to help avoid the [1000 millisecond setTimeout](https://github.com/jenic/fingerprintjs2/blob/1452932c98410c04c85a5b653445a88de8f6f987/fingerprint2.js#L199).  

What i did was daisy chained off of the 'pc.onicecandidate' listener to count both the icecandidate & looped sdp lines. When the condition of both are equal length, then all icecandidates are sent to the callback.   Note: I'm using hybrid es6 (I'll babel it back if need be) If it's found workable I'll make a PR, or let one of you mangle it.  Hope it helps.

**Comment by abmmhasan** [comment]
I think you are looking for this!
https://github.com/muaz-khan/DetectRTC

**Comment by Valve** [comment]
I'm sorry for closing, but we'll be concentrating on stabilizing the library, not on adding new features in the foreseeable future. Closing as a non-feature.

**Comment by sorahn** [comment]
I'm starting to research webrtc fingerprints for work, and it turns out that the new version of safari included with ios11 includes "full webrtc support".  Which seems to include leaking unique device ids (browserleaks.com/webrtc).

So far I've confirmed that mobile safari does leak unique device fingerprints from webrtc.

<img width="320" alt="image-1" src="https://user-images.githubusercontent.com/588852/27197162-11b51806-51c2-11e7-8738-b504c8d86722.png">

@Valve are you still interested in adding webrtc fingerprinting to this library?

**Comment by Valve** [comment]
@sorahn, I've stopped working on this library and looking for a maintainer

**Comment by NawarA** [comment]
@Valve I'll help maintain code, add new open source code and new functions, vet pull requests, etc

**Comment by Valve** [comment]
thanks, @NawarA
