### ISSUE TITLE
Same Hash for iPhones of same model?

### ISSUE THREAD

**Issue by SBejga** [Valve/fingerprintjs2#122]
Hi,

at first I'd like to thank you for publishing this greate piece of library. 

But I just noticed, that If I open my project using fingerprintjs2 on my two iPhone 6 (yes, I have two, one for private and one by my company for business). They both have the same hash. 

Ok I considered, they have of course the same browser (UA) with same plugins (should not recognize plugins?) and of course same resolution etc. Should also have the same amount of fonts, because you get only the system fonts of iphone.

So currently I brainstorm a bit, how it would be possible to fingerprint the mobile devices in a good matter because of their less fingerprint options. 

Are there any thoughts and researches especially for the problem of the same hash for different mobile devices of the same model type? Currently I would think, that for mobile devices there is no good way to identify the client without cookies, isn't it?

KR

**Comment by Valve** [comment]
Yes, are're correct. Unfortunately it's not possible to generate 2 different fingerprints for identical devices. That's the main reason why FP-ing cannot be relied upon as a single method of identification. It should be a component in the collection of multiple identifiers (cookie-stored ids, IP addresses, etc). I need to create a FAQ page that explains all this, but now I don't have much spare time (if at all)
