### ISSUE TITLE
iPad fingerprint

### ISSUE THREAD

**Issue by maverick42** [Valve/fingerprintjs2#123]
Hi,.

On PC (multiple browsers) the fingerprint key is **stable**. It changes only if I add new plugin or such that the browser is updated ... Perfect !

But on my ipad the key is **unstable** !  If I open mutiple tabs with your sample page, restart safari ... I get a new key (even a few seconds of ...) ??! 

Do you have an idea to avoid this?

Regards
Frédérik

**Comment by Valve** [comment]
Hi, thanks for letting me know. I'll verify it during this weekend.

**Comment by johnmelba** [comment]
It happen to the macbook when it connect to a bigger screen. 
So what I do is 
var options = {
    excludeAvailableScreenResolution:true,
    excludeScreenResolution:true
  }; 
somehow the new tab will have different resolution at the beginning then it will change back to normal.

**Comment by jonashaag** [comment]
Not aware of it, closing due to lack of info.
