### ISSUE TITLE
Font detection slow

### ISSUE THREAD

**Issue by msp** [Valve/fingerprintjs2#126]
Hey, thanks for the library!

Any idea why the font detection is slow? My numbers seem way above from what you quote in the README. I'm using the default config.

Approx 4 seconds in Chrome and longer in Safari..

Fingerprinting INIT took 0.5349999999998545 milliseconds.

application.js:75591 userAgentKey:0.45499999999992724 milliseconds.
application.js:75595 languageKey:0.1449999999999818 milliseconds.
application.js:75599 colorDepthKey:0.14000000000032742 milliseconds.
application.js:75603 screenResolutionKey:0.3049999999998363 milliseconds.
application.js:75607 availableScreenResolutionKey:0.2899999999999636 milliseconds.
application.js:75611 timezoneOffsetKey:0.16499999999996362 milliseconds.
application.js:75615 sessionStorageKey:0.12500000000045475 milliseconds.
application.js:75619 localStorageKey:0.26499999999987267 milliseconds.
application.js:75623 indexedDbKey:0.1999999999998181 milliseconds.
application.js:75627 addBehaviorKey:0.205000000000382 milliseconds.
application.js:75631 openDatabaseKey:0.17000000000007276 milliseconds.
application.js:75635 cpuClassKey:0.525000000000091 milliseconds.
application.js:75639 platformKey:0.38499999999976353 milliseconds.
application.js:75643 doNotTrackKey:0.15000000000009095 milliseconds.
application.js:75647 pluginsKey:1.1000000000003638 milliseconds.
application.js:75651 canvasKey:23.725000000000364 milliseconds.
application.js:75655 webglKey:82.53499999999985 milliseconds.
application.js:75659 adBlockKey:0.2250000000003638 milliseconds.
application.js:75664 hasLiedLanguagesKey:0.15000000000009095 milliseconds.
application.js:75668 hasLiedResolutionKey:0.14000000000032742 milliseconds.
application.js:75672 hasLiedOsKey:0.3599999999996726 milliseconds.
application.js:75676 hasLiedBrowserKey:0.5149999999994179 milliseconds.
application.js:75680 touchSupportKey:0.3700000000003456 milliseconds.

application.js:76013 FONTS:4081.925 milliseconds.
application.js:75694 fontsKey:4172.885 milliseconds.

XX:585 Fingerprinting GET took 4292.765 milliseconds.

**Comment by Valve** [comment]
Yes, it's slow, but in your case it's unusually slow, probably because you're running the FP test on either a lower-end smartphone or on an old PC. On my desktop the FP process takes 40-50 ms on average.

Overall, the slowness is because font detection does a lot of DOM manipulation in the background. It's dynamically creating a DOM element with a font under test and then destroys it.
If you have ideas of how to make the process faster, please let me know.

**Comment by msp** [comment]
Hmm strange, I'm on a MBP.
I'll dig into it more if I get a chance.. 

MacBook Pro (Retina, Mid 2012)
2.6 GHz Intel Core i7
16 GB 1600 MHz DDR
Intel HD Graphics 4000 1024 MB

**Comment by Valve** [comment]
That's strange, I have a similar MBP too (Mid 2012 Core i5), it's ~90ms there

**Comment by msp** [comment]
Wanna swap? ;)

Ok, I'm still prototyping so not an immediate concern but will look if I can. Shout if you think of any useful pointers.

Thanks for the quick responses!

**Comment by Valve** [comment]
Haha, cool, let me know if you need more help with this

**Comment by msp** [comment]
Our project has a load of existing JS. Something (probably Backbone or Underscore) was mixing in a load of noise to the Array prototype so font detection iterated The World rather then [3 fonts](https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L335) you'd expect.

Cheers

**Comment by Valve** [comment]
fixed in 1.1.1
