### ISSUE TITLE
What about Mobile browsers?

### ISSUE THREAD

**Issue by ultramaks** [Valve/fingerprintjs2#127]
I use your code to get fingerprints of users who visit my guestbook and deny access some of them (trolls etc)
But as I have 2 versions of guestbook (ordinary and mobile) I found out that mobile users can't give me their fingerprints. For example you can try [Opera Mobile Emulator](http://www.opera.com/ru/developer/mobile-emulator) and probably due to issues with JavaScript the fingerprint cannot be detected
I wonder is this a bug and can this be resolved somehow?

**Comment by Valve** [comment]
Thanks for letting me know. I will need to test it on the emulator.

**Comment by ultramaks** [comment]
I wonder is it possible at all to make this fingertip working for mobile browsers... they all often lack some javascript functionality - e.g. opera mini seems not to support JavaScript by default [article](https://dev.opera.com/articles/opera-mini-and-javascript/)
In this case I should look into something that works on server (PHP). I wonder are there anything like these tool made on the serverside?

**Comment by Valve** [comment]
It's working on all browsers with JS support. According to wikipedia (https://en.wikipedia.org/wiki/Opera_Mini#JavaScript_support) Opera mini does not run JS in the browser, so JS will not work there and FPJS too. I think there is nothing I can do here.
Please let me know if you have additional thoughts about it and feel free to reopen the issue
