### ISSUE TITLE
Is there a way to prevent an attacker from generating zillion fingerprints?

### ISSUE THREAD

**Issue by yairpe** [Valve/fingerprintjs2#132]
The whole purpose of human fingerprints is to uniquely identify a person. But an attacker can easily generate a different random digital fingerprint every time so his scripts appear as many different machines.

Is there a way to prevent it?

Thanks

**Comment by Valve** [comment]
Could you please explain what you mean by "_can easily generate a different random digital fingerprint every time so his scripts appear as many different machines._"?

**Comment by yairpe** [comment]
sure. Let's say site X is using fingerprintjs2 to identify user machines to enable them to comment (or 'like') without needing to login. It even blocks multiple comments from the same signature.

So fingerprintjs2 works hard to gebnerate quite a unique fingerprints string using the hash function. And the source code is open of course.

Now some hacker can quite easily write a script that every time that the script access a page in site X with comments, generate a dummy fingertip and use it.

The server than believes that it's another user and allow the comment.

Well comments can be reduced to a certain level with tools like akismet but what about 'Likes'?

And even if I tamper with the library code and add some extra info like checksum to check it on the server, it is still open javascript code at the client side.  

Hope I've made my point clear.

**Comment by Zate-ZOS** [comment]
you cannot replace authentication with a fingerprint.  fingerprint is generated client side, an attacker will ALWAYS be able to fake it/spoof it.  Fake/spoofed FP's are generally easy to spot though when looking through large data sets but your example about using it to do something without needing to login is terrible security.

**Comment by Valve** [comment]
@yairpe yeah, you're trying to misuse the library. If you want to prevent people from voting/liking 2+ times, fpjs is not sufficient for this. You need some additional tools, like cookie storage
