### ISSUE TITLE
How to get getResolution or getScreenSize for cookie

### ISSUE THREAD

**Issue by NJseo** [Valve/fingerprintjs2#136]
Call details for use in Cookie drop. How to do this?

**Comment by Valve** [comment]
Could you please elaborate? Don't understand you

**Comment by NJseo** [comment]
Yeah, I read the contributing, but that didn't help me out. In your documentation, you have various ways to exclude or include portions of the print. Now where in there did it describe methods to just get single aspects of the entropy out of the fingerprint.js file.  Is there a call I could make to just get back single aspects like platform name, the screen size, isMobile, isDesktop, or isTablet?

**Comment by Valve** [comment]
You can try using the second parameter of the `get` method. It returns an array of all components that were used in FP calculation

**Comment by NJseo** [comment]
Maybe you can give me a hand with this, as I am still struggling. When I tried like you said, I get a fingerprint returned.

**Comment by Valve** [comment]
@NJseo try something like https://jsbin.com/moxoqusuwa/edit?html,output
