### ISSUE TITLE
Is there some nodejs example

### ISSUE THREAD

**Issue by chaegumi** [Valve/fingerprintjs2#140]
TypeError:fingerprint2.get is not a function

```javascript

var http = require('http');
var fingerprint2 = require('fingerprintjs2');

http.createServer(function(request, response){
	console.log(fingerprint2);
	
	fingerprint2.get(function(result, components){
		  console.log(result); //a hash, representing your device fingerprint
		  console.log(components); // an array of FP components
		});
	
}).listen(8080);

console.log('server start on http://127.0.0.1:8080/');

```

**Comment by jhuenges** [comment]
The fingerprint needs to be calculated on the client.

**Comment by chaegumi** [comment]
@jhuenges 
why readme.md include 
 npm install fingerprintjs2

**Comment by jhuenges** [comment]
This needs to happen on the client side (eg. browser)
```js
new Fingerprint2().get(function(result, components){
  console.log(result); //a hash, representing your device fingerprint
  console.log(components); // an array of FP components
});
```

**Comment by trendsetter37** [comment]
@chaegumi that means you can install the files with npm but you still have to use it on the client side as @jhuenges says. The code you posted is trying to use fingerprint on the server side.

**Comment by chaegumi** [comment]
oh thanks

**Comment by manjudr** [comment]
@chaegumi  @trendsetter37 @jhuenges 
Can you help us we are getting this error when we trying use it on server side

``` 
ReferenceError: window is not defined
```

**Comment by manjudr** [comment]
Does fingerPrintjs2 support for server side?

**Comment by jhuenges** [comment]
See 4 comments above.
