### ISSUE TITLE
Keystroke fingerprinting

### ISSUE THREAD

**Issue by JosefJezek** [Valve/fingerprintjs2#143]
Could you add Keystroke fingerprinting?

- http://narcvs.com/javascript/fingerprint/
- https://lists.freedesktop.org/archives/wayland-devel/2016-March/027607.html
- https://paul.reviews/behavioral-profiling-the-password-you-cant-change/

**Comment by Valve** [comment]
I'm sorry for closing, but we'll be concentrating on stabilizing the library, not on adding new features in the foreseeable future. Closing as a non-feature.
