### ISSUE TITLE
Not working in Salesforce Lightning

### ISSUE THREAD

**Issue by Rajinder-dx** [Valve/fingerprintjs2#145]
I am using this lib(fingerprintjs2) in Salesforce lightning component's JS controller and when I try to call it as following it always return "Cannot read property 'extend' of undefined" error. And I notice that "this" keyword which is used in the lib(fingerprintjs2) is always show "undefined" 

new Fingerprint2().get(function(result, components){
          console.log(result);
});

**Comment by Valve** [comment]
Please help me diagnose this, because I don't have access to lightning and don't even know what this is

**Comment by Rajinder-dx** [comment]
hi,

Salesforce is CRM "http://www.salesforce.com/"  and this CRM also provide some UI to create custom page called "Lightning". this is similar to "AngularJS".  

I am using fingerprintjs2 in it and it creating some issues in there.

I have notice that there is problem with  compatibility of "fingerprintjs2"  and "Lightning".  I think this is not your problem

btw I haved solved the problem. 

Lightning use "this" keyword to locate his data variable and your lib. also use "this" keyword. so this was the problem

Thanks for your reply.

**Comment by Valve** [comment]
ok, I'll close the issue then
