### ISSUE TITLE
Uncaught ReferenceError: Fingerprint2 is not defined

### ISSUE THREAD

**Issue by hollodk** [Valve/fingerprintjs2#146]
I have experienced some problems with Fingerprint2 is not defined, i think it has to do with window.module in some way. I can replicate it every time.

Try this url http://oferta.noznore.es/subscrption-1/

**Comment by Valve** [comment]
Thanks for letting me know, it is probably related to incorrect module export setup. I have never used module system in JS, so need to read about it first.

**Comment by misslv** [comment]
Listen what you said, improving my poor English.

**Comment by timelf123** [comment]
Confirmed, this doesn't support module loaders CommonJS/webpack etc

**Comment by Valve** [comment]
@timelf123 I'm not using module loaders you mentioned, so please submit a PR if you need this functionality.

**Comment by timotic** [comment]
Just wanted to clarify. Was a fix actually made on this issue? I seem to encounter the same problem and I'm on version 1.1.1

**Comment by Valve** [comment]
This issue was never fixed.

**Comment by timotic** [comment]
Thanks Valve. Was there a problem to fix in the first place?

**Comment by Valve** [comment]
According to ticket #92 some people cannot use the library with module loaders. I'm not using them so cannot say more about it
