### ISSUE TITLE
Confirm Formula

### ISSUE THREAD

**Issue by jupitercow** [Valve/fingerprintjs2#148]
After having a user generate a number of false records in our db, I am wondering if there would be anyway to confirm the 32 character strings in our db to see if they were created through fingerprintjs2 or randomly by the user's string generator?

Like are there uppercase characters in Fingerprint JS's strings?

Any help would very appreciated!

Thanks.

**Comment by Valve** [comment]
If you mean if there is a specific pattern in the finterprint, no there isn't and you cannot tell if a fingerprint was a fake or real,sorry

**Comment by jupitercow** [comment]
Thanks for the quick response. I am seeing what I can do.

The issue is a voting system that tracks non-logged in users. I see that on posts with a resonable amount of votes over time, there are no uppercase letters in any of the ids we stored. In the ones that jumped up tens of thousands recently, There are. Is this just anomoly, or is it possible that the hashes don't use uppercase? I am trying to confirm that. It would probably be my only hope...

Thanks again. This library has been very useful. We fixed the hack with a server nonce.

**Comment by Valve** [comment]
It's using `Number.prototype.toString()` with radix of 16 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString)
here: https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L1206
which always produces lowercase letters.
Closing for now, please feel free to reopen
