### ISSUE TITLE
Fonts detection improved performance?

### ISSUE THREAD

**Issue by lrlinde** [Valve/fingerprintjs2#149]
I noticed the performance was poor during fonts detection. 
The function 'detect' appends and removes the span from the body three times per font (see lines 367 - 377)
I was wondering if this could be modified so we add the span just once and remove it after checking all the fonts.
Aside from that, I would modify a bit the logic, so once a font is detected, we don't retry with the rest of default fonts.

Is there any reason to not doing this? Am I missing something?

**Comment by Valve** [comment]
No specific reason, the code for code detection is not mine, I took it from the site referenced in the comments. If you can improve the performance of this code and not break it - that is awesome, please submit a PR.

**Comment by Valve** [comment]
Fixed in v1.2.0
