### ISSUE TITLE
still loading in browser mozilla firefox 46.01

### ISSUE THREAD

**Issue by marcianorama** [Valve/fingerprintjs2#150]
with code below
<!DOCTYPE html>
<html lang="en">
<head>
        
</head>
<body>
		<script src="/apps/fingerprint2.min.js"> </script>
      <script src="/apps/client.min.js"> </script> 
	<script>
	        var fp = new Fingerprint2();
	        var client = new ClientJS();
	        var obj = new Object();
	        var jsonString='';
	       	fp.get(function(result,components) 
			{
			   obj.fingerprint = client.getFingerprint()+"|"+result;
			   obj.fonts  = client.getFonts();
			   obj.mimeTypes = client.getMimeTypes();
			   obj.browser = client.getBrowser();
			   obj.os = client.getOS();
			   obj.osVersion = client.getOSVersion();
			   obj.CPU = client.getCPU();
			   obj.userAgentLowerCase = client.getUserAgentLowerCase();   
			   obj.screenPrint = client.getScreenPrint();;
			   obj.currentResolution = client.getCurrentResolution();
			   obj.availableResolution = client.getAvailableResolution();
			   obj.colorDepth = client.getColorDepth();
			   obj.browserVersion = client.getBrowserVersion();
			   obj.browserMajorVersion = client.getBrowserMajorVersion();
			   obj.engine = client.getEngine();
			   obj.engineVersion = client.getEngineVersion();
			   obj.plugins = client.getPlugins();
			   obj.device = client.getDevice();
			   obj.deviceType = client.getDeviceType();
			   obj.deviceVendor = client.getDeviceVendor();
			   obj.timezone_offset = components[5].value;
			   obj.session_storage = components[6].value;
			   obj.local_storage = components[7].value;
			   obj.indexed_db = components[8].value;
			   obj.open_database = components[9].value;
			   obj.cpu_class = components[10].value;
			   obj.do_not_track = components[12].value;
			   obj.adblock = components[16].value;
			   obj.has_lied_languages = components[17].value;
			   obj.has_lied_resolution = components[18].value;
			   obj.has_lied_os = components[19].value;
			   obj.has_lied_browser = components[20].value;
			   obj.touch_support = components[21].value;
			   obj.local_time= Date();
			   obj.time_zone= new Date().toString().match(/\(([A-Za-z\s].*)\)/)[1];
			
			   var jsonString= JSON.stringify(obj);
			   
			   document.write(jsonString);

			}
	        );
				
		</script>
</body>

</html>

please help me

**Comment by Valve** [comment]
I don't understand this issue. Please read 'contributing.md'
