### ISSUE TITLE
security vulnerability: XSS through FontList.swf

### ISSUE THREAD

**Issue by iancu-caputa** [Valve/fingerprintjs2#151]
After you host FontList.swf on your domain, and you directly request the swf file:
http://example.com/lib/fingerprint/FontList.swf?onReady=alert(document.domain)
you will get some XSS.

Apparently the problem comes from the way parameters are being read in the flash plugin, which is falling back to URL parameters if script parameters were not found.

Please fix.

Best regards,

**Comment by Valve** [comment]
Oh crap, I need to remove this flash plugin, only troubles from that. Please stop using flash font detection, because it's deprecated anyway, I'll remove the flash component in version 2.
I will update the readme saying that flash font detection is deprecated

**Comment by Valve** [comment]
I think I will just test all the accumulated PRs, remove flash and release flash entirely on this weekend.

**Comment by iancu-caputa** [comment]
That will be excellent

Thank you!

**Comment by Valve** [comment]
Good news, in v.1.2.0 CSS+JS font detection just got 3.5x times faster!
See this: https://github.com/Valve/fingerprintjs2/pull/152
definitely no reason to use flash now.
I'm closing for now, because removing Flash is already on my TODO list, just don't use it anyway
