### ISSUE TITLE
how to get params in get?

### ISSUE THREAD

**Issue by pingfengafei** [Valve/fingerprintjs2#153]
```js
'use strict';
import FingerPrint from 'fingerprintjs2';
var _dfp;
var _component = {};
new FingerPrint().get((dfp, components) => {
            _dfp = dfp;  
            components.forEach((component, index) => {
                _components[component.key] = component.value;
            });
        });

        console.log(this.dfp); //void
        console.log(_components); //void
```
I can not get the correct dfp and components.
it seems in the get function:
get --> fontsKey --> jsFontsKey -->setTimeout(..., 1);
caused this!

why has 1 millisecond delay？and how can I get correctly results？

**Comment by Valve** [comment]
No, this 1ms delay is not relevant.
See working fiddle here: https://jsfiddle.net/5oo85ph4/
