### ISSUE TITLE
Questions about the use of AdBlock and User-Agent

### ISSUE THREAD

**Issue by noehmeier** [Valve/fingerprintjs2#157]
**Why just check for AdBlock and not remaining Blocker**
I thought first, the check for AdBlock is for all AdBlocker, but i see it checks just for AdBlock. AdBlock is just for Chrome available, and has a market share of 38% of used AdBlocker in 2015. More famous is AdBlock Plus, but also uBlock, uBlock Origin and Adguard AdBlock are rising. So, why is there no detection for all of them AdBlocker, there are solutions available, like for paywalls. I read in an issue here, that it needs seperate JavaScript files and can maybe not be included, is that the reason?

**Why no plausibility check between AdBlock and Chrome Browser**
Also, i don't understand, why there is no plausibility check for browser manipulation. If someones AdBlock plugin is detected, the user must have Chrome as browser. If it is not Chrome, the browser type is manipulated. Or not?

**Why the use of the full User-Agent?**
Another question is about the User-Agent. Fingerprintjs2 uses the full UA for the fingerprint, including the Browser Version. Chrome and Firefox change their versions in weeks and months, so the duration, how long a user can be tracked, is limited to that. Would it not be a better solution, to extract most of the parts, like encoding, language, browser- and os-names - and dont include the versions into the fingerprint, or is that a bad idea? I also know, that i can exclude the whole UA, but most of the parts are useful in my opinion.

**Comment by Valve** [comment]
Agree on all, specific answers below.
1. I don't have time to implement all of these, and I only received a PR for AdBlock. The rest was never proposed in a PR.
2. PR for AdBlock was merged like 2 days ago, and although your idea is right and valuable, it takes time to implement/write specs etc which I don't currently have.
3. We already have a ticket for this: https://github.com/Valve/fingerprintjs2/issues/5
Overall - UA parsing is a complex subsystem which needs to be added and again - limited human resources.

If you feel like contributing, I'd be glad to accept your code.

Thanks!
