### ISSUE TITLE
Wrong fingerprint when first run.

### ISSUE THREAD

**Issue by ukid** [Valve/fingerprintjs2#158]
Code from demo
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<script type="text/javascript" src="fp.js"></script>
<script type="text/javascript">
	new Fingerprint2().get(function(result, components) {
		console.log(result); //a hash, representing your device fingerprint
		console.log(components); // an array of FP components
	});
</script>
</head>
<body>
</body>
</html>
```

And the results are:
![0f8a7417-943d-4116-8dce-c6d998672f0b](https://cloud.githubusercontent.com/assets/1004222/15533732/8aadb038-2298-11e6-8579-578626a88bfc.png)

I can provide more information about this issue.Post what you need.

**Comment by Valve** [comment]
Try disabling WebGL and let me know if it continues to be different

**Comment by ukid** [comment]
![9a4250ae-28e6-43c6-8788-aedb5d36beee](https://cloud.githubusercontent.com/assets/1004222/15563172/b8b013fe-2338-11e6-999b-581152ae2264.png)
It's hard to reproduce the issue.Maybe something changed after the first run.I'm closing it now.

**Comment by Vanhecke** [comment]
I have the same issue and I can reproduce it by either re-starting firefox and re-starting chrome incognito.
The issue however seems to related to the demo code / button.
I changed the javascript to just run on page load (I removed jquery) and since then the fingerprint became stable.
