### ISSUE TITLE
Research touch screen based fingerprinting

### ISSUE THREAD

**Issue by Valve** [Valve/fingerprintjs2#16]
like maximum touch points, etc

**Comment by NawarA** [comment]
navigator.maxTouchPoints is a good measure. 

Also, document.createEvent('TouchEvent'), may work if the device is touch capable, or fails if the device has a regular screen (depending on OS / browser).

**Comment by Valve** [comment]
basic functionality added in a335eb3ba4f908b37514e9ae67b149b0e636d947
