### ISSUE TITLE
Some people not being fingerprinted

### ISSUE THREAD

**Issue by BobSmithJoe** [Valve/fingerprintjs2#173]
Hi there,

Great product!

Question. Is there any debugging or any logging I can use to figure out why some people arent being fingerprinted? I'm not talking about changing fingerprint -- I understand people can easily change their fingerprint. I'm talking about not getting any fingerprint, period. Majority of people this is working fine.

Thanks!

EDIT: To clarify, the people not being fingerprinted have JavaScript enabled.

**Comment by Valve** [comment]
Hi Thanks,

Have no idea :)  Try collecting more details from these people to start having some clues, otherwise impossible to know

**Comment by MacWarrior** [comment]
Hi, 

Hope this can help : https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode

**Comment by jimport** [comment]
Hej, 
I am not shure if it's the same issue, but I was checking out the Panopticlick tool from the EFF and playin' around with some Firefox addons. When I disable canvas support using the Random Agent Spoofer addon (https://github.com/dillbyrne/random-agent-spoofer), the fingerprinting test won't stop loading. If it's enabled I get the 'your browser has a unique fingerprint' warning.
If you need more info, let me know. Hope it helps.

**Comment by Valve** [comment]
Thanks, @jimport. Not sure if this will go into v2, though

**Comment by Valve** [comment]
Closing as a dup of #65
