### ISSUE TITLE
Results of each test individually

### ISSUE THREAD

**Issue by slacker69** [Valve/fingerprintjs2#175]
Is there a test index.html file that will display the results for each test individually? I'd like to know to do that.

**Comment by Valve** [comment]
I've started (Finally) working on V2, and I will add this capability there.

**Comment by banksec** [comment]
Hi,
is it now possible to get results of each test (UserAgent, Language, Color Depth etc), not only hash of all parameters?

**Comment by skiperz** [comment]
Добрый день!
Как установить этот скрипт , и как его настроить чтоб при посещении сайта отпечатки заносились в бд ?

**Comment by Valve** [comment]
добавляете на страницу html код скрипта, затем посылаете череез ajax полученный отпечаток и делаете в базе insert into fingerprints(fingerprint) values $fingerprint.

**Comment by skiperz** [comment]
Что является "кодом скрипта"
Это- ?
new Fingerprint2().get(function(result, components){
  console.log(result); //a hash, representing your device fingerprint
  console.log(components); // an array of FP components
});

**Comment by skiperz** [comment]
Напишите пожалуйста код ajax и как выполнить это действие "делаете в базе  into fingerprints(fingerprint) values $fingerprint."
