### ISSUE TITLE
Calling FPJS2 repeatedly on the same page more than 16 times produces a warning

### ISSUE THREAD

**Issue by Valve** [Valve/fingerprintjs2#176]
I'm using the latest version of FPJS2 in Firefox 47. When calling the FPJS library more than 16 times on a page, I get this warning:

```
Error: WebGL: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.
```

**Comment by Valve** [comment]
Nice! thanks for the info

**Comment by justdmitry** [comment]
This code should be written inside FPJS2, not in outside/calling code, right?

**Comment by jonashaag** [comment]
Definitely, PR welcome

**Comment by ProcrastinatorCp** [comment]
@jonashaag 
Hi, Could you please check : https://github.com/Valve/fingerprintjs2/pull/484
