### ISSUE TITLE
FingerPrint2 is giving new id every day

### ISSUE THREAD

**Issue by vickysmiles555** [Valve/fingerprintjs2#178]
I am calling fingerprint as below 
 var fingerPrint;	
	 new Fingerprint2().get(function(result,components){
	 fingerPrint = result;}//a hash, representing your device fingerprint});
	 )
	 console.log(fingerPrint)
two days back it gave me "1fe43a69c19661f0261986af44af62d4" and when i tested today it is giving me "80d759098d511338dc17c4f9fd8be044"

Browser Type - Chrome 
Browser Version - 51.0.2704.106.

This is also reproduced in IE Browser Version 11.0

**Comment by Valve** [comment]
Why do you think this is a bug? Also your title is misleading, you're staging that you saw 2 different FPs, but the title says that it's giving new id every day. 
If you have more specific information to indicate that this is a bug indeed, feel free to reopen the issue with additional information attached.

**Comment by vickysmiles555** [comment]
I am under assumption that fingerprint2 supposed to give uniqueid for a browser per machine but instead it is giving new id every day.  I tested on friday and monday, the id's changed.

**Comment by Valve** [comment]
it produces IDs that correspond to current state of the browser. If you browser changes (for example a minor version upgrade) - the ID will change as well.

**Comment by vickysmiles555** [comment]
I don't remember changing any browser version for IE or chrome, but i will let other developers from my test it and will let you know.

Thanks for your help.

**Comment by Valve** [comment]
Chrome updates automatically and can cause the fingerprint to change w/out you realizing it, so I think this is what happened in your case. I agree that this is not an optimal behavior and it is being worked on and will be addressed in https://github.com/Valve/fingerprintjs2/milestone/1

**Comment by sakibkhan** [comment]
Valve Sir its giving Diffrent FingerPrint id in Diffrent browsers in the same system

**Comment by sakibkhan** [comment]
Can you fix it
