### ISSUE TITLE
Changing the hash-function

### ISSUE THREAD

**Issue by commerce-experts** [Valve/fingerprintjs2#18]
Hi and thx for this beautiful piece of software :-)
I'm playing around with fingerprinting libs quite some time know and really like your approach.
Apart from adding more fingerprinting methods the only thing that I would like like to improve is the consistency of fingerprints during a device lifecycle.

For example there are some params that won't change over time, some that will but in a given direction (plugin versions) and some that are highly fluctuating. 
With the current hash method we always end up with a new fingerprint and need to "fuzzy match" them server-side.

Maybe we could introduce a more intelligent way of building our fingerprint by things like: https://github.com/ethanlim/ccmf#locality-sensitive-hashing-lsh
and therefore reduce the server-side effort?

**Comment by Valve** [comment]
Hi @commerce-experts, 
Thanks for thanks :)

Yes, you're right, murmurhash is not the optimal hashing here, we've been discussing LSH for some time on the gitter.im channel.
Currently I'm not spending a lot of time on the project, having some side things to prepare for, but this is definitely on my todo list.

Thanks!

**Comment by ahfeel** [comment]
:+1: Has anything been done towards more fuzzy matching yet ? :)

**Comment by Valve** [comment]
So for now (for version 2) a plugin/extension system will be developed, which will allow you to replace a hashing function. Closing in favor of https://github.com/Valve/fingerprintjs2/issues/177
