### ISSUE TITLE
excludeUserAgent issue if I spoof my UA fingerprint is different 

### ISSUE THREAD

**Issue by adzbiz** [Valve/fingerprintjs2#180]
excludeUserAgent seems to doesn't works. I'm testing Fingerprintjs2 on Chrome with "Chrome UA Spoofer" extension to "fake User Agent" (https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg)
and each time I choose another useragent my fingerprint changes...

https://cdn.jsdelivr.net/fingerprintjs2/1.4.1/fingerprint2.min.js
 var options = {excludeUserAgent:true};
 new Fingerprint2(options).get(function(result){
 console.log(result);

**Comment by Valve** [comment]
when you exclude it, it's definitely not being used. Probably the issue is that some other components change along with the UserAgent change. Please let me know which other components are different for you.
You can view the components by examining the second argument of the get callback function:

```
new Fingerprint2(options).get(function(result, components){ ...
```

**Comment by denis-n** [comment]
I have a question: do you think it's best practice for mobile devices to have this meta tag?

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">`
