### ISSUE TITLE
Everty time was different while using iOS safari and Alipay

### ISSUE THREAD

**Issue by jrainlau** [Valve/fingerprintjs2#181]
hello, fingerprintjs2 is aweasome, but there are something I am confused. I made a html page and using `fingerprintjs2`. However, every time I open the page by iOS safari, the result was different, and I don't have any idea about it. Are there anyting wrong with my usage? Thanks a lot!

**Comment by Valve** [comment]
Probably something in your browser is changing every time you run the library.
Please let me know which of the fingerprinting components is different for you. You can view the components with:

```
new Fingerprint2().get(function(result, components) {...
```

**Comment by denis-n** [comment]
I have a question: do you think it's best practice for mobile devices to have this meta tag?

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

**Comment by Valve** [comment]
@denis-n I fail to see how your question is related to this library. Please use Stackoverflow.com for such questions

**Comment by denis-n** [comment]
The reason why I was asking - I tried fingerpringjs2 both ways - first without this and after that with this tag (well, there were some other meta tags).
After adding the tag the code generated by your library changed from what it was before. 
But it doesn't change since then.

**Comment by Valve** [comment]
You can let me know why the code was different by examining the components and letting me know which component changed for you, @denis-n

**Comment by jrainlau** [comment]
u r right, after printed out all the `components` infomation, I found that my `user-agent` changed frequently. That's my own problem. Thank u very much!

**Comment by Valve** [comment]
you are welcoe, @jrainlau
