### ISSUE TITLE
The same fingerprint for multiple phones

### ISSUE THREAD

**Issue by SvetZitrka** [Valve/fingerprintjs2#182]
We did tests and found out that several mobile phones can have a puppy fingerprint.
Specifically, we tested several phones Nexus 5.

Can you think of a solution to odliřit fingerprints for mobile phones?

**Comment by Valve** [comment]
I know about this issue and it's an unsolved one, there is no reliable way (or at least I know of none) to identify identical mobile devices

**Comment by SvetZitrka** [comment]
Thank you for answer. A plan in the future, at least for some activity to increase the percentage chance of resolution of mobile devices? supercookie etc. Something like https://panopticlick.eff.org/results?&a=111&t=111&dnt=111#fingerprintTable
