### ISSUE TITLE
Allow excluding build number from browser's version

### ISSUE THREAD

**Issue by unoexperto** [Valve/fingerprintjs2#184]
I think we should allow excluding build number from browser's version since updates can be frequent.

**Comment by Valve** [comment]
This has been discussed in
https://github.com/Valve/fingerprintjs2/issues/5
https://github.com/Valve/fingerprintjs2/issues/97
https://github.com/Valve/fingerprintjs2/issues/178
and will be addressed in https://github.com/Valve/fingerprintjs2/issues/177
