### ISSUE TITLE
Fingerprint is different the next day

### ISSUE THREAD

**Issue by klasver** [Valve/fingerprintjs2#190]
Hello,

Currently I am testing the fingerprint but the fingerprint changes every day on the exactly same machine / browser. Someone any idea? I am using the default configuration.

```
new Fingerprint2().get(function(result, components) {
		console.log(result);
		console.log(components);
});
```

**Comment by Valve** [comment]
Please read contributing.md and faq.md first. It's all answered there. Please also see maybe 10 tickets that were created about it in the past.
