### ISSUE TITLE
Firefox with disabled cookies

### ISSUE THREAD

**Issue by akoenig** [Valve/fingerprintjs2#195]
Firefox responds with a `SecurityError: The operation is insecure.` when one tries to access `localStorage` when cookies are disabled. Therefore, this exception will be thrown when trying to execute the example code from the `readme`:

```js
const Fingerprint2 = require('fingerprintjs2');

new Fingerprint2().get(function(result, components){
  console.log(result); //a hash, representing your device fingerprint
  console.log(components); // an array of FP components
});
```

**Comment by Valve** [comment]
Are you sure?

https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L612

It has been addressed a long time ago and working for me.

**Comment by Xavierh95** [comment]
This error seems to be still there.
If I'm disabling cookies of firefox, I got an error in console.

`new Fingerprint2({ excludeAdBlock: true }).get(function (result, components) {
       var browser_fingerprint = result;
})`

![screen shot 2017-10-13 at 10 22 09](https://user-images.githubusercontent.com/7370867/31536854-71041522-b000-11e7-8cf9-0e085b45715c.png)

**Comment by jonashaag** [comment]
Please try to reproduce this in a fresh Firefox installation, with v1.5.1, and if you can reproduce it, tell your Firefox version and exact setup.

**Comment by zerob4wl** [comment]
I have this issue yet. My Firefox version is 58.0.2 (64-bit).

**Comment by jonashaag** [comment]
Can you please post your error console trace back and the fingerprintjs version you are using?
