### ISSUE TITLE
reducing size of minified code after gzip compression (currently 10KB) [feature suggestion]

### ISSUE THREAD

**Issue by elad-yosifon** [Valve/fingerprintjs2#196]
At the moment the code is written in a fairly wasteful (raw js output size) manner.
I can suggest several ways to reduce size considerably.
These suggestion aligns nicely with several v2 milestones (mostly extension system and features I need personally) , and **I'm willing to implement them myself**.

#### 1. breaking the code into modular and static components
* e.g. extracting hash functions to a static context
* e.g. enabling prototype inheritance / passing extended methods in options (not sure this is a good idea)

#### 2. using Closure-Compiler to compile/minify the code
* that will add a lot of out-of-the-box code optimizations (dead code elimination, function inlining, constant extractions, etc...)
* using JSDoc/Closure-compiler annotations, even more optimizations and code insights
* pre-processor/compilation flags - better control over final compiled code

#### 4. etc ...

This change is pretty big and will probably need a massive refactoring of existing code.
I'm willing to take this job on myself, but we need to coordinate this procedure before I begin.

If you are into this idea, I think I can accomplish that over this weekend.

Please advise..

**Comment by Valve** [comment]
Please let me know what a "static context" is, I don't know what this is :)

As for using closure compiler - I have no objections, if it can deliver better compression ratio.

Overall I agree that the library has become quite large.
If you really want to work on this, may I suggest to do it in a series of small, incremental changes, not as a huge refactoring. I will probably not be able to review it, given that I spend little to no time on this project currently.

**Comment by elad-yosifon** [comment]
"static context" means that it will not be a part of any created object ( new Object?(...) ), it is rather a "utility" that supports internal/external usage of related objects.

In our case, the murmur hash functions don't handle/affect any state of any instance of Fingerprint object. You can simply pass over a primitive string and get a primitive string as a returned value, there is no need to use ```this.murmurHashFunction...()``` of some sort.

that way compilers can collapse all the hash function internals into one large function (if it's size effective..)


Back to the main thread, needless to say that I will commit small surgical changes, and be 100% backwards compatible. 

I will need your support/consent to turn this code upside down and produce a better library.

I think it's best to take this discussion to an other communication form.
contact me at elad.yosifon@gmail.com **(I will remove this mail right after your next comment in order to avoid spam and bots scraping)**

**Comment by Valve** [comment]
please remove your email

**Comment by elad-yosifon** [comment]
done, I'm waiting for your mail ..

**Comment by evanjmg** [comment]
+1
