### ISSUE TITLE
How can i store fingerprint2 result in a var?

### ISSUE THREAD

**Issue by alipour66m** [Valve/fingerprintjs2#198]
I need to store fingerprint2 result in a var and use it in my javascript code.

new Fingerprint2().get(function(result){var info = {fingerprint: result};getsecure(info);});
function getsecure(data) {
secure = data.fingerprint;
}
I need secure here.

Is there a way to do it?
like fingerprint1 ?

**Comment by elad-yosifon** [comment]
@alipour66m  in your case there is no importance for the order of code execution, since the API is async.
You should do the things you need inside the callback.

BTW - v2 will support a synchronous get function (i.e. no callback)

**Comment by alipour66m** [comment]
Thanks for your replay
you mentioned "BTW - v2 will support a synchronous get function"
when it will be ready?
How can I get it?

**Comment by elad-yosifon** [comment]
@alipour66m - v2 is a work in progress. 
We can't provide estimates or commit to deadlines at the moment.
you can check the progress in v2 branch..

**Comment by Gowtham95india** [comment]
Hi @elad-yosifon 

 Does v2-synchronous is ready for production use?

**Comment by elad-yosifon** [comment]
@Gowtham95india I'm actually using it in production.
I still regard it as a "work in progress", but I think it is quite safe to use if you know how to compile it.
