### ISSUE TITLE
Implement social media use tests

### ISSUE THREAD

**Issue by gburtini** [Valve/fingerprintjs2#200]
https://robinlinus.github.io/socialmedia-leak/

By hitting a private page and checking for a redirect, you can see if a user is logged in. It's a simple check that requires 1 HTTP request. 

I am only proposing the idea for discussion - it might not be static enough to be appropriate for fingerprintjs2.

**Comment by Valve** [comment]
I think we'll concentrate on stabilizing the fingeprinting, not on adding new features for the foreseeable future, so I don't think we'll be adding this feature, sorry.
