### ISSUE TITLE
Uncaught error when Canvas Defender is installed

### ISSUE THREAD

**Issue by maxisme** [Valve/fingerprintjs2#205]
This [line](https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L785) is throwing an error when I call `Fingerprint2()`
I believe this is todo with me having [Canvas Defender](https://chrome.google.com/webstore/detail/canvas-defender/obdbgnebcljmgkoljcdddaopadkifnpm) installed!

**Comment by Valve** [comment]
Well, I'm not sure if the lib should do anything about it, but you can submit a PR which wraps this line in a try/catch to not crash

**Comment by jonashaag** [comment]
This is now fixed
