### ISSUE TITLE
Best way to uniquely identify!

### ISSUE THREAD

**Issue by abmmhasan** [Valve/fingerprintjs2#21]
Well, I just scrolled in your project & yes it's a cool project dude.

Need some more identification options for unique identification.
1. IMEI detection,
2. WLAN MAC address detection,
3. Serial number detection,
4. SIM detection

The best way to unique identification!

**Comment by Valve** [comment]
@abmmhasan how can one get those values in JavaScript?

**Comment by abmmhasan** [comment]
1. IMEI in Android can be found as <a href="http://stackoverflow.com/questions/27313331/how-to-get-device-unique-imei-number">Method 1</a>, <a href="http://stackoverflow.com/questions/7413305/retrieve-imei-number-sim-number-mobile-number-via-mobile-browser">Method 2</a> or <a href="https://community.oracle.com/thread/2613259">Method 3</a> . Though theses answers not perfect for JS. Another <a href="https://forum.jquery.com/topic/how-to-get-mobile-imei-code">Interesting read</a> says it's not possible. & After several read, I understood it will become a security issue if it relates with JS.
Solution: In my case what is the best way could be, using some app response which is already installed that phone, uses Hardware level or Root level security and is unique respond-er.
 2-4. LOL, now these express same manner as above. Security! :P
