### ISSUE TITLE
Importing from Typescript

### ISSUE THREAD

**Issue by melloc01** [Valve/fingerprintjs2#210]
Hi guys, I have been trying to load fingerprintjs2 within my typescript App but it seems the module loader can't find fingerprintjs2 module, my sample app is on Github: https://github.com/melloc01/ts-library-starter - there are some instructions the get the app running, thank you in advance

**Comment by bleuscyther** [comment]
this seems to work :   
`import Fingerprint2 from "fingerprintjs2";`
