### ISSUE TITLE
Canvas Fingerprinting explanation? 

### ISSUE THREAD

**Issue by dulevw** [Valve/fingerprintjs2#213]
Hello, 

I have a question about components array [15] (canvas). Are the values of them the hash values of canvas fingerprint? Is there any pixel drawn on my hompage? I think if i get the canvas hash value then there must be a pixel drawn on my homepage? It means there is already canvas finterprinting implemented in this version of fingerprints? Am i right? 

Thx

**Comment by Valve** [comment]
Yes.
1. A hidden canvas is created.
2. Shapes are drawn on the canvas.
3. Text is written on the canvas.
4. Canvas data is converted from binary form to Base64 encoded string.
5. This string gets appended to other components.
6. All components are passed through a hash function.

Hope this helps

**Comment by abetsxsolla** [comment]
when the new version will be released?
