### ISSUE TITLE
Make synchronous version

### ISSUE THREAD

**Issue by tamtakoe** [Valve/fingerprintjs2#215]
Add, please, special method f.e. `Fingerprint2().sync` without asynchronous operations (several options have to be disabled)

**Comment by elad-yosifon** [comment]
@tamtakoe it will be available in v2 (currently in dev).
you can play with it on v2 branch, and see if it works for you.

**Comment by xeraseth** [comment]
I was needing the synchronous version. I noticed that the exclude options are passed differently. In addition it wasn't merging user options with default options. I've opened a PR to handle that issue. Let me know if you want a separate issue instead (looks like spec was already updated with new exclude expectations). #227

**Comment by valnub** [comment]
+1 on synchronous solution. What's the status on this?

**Comment by Valve** [comment]
Currently no one is working on anything. Elad Yosifon wanted to be a maintainer, but he stopped working on this project. Looking for maintainers currently

**Comment by valnub** [comment]
Here, I created a synchronous version for anyone who needs it:

- https://github.com/valnub/fingerprintjs2sync
- https://www.npmjs.com/package/fingerprintjs2sync

**Comment by jonashaag** [comment]
Closing in favour of #269

**Comment by OriAmir** [comment]
anything new about that? it's really necessary! I don't understand why this library is async at all.. tnx
@valnub

**Comment by jonashaag** [comment]
Necessary for what? What's your use case that doesn't allow you to use async?
