### ISSUE TITLE
What is the output hash method in fingerprintjs2 ?

### ISSUE THREAD

**Issue by alipour66m** [Valve/fingerprintjs2#217]
Hi
I want to know What is the hash method in fingerprintjs2 output  ?
And is there any way to verify fingerprintjs2 hash output?
I think it is a good idea that fingerprintjs2 hash output code can be verifiable.

**Comment by Valve** [comment]
Hi @alipour66m it's using Murmurhash V2 (128bit). You can see the details here: https://en.wikipedia.org/wiki/MurmurHash
