### ISSUE TITLE
jsFontsKey has some problem when browser zoom in or zoom out

### ISSUE THREAD

**Issue by Monyer** [Valve/fingerprintjs2#22]
my test result:
time1:zoom to 100%
Serif"[100 … 141]
136: "Vijaya"137: "Vrinda"138: "Webdings"139: "Wingdings"140: "Wingdings 2"141: "Wingdings 3"

time2:zoom to 110%
Serif"[100 … 140]
136: "Vrinda"137: "Webdings"138: "Wingdings"139: "Wingdings 2"140: "Wingdings 3"

**Comment by Monyer** [comment]
http://www.browserleaks.com/fonts  do not has the same problem.

**Comment by Valve** [comment]
Thanks @Monyer will look into it

**Comment by Valve** [comment]
Fixed, had to remove 2 fonts with inconsistent detection.
