### ISSUE TITLE
Same fingerprint hash from two different fingerprint components

### ISSUE THREAD

**Issue by Lapkritinis** [Valve/fingerprintjs2#220]
I gathered around 340000 different browser fingerprints and decided to check if fingerprint hash is unique for fingerprint_components. All there unique, but one fingerprint with hash 872baf8c9dffb2de298334f87c92b08f contained two different fingerprint components. Only "canvas" is different. I am attaching both json files (well github throws error... "Something went really wrong, and we can't process that file".

adding link to dropbox 
https://www.dropbox.com/s/58c7vp9hqr5rmwe/json1.txt?dl=0
https://www.dropbox.com/s/99bxlm4mdvljzgr/json2.txt?dl=0

**Comment by Valve** [comment]
two birds in one thread, nice!

2 collisions per 340K inputs is absolutely normal see here: http://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed
