### ISSUE TITLE
Timezone offset values must be multiplied by -1

### ISSUE THREAD

**Issue by escopecz** [Valve/fingerprintjs2#223]
Timezone offset value seems to be the other way around than other systems work with it. At least based on timezone numbers at https://www.timeanddate.com/time/map/. 

I'm located in Prague and my system is set to Prague timezone as well, but I'm getting timezone_offset = -60. That is -1 instead of 1. If I run the offset through PHP's [timezone_name_from_abbr](http://php.net/manual/en/function.timezone-name-from-abbr.php). 

If I set my system timezone to New York, Fingerprint will send me timezone offset of 5 (in minutes) which is somewhere in Asia. If I multiply it -1, I get offset of 5, which is New York. 

It seems to send the opposite values than it should.

**Comment by elad-yosifon** [comment]
@escopecz if it is consistently returning the negated timezone.. it works as expected.
The whole point of this library is to generate a consistent hash value given a specific user device.
The case you are describing will always return the same value (just negated), which will lead to the same hash given all other parameters are identical.

**Comment by Valve** [comment]
yeah, the purpose is not to detect your timezone, but to provide an entropy source based on your timezone. If it's consistent for you, it shouldn't be considered a bug. Closing for now, please fell free to reopen if you disagree/want this to be discussed.
