### ISSUE TITLE
Fingerprint2 is not defined on My MacBook Pro

### ISSUE THREAD

**Issue by RocPeng** [Valve/fingerprintjs2#224]
Thanks for offer this lib,it is amazing，but when i deploy a nodejs project i found a problem，the code is:
var fingerprint = '';
new Fingerprint2().get(function(result, components){
    fingerprint = result;
});
it works well in the chrome browser of my lenovo computer,but it cannot work in the chrome of my macbook pro,error:
Uncaught ReferenceError: Fingerprint2 is not defined
    at home.js:2
an someone help me？

**Comment by Valve** [comment]
Hi, thanks for using the library!

This lib was never designed to work in nodejs, so I'm closing this for now. Feel free to reopen with more details :)
