### ISSUE TITLE
Default settings generating 2 different fingerprints that alternate on refresh

### ISSUE THREAD

**Issue by pulsedemon** [Valve/fingerprintjs2#228]
I decided to console log the component list for each fingerprint:

`console.log(JSON.stringify(components, null, 2));`

Saved the output of each fingerprint in fingerprint1.txt and fingerprint2.txt

Diffed them:

`diff -u fingerprint1.txt fingerprint2.txt > difference.txt`

This is the output:

```
1 --- fingerprint1.txt»·2017-01-30 13:28:41.000000000 -0500
2 +++ fingerprint2.txt»·2017-01-30 13:28:43.000000000 -0500
3 @@ -73,7 +73,7 @@
4    },
5    {
6      "key": "canvas",
```

The canvas fingerprint is different.

I'm on OS X El Capitan, Chrome Version 55.0.2883.95 (64-bit), and this is how we call the fingerprint lib:

```
var fingerprintjs2 = require('fingerprintjs2');
var that = this;

new fingerprintjs2().get(function(result){
    that.fingerprint = result;
});
```

I was able to fix the issue by excluding canvas in the options.

I've attached the files.

[difference.txt](https://github.com/Valve/fingerprintjs2/files/739896/difference.txt)
[fingerprint1.txt](https://github.com/Valve/fingerprintjs2/files/739897/fingerprint1.txt)
[fingerprint2.txt](https://github.com/Valve/fingerprintjs2/files/739898/fingerprint2.txt)

**Comment by Valve** [comment]
Canvas component is different for you. Please help me isolate which part of canvas component generates different values on refresh. One idea is that you have an external GPU which gets activated on second refresh?

**Comment by pulsedemon** [comment]
@Valve hmm that sounds possible, but I honestly don't know too much about how that works.  I have a dedicated graphics card in my macbook pro and automated graphics switching is enabled.  If it helps at all, this page returns the same canvas fingerprint every time: https://browserleaks.com/canvas

**Comment by Valve** [comment]
>  I have a dedicated graphics card in my macbook pro and automated graphics switching is enabled

I think this is the issue.

The link you gave - they're probably not doing the WebGL fingerprinting and it's more stable in their case.
I don't have a laptop with external GPU, so I won't be able to identify exact place in the script where data changing w/out your help. Please help me to spot the line which returns different values with and without  the GPU enabled. If you find it, submit an issue for your case, where externally activated GPU changes the resulting fingerprint.

**Comment by pulsedemon** [comment]
@Valve Glad to help.  If I can, I'll also submit a pr

**Comment by Valve** [comment]
thanks!

**Comment by pulsedemon** [comment]
@Valve I was on v1.4.1 before.  Just upgraded to 1.5.0 and it seems like my issue is resolved.

**Comment by Valve** [comment]
ok, great, thanks

**Comment by pulsedemon** [comment]
@Valve I'm sorry, I spoke too soon.  I refreshed the page over 20 times and it produced the same fingerprint, but now it's gone back to multiple fingerprints.  I'll continue to look into this.

**Comment by Valve** [comment]
no problem, thanks!
