### ISSUE TITLE
flashFontsKey can't get anything when Chrome in incognito mode

### ISSUE THREAD

**Issue by Monyer** [Valve/fingerprintjs2#23]
the chrome version is : 41.0.2272.101 m
http://browserleaks.com/fonts  has the same problem.

but maybe it is a way to detect whether user in incognito mode or not.

maybe we can do it like that:
NoFlashFontskey = "f8e9592befd6dcb2337f6ac5d0beca77"
FlashFontskey = "2a4d643f"   or  "00000000"
Key = NoFlashFontskey+FlashFontskey

if we had key1 and key2:

if (key1===key2){
    then    user1 is user2       (strongly)
}else{
    if (key1.substr(32,8)==="00000000" || key2.substr(32,8)==="00000000"){
          if(key1.substr(0,32)===key2.substr(0,32)){
               then   user1 is user2          (not strongly)   and user maybe  in incognito mode
          }else{
               then   user1 is not user2          (strongly)
          } 
    }else{
        if (key1.substr(32,8)!=="00000000" && key2.substr(32,8)!=="00000000")
          && key1 !== key2
           then   user1 is not user2    (strongly)
    }
}

**Comment by Monyer** [comment]
maybe we can do it like that:
NoFlashFontskey = "f8e9592befd6dcb2337f6ac5d0beca77"
FlashFontskey = "2a4d643f"   or  "00000000"
Key = NoFlashFontskey+FlashFontskey

if (key1===key2)
    then    user1 is user2         strongly

if (key1.substr(32,8)==="00000000" || key2.substr(32,8)==="00000000")
   && key1.substr(0,32)===key2.substr(0,32)
    then   user1 is user2          not strongly   and user maybe  in incognito mode

if (key1.substr(32,8)!=="00000000" && key2.substr(32,8)!=="00000000")
  && key1 !== key2
   then   user1 is not user2    strongly

**Comment by mhuisman** [comment]
reproducible in firefox.  currently the fonts code assumes that if flash is enabled, flash font detection will be successful.  downside is ~100ms performance hit with null output.  might be worth making js font detection the primary detection mode and only do flash detection if user specifies the option.

**Comment by Valve** [comment]
@Monyer @mhuisman confirming the issue in incognito mode. Will look into it.

**Comment by mhuisman** [comment]
@Valve +1 to js font detection as default, I can take a crack at it this week

**Comment by Valve** [comment]
Thanks, fixed in #35 closing
