### ISSUE TITLE
ReferenceError: Fingerprint2 is not defined

### ISSUE THREAD

**Issue by convert5** [Valve/fingerprintjs2#233]
Hi,

I am using v1.5 and I am still getting this error message:
ReferenceError: Fingerprint2 is not defined

I am loading it directly from my server (so no CDN).  It is part of a larger magento (version 2.1.5) installation.  Works fine under magento 1.9.

Any ideas?

Thank you!

**Comment by Valve** [comment]
Please ask questions on gitter.im channel, I'm not using Magento and thus cannot reproduce this issue. The library is working fine for me

**Comment by thiagoloddi** [comment]
@convert5 Did you solve it?

**Comment by GrosSacASac** [comment]
@ms-chanma how are you including Fingerprint2 in your project ? Can you share a minimal reproducible example ?

**Comment by ms-chanma** [comment]
angular.module('groupme').service('deviceIdService', [
    'storageService', 'api', 'Translations',
    function(storageService, api, Translations) {
        var device_id;

        function init(){
            device_id = storageService.get('device_id');
            if(device_id == null || device_id == "") {
                config = {
                    excludeScreenResolution: true, //Screen resolution  will change when you move between different screens on the same decive
                    excludeAvailableScreenResolution: true, //same as above
                    excludeCanvas: true, //firefox will generate different Canvas value on different screen of the same device
                    excludePlugins: true,  //browser plugin will change often
                    excludeLanguage: true //this is browser language, should not affect the hash
                }
                new Fingerprint2(config).get(function(result, components) {
                    device_id = result;
                    storageService.set('device_id', device_id);
                })

            }
        }

**Comment by ms-chanma** [comment]
I use bower install fingerprint then npm install.
In application.js.erb, it require fingerprint js file : //= require fingerprintjs2/dist/fingerprint2.min.js.
I create a angularjs service to call fingerprint2:
angular.module('groupme').service('deviceIdService', [
    'storageService', 'api', 'Translations',
    function(storageService, api, Translations) {
        var device_id;

        function init(){
            device_id = storageService.get('device_id');

**Comment by GrosSacASac** [comment]
`bower install fingerprint` will install the old project ...

uninstall it then 

try `npm install fingerprintjs2`
and do
`const Fingerprint2 = require("fingerprintjs2")` in the same file where it is used, at the top

**Comment by gogul91** [comment]
> `bower install fingerprint` will install the old project ...
> 
> uninstall it then
> 
> try `npm install fingerprintjs2`
> and do
> `const Fingerprint2 = require("fingerprintjs2")` in the same file where it is used, at the top

It's works!

**Comment by ExtractTable** [comment]
please check if your browser is allowing all scripts !! Privacy browsers like Brave are not allowing Fingerprint js

**Comment by sergiu-petrica** [comment]
@ExtractTable thank you, this turned out to be the case for me.

An FYI for people reading this who are using Opera like myself: it seems like Opera blocks this library by default. The solution is to deactivate Settings -> Basic -> Block Trackers. It's on by default.
That's interesting because I don't consider Opera a privacy-oriented browser at all.

**Comment by sergiu-petrica** [comment]
@ExtractTable  thank you, this turned out to be the case for me.

For people reading this: Opera browser seems to block this library, even though it's not exactly known as the most privacy-oriented browser. 
The solution is to disable `Settings -> Basic -> Block Trackers` as it's on by default.
