### ISSUE TITLE
Doesn't work on Android 7.1.1 / Google Pixel / Chrome 56.0.2924.87

### ISSUE THREAD

**Issue by brianfeister** [Valve/fingerprintjs2#234]
I'm on Android 7.1.1 / Google Pixel / Chrome 56.0.2924.87, no unusual settings, in regular (NOT Incognito mode) and this library does not generate a consistent hash for the fingerprint.

**Comment by Valve** [comment]
I'm sorry, I don't have bandwidth to investigate this. A PR would be very welcome. Thanks!

**Comment by DeMies75** [comment]
Same problem working in Windows 7 on Chrome 56.0.2924.87 (64-bit).
For 1 tab the fingerprint stays the same, multiple tabs in the same browser => all different fingerprints.

**Comment by Valve** [comment]
Please help me identify which component gets changed for you on different tabs. Once we know this we can fix this

**Comment by DeMies75** [comment]
Can't, Chrome updated to 57.0.2987.133 (64-bit), can't reproduce it anymore :(.

**Comment by Valve** [comment]
ok, I'm closing then. Please feel free to reopen with more details if you see this issue again

**Comment by o0aditya0o** [comment]
I am also experiencing the same issue on chrome version  58.0.3029.96 (64-bit) Mac OS . The only difference is the time to calculate the fingerprint when the time is in the range of 300-400 ms it gives hash and when in the range of 1000-1100 ms gives another hash . @Valve @DeMies75
