### ISSUE TITLE
your code is  giving diffrent fingerprint id to the diffrent browsers in the same system help me out of this .

### ISSUE THREAD

**Issue by sakibkhan** [Valve/fingerprintjs2#235]
# Before submitting an issue please read:

### https://github.com/Valve/fingerprintjs2/blob/master/CONTRIBUTING.md

If your issue is about fingerprint changing fast/being inconsistent, please search for already closed issues about it, you may find your answer there.

This can be probably because of your browser upgrade (User agent string changing), different screen resolution on various devices (fixable by disabling screen_resolution option).

If you want to submit a bug, please let me know which browser/os you're using and which fingerprinting component is broken and/or different for you on multiple library calls.

If you want to ask a question - please use gitter.im (badge is in the readme) and ping me with @valve handle, I'll gladly answer specific questions about the library.

**Comment by sakibkhan** [comment]
i want same fingerprint id to the diffrent browsers in the same ststem.

**Comment by lucarez** [comment]
Hi @sakibkhan,
I think that what you are asking for is out of the scope of this project, this fingerprinting method is browser based, at least for what I could understand, but if I'm wrong maybe @Valve can correct me.
I'd like to use this post to bring out a reading that I had last week ([http://thehackernews.com/2017/02/cross-browser-tracking.html](http://thehackernews.com/2017/02/cross-browser-tracking.html)) that could help @sakibkhan with his requirements but, maybe, can also improve this library entropy with the checks that the cross-browser fingerprint of the article uses.
I took a quick look at the [repo](https://github.com/Song-Li/cross_browser) linked in it and saw some server side content that goes beyond FP2 purpose, but if you want to check it as a free-time reading...

**Comment by Valve** [comment]
@lucarez you're right, thanks for the explanation :+1:

**Comment by sakibkhan** [comment]
even the cross browser master giving diffrent id's to  diffrent
browsers.cant you enhance fingerprint.js
or else suggest any other thing.

thank you
