### ISSUE TITLE
Adding audio stack fingerprinting feature

### ISSUE THREAD

**Issue by viyatb** [Valve/fingerprintjs2#237]
I found this [research page from Princeton](https://audiofingerprint.openwpm.com/)  which generates the fingerprint based on the audio stack of the target.

I ran some tests and it looks promising. Should I open a PR regarding this?

**Comment by Valve** [comment]
https://github.com/Valve/fingerprintjs2/pull/156
It's already been suggested and implemented. Not stable enough to include into fingerprinting process, unfortunately.
