### ISSUE TITLE
[feature request] adding custom attributes to fingerprint calculation

### ISSUE THREAD

**Issue by jacek213** [Valve/fingerprintjs2#238]
I need to add some attributes which are not core part of `fingerprintjs2` to the fingerprint calculation (for example navigator.cookieEnabled).

If this kind of change would be welcome, please let me know and I might submit a PR for that :)

**Comment by jdufour** [comment]
I was also thinking of adding some things ..MediaDevices.enumerateDevices() and the related data.

// If this kind of change would be welcome, please let me know and I might submit a PR for that :)
Ditto

**Comment by Valve** [comment]
sorry guys, I will only be accepting PRs that stabilize existing FP process. Currently the FP is not very stable so adding new FP sources will make it even less stable.
