### ISSUE TITLE
Remove the global polyfill for the Array.prototype.indexOf()

### ISSUE THREAD

**Issue by arapoport** [Valve/fingerprintjs2#239]
I noticed that the library (version 1.5.0) sets a polyfill for the `Array.prototype.indexOf()` function.

However it looks like **Array**.prototype.indexOf() is not used in the library at all.  It uses **String**.prototype.indexOf() a lot but not the one from Array.

Besides, overriding or polyfilling any global object implicitly done by a library can have nasty side effects. For example, someone may rely on absence of Array.prototype.indexOf() to detect IE8. 

For a library it would be more appropriate to keep an own implementation of a standard function in a private function and use it only when needed. Or at least write a notice about the polyfill,

**Comment by Valve** [comment]
You're right, @arapoport, thanks for the observation. A PR would be welcome :bowing_man:

**Comment by arapoport** [comment]
Sure, I'll submit it soon :-)

**Comment by Valve** [comment]
released v.1.5.1 with your fix, thank you
