### ISSUE TITLE
window.screen.availWidth and window.screen.availHeight maybe useful?

### ISSUE THREAD

**Issue by Monyer** [Valve/fingerprintjs2#24]
window.screen.availWidth and window.screen.availHeight maybe useful
when
windows taskbar in defferent place or taskbar's height changes

**Comment by Valve** [comment]
Thanks, @Monyer.
I'm on vacation now, travelling. Will resolve and answer all your issues after May 11th

**Comment by Valve** [comment]
Closed by https://github.com/Valve/fingerprintjs2/pull/37
