### ISSUE TITLE
how to disable console logs in non-minified version

### ISSUE THREAD

**Issue by jacek213** [Valve/fingerprintjs2#242]
Hello,

I'm using a non-minified version (using bower). I want to disable console logging, however I don't see any other option to do that than setting `window.NODEBUG = true`, which I of course don't want to do :)

**Comment by Valve** [comment]
Well, non-minified version was never actually meant for production usage. You can just remove all the places there logging occurs manually.

**Comment by jacek213** [comment]
Well, I can't really do that because I don't keep thrid party source code in repo - it stays in /bower_components and all the vendor files are compiled into a single file and minified on our side when building a package. The process is automated and only files listed as `main` in their `.bower.json` file are being taken from /bower_components.

**Comment by Valve** [comment]
ok, please remove all the logging and do a PR and I'll release a new version w/out logging. I don't think anybody is using it

**Comment by jacek213** [comment]
Or we can make it configurable - let me know. Anyway, will do. Thanks.

**Comment by jacek213** [comment]
Done in https://github.com/Valve/fingerprintjs2/pull/244. All tests are green. However, if you'd rather keep console logs and make them configurable, let me know and I'll submit another PR.

**Comment by Valve** [comment]
released v.1.5.1
