### ISSUE TITLE
Opera detected as Chrome is Mac

### ISSUE THREAD

**Issue by lucasdantur** [Valve/fingerprintjs2#246]
Hi,

I'm getting recognized as Chrome when using Opera in Mac.

Opera version: 44.0.2510.1449
MacOS version: 10.12.4 (16E195)

User agent detected by fingerprintjs2: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2

Real user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36 OPR/44.0.2510.1449

Let me know if you need any additional information, or if there's a workaround this.

**Comment by Valve** [comment]
Hi, 
This library doesn't do user agent detection. It just uses whatever the browser reports with navigator.userAgent

**Comment by lucasdantur** [comment]
Ok. Thank you
