### ISSUE TITLE
has_lied_os is wrong in case of Linux + Chrome on laptop w/ touchscreen

### ISSUE THREAD

**Issue by korc** [Valve/fingerprintjs2#247]
It seems that logic detecting mobile device and comparing it to the OS value is not good enough to say if information is false or not.
ref:
https://github.com/Valve/fingerprintjs2/blob/1e48f854a9177288e2de2d4935b85a64e2cca1dc/fingerprint2.js#L894-L906
Errornous logic in case of legitimate browser:
* Chrome on Linux with touchscreen support *has* `ontouchstart` and `navigator.maxTouchPoints`, and therefore `mobileDevice` *will be* `true`
* `os` value *will be* `Linux`
* it is wrong to return `true` from `getHasLiedOs` at this point

A possible solution would be adding comparison if `userAgent` contains `Chrome`.

**Comment by Valve** [comment]
Thanks for the find, I'll look into it @korc

**Comment by marctrent101** [comment]
Not just chrome on linux. I have chrome on windows 10 64 bit on laptop with touch capabilities. The result is has_lied_os=true. Many desktop/laptop screens now support touch...

![image](https://user-images.githubusercontent.com/33937964/41240510-a6dcdbcc-6d68-11e8-894e-ee2965cae0ff.png)

**Comment by Valve** [comment]
@korc a set of improvements has been merged in master regarding os/platform detection/spoofing.
I'm closing this issue, because we no longer detect mobile devices by looking at touch screen capabilities.
