### ISSUE TITLE
Why does the fingerprint does not comes same for normal and incognito browsing modes of chrome despite of the fact that all the information displayed on the site is same for both of them.

### ISSUE THREAD

**Issue by o0aditya0o** [Valve/fingerprintjs2#248]

**Comment by lambrojos** [comment]
:+1:

**Comment by jor3l** [comment]
Same here, therefore this is useless

**Comment by mborecki** [comment]
I get the same fingerprint in normal and in incognito mode. Maybe you have same plugins unavaible in incognito? Can you check components list?

**Comment by jor3l** [comment]
@mborecki It happens to be a problem with the website I was testing it on. Some of the libraries used enable flash so the plugins do change when tested on Incognito

**Comment by 2tunnels** [comment]
Firefox in Incognito mode enabling "Do not track" option and fingerprint are different.

**Comment by jonashaag** [comment]
According to this site https://stackoverflow.com/questions/32890865/does-private-mode-enable-do-not-track-dnt-on-popular-browsers most browsers enable DNT in incognito mode. I can confirm it is automatically enabled in latest Firefox and Safari, but not in latest Chrome.

I guess it makes no sense to consider DNT for these browsers in the first place. If we're in incognito mode, there's no way of knowing if the user has DNT enabled in non-incognito mode too, which means we cannot know if the DNT component tampers with the fingerprint.

What do you think?

**Comment by lpd-au** [comment]
It'd be great if there was an option/default to compare plugins but ignore flash, for the stated reason of it sometimes disappearing in incognito mode.

**Comment by jonashaag** [comment]
Good idea, PR welcome

**Comment by jonashaag** [comment]
Closing, see follow-up issues ^
