### ISSUE TITLE
Hardware based Key and Server Side JS

### ISSUE THREAD

**Issue by abmmhasan** [Valve/fingerprintjs2#25]
Well, there is another great option could be added. Well, as you read in title "Hardware based Key". Like detecting Security keys which is also available in Google Security Solution.

Though there is security risks. As JS file runs on client side so anyone can bypass it with simple browser based developer extensions.

There is a <a href="http://www.webreference.com/programming/javascript/rg37/index.html">good reading here</a>.

**Comment by Valve** [comment]
Closing because this library is a pure browser identification library.
