### ISSUE TITLE
Canvas fingerprinting is useless...

### ISSUE THREAD

**Issue by sumazaze** [Valve/fingerprintjs2#250]
Hi

What is the purpose of canvas fingerprinting?

I tried it on 3 browsers (desktop)
2 browsers (android)
3 browsers different OS (browserstack.com)

You know what?? all share the same fingerprint

"iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAgA"

try it yourself.

**Comment by antoinevastel** [comment]
Hi,
What you copied is just the beginning of the string representing the canvas, but the end of the string is probably different. Normally, (at least) the emoji included in the canvas is rendered differently depending on the OS as you can read in this article: https://hal.inria.fr/hal-01285470v2/document
