### ISSUE TITLE
Can you explain the meaning of line 917, 925 929?

### ISSUE THREAD

**Issue by wu-yuanyi** [Valve/fingerprintjs2#252]
`if(oscpu.indexOf("win") === 0 && oscpu.indexOf("linux") === 0 && oscpu.indexOf("mac") >= 0 && os !== "other")`
`if(platform.indexOf("win") === 0 && platform.indexOf("linux") === 0 && platform.indexOf("mac") >= 0 && os !== "other")`
the value of `oscpu.indexOf("win") === 0 && oscpu.indexOf("linux") === 0` is always false.

and what is pike?
`platform.indexOf("pike")`

**Comment by antoinevastel** [comment]
Yes you're right, oscpu.indexOf("win") === 0 && oscpu.indexOf("linux") === 0 will always be false.
Pike corresponds to Opera mini on iPhone according to this thread on StackOverflow: https://stackoverflow.com/questions/19877924/what-is-the-list-of-possible-values-for-navigator-platform-as-of-today

**Comment by wu-yuanyi** [comment]
If you want to deal with "winlinuxmac", the code is error too.
It may be
`if(oscpu.indexOf("win") >= 0 && oscpu.indexOf("linux") >= 0 && oscpu.indexOf("mac") >= 0 `

**Comment by wu-yuanyi** [comment]
If you want to deal with "winlinuxmac", the code is error too.
It may be
`if(oscpu.indexOf("win") >= 0 && oscpu.indexOf("linux") >= 0 && oscpu.indexOf("mac") >= 0 `

**Comment by antoinevastel** [comment]
Yes you're right indeed.
