### ISSUE TITLE
Chrome 58 complains "[Violation] 'setTimeout' handler took Nms"

### ISSUE THREAD

**Issue by peterugh** [Valve/fingerprintjs2#253]
```
[Violation] 'setTimeout' handler took 63ms
```

Chrome 58 console now gives performance warnings by default. A violation is being reported for a setTimeout in the library. My exact message varies in terms of time the handler took but is between 50ms and  80ms each time. The message does not always appear. 

I'm using `import` to include the library into a React application using a Babel transpiler

Perhaps [requestIdleCallback](https://developers.google.com/web/updates/2015/08/using-requestidlecallback) could be implemented. If time allows I'll try and create a PR but it's not likely that will be soon.

Mac OS 10.11.6
Chrome Version 58.0.3029.110

**Comment by javac9** [comment]
Same here, I'd like to know what the best approach to avoiding these would be (I guess performance improvement but...).

**Comment by GrosSacASac** [comment]
By the nature of this library, this should be a "won't fix"

**Comment by Valve** [comment]
Since a global `setTimeout` has been removed and it's possible to just wrap the calling into `requestIdleCallback` on Chrome, I'm closing this issue. 
Please feel free to reopen with additional comments.
