### ISSUE TITLE
Fingerprint changes on refresh

### ISSUE THREAD

**Issue by jdsenecal** [Valve/fingerprintjs2#254]
Hello!
I'm experiencing a strange issue. On initial page load, i get a particular Fingerprint (Print A), but when I refresh the page, I get a different one (Print B).
The two fingerprints are different, but they're consistent. On initial load, Print A always shows, but Print B shows whenever I refresh the page.

Any ideas?
Currently testing on Windows 10.
Chrome Version 58.0.3029.110 (64-bit) appears to be where the issue is occurring.
IE 11 so far appears to be working as expected.

**Comment by Valve** [comment]
It was answered before, probably you have a CPU GPU and External GPU and
external GPU kicks in on second refresh

**Comment by jdsenecal** [comment]
Unfortunately, no. No external GPU. :(
Could it be related to plugins getting loaded on initial page load (adblock being one in particular)?

**Comment by Valve** [comment]
yes, probably; the best way is identify the changing component. Something
is different in these 2 cases and adds to a changing fingerprint

**Comment by amuagarwal** [comment]
Even i am facing the same issue and this problem started after updating Chrome to version 58.0.3029.110 (64-bit). Any help will be very useful to get the unique id on each refresh.

**Comment by jdsenecal** [comment]
So, from my perspective, this appears to be due to browser plugins. What I ended up doing was I delayed the generation of the fingerprint until after the page completely loads. This appears to have resolved the issue from what I can see.

**Comment by tkalfigo** [comment]
I had same issue. 

Though I cannot be 100% sure, I believe adding in the constructor the option `excludeAdBlock: true` seems to have solved it. 

I am now getting the same fp over multiple reloads.
