### ISSUE TITLE
fingerprint2.js getting blocked by AdBlockers

### ISSUE THREAD

**Issue by amuagarwal** [Valve/fingerprintjs2#258]
just a quick update fingerfrint2.js getting blocked by AdBlockrs 

Static filter /fingerprint2.js found in:
EasyPrivacy

**Comment by RobertJGabriel** [comment]
Or change the file to fp.js will also pass it

**Comment by amuagarwal** [comment]
Currently doing this only. Even thinking to put few line of code that push new filename every week or month so in feature even if anyother file name get blocked, I not need to worry about renaming manually.

**Comment by george-kar** [comment]
Or you can place the fingerprint code inside your existing js files and mix everything together

**Comment by Valve** [comment]
I think this is not an issue, easy to avoid blocking.

**Comment by ar-anvd** [comment]
@amuagarwal What blockers are you talking about? 

fingerprint2.min.js from cdnjs is not blocked by Adblock Plus, at least in my tests.

**Comment by amuagarwal** [comment]
the ad blocker with wich i tried are uBlock Origin and its all variant. By changing filename it works.

**Comment by UltraFlux** [comment]
https://cdnjs.cloudflare.com/ajax/libs/fingerprintjs2/1.5.1/fingerprint2.min.js
Confirmed blocked by Adblock

**Comment by UltraFlux** [comment]
renaming to random filename makes no difference, ex: KjUS3hZzvo6C.min.js

**Comment by franck34** [comment]
May you try to obfuscate ?

* https://github.com/javascript-obfuscator/javascript-obfuscator
* https://javascriptobfuscator.herokuapp.com/

**Comment by alimo2** [comment]
e.g. Brave browser drop fingerprinting methods like webgl and canvas!!!
