### ISSUE TITLE
There is a bug in getScreenResolution

### ISSUE THREAD

**Issue by ilife5** [Valve/fingerprintjs2#259]
Hi

I`m reading the source code for study. At [fingerprint2.js#L147](https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L147), there is a bug.

```
getScreenResolution: function(keys) {
      var resolution;
      if(this.options.detectScreenOrientation) {
        resolution = (screen.height > screen.width) ? [screen.height, screen.width] : [screen.width, screen.height];
      } else {
        resolution = [screen.width, screen.height];
      }
      if(typeof resolution !== "undefined") { // headless browsers
        keys.push({key: "resolution", value: resolution});
      }
      return keys;
    }
```

Resolution can`t be "undefined".

**Comment by jonashaag** [comment]
@Valve this is correct, the case can be deleted. This code smell was actually already there in the commit in which that code was introduced: https://github.com/Valve/fingerprintjs2/commit/b8305c4ce2e901e86d167b731ea751f70264cefd

**Comment by Valve** [comment]
@jonashaag please handle it as you see fit, up to you.

**Comment by mdxs** [comment]
Looks like the above commit from @abritinthebay could address this #259 but it is not (yet) a PR, or is it?

**Comment by jonashaag** [comment]
true

**Comment by abritinthebay** [comment]
Pulled master, created PR, thanks for the reminder ;)
