### ISSUE TITLE
Timezone offset changes twice a year, resulting in unstable fingerprint

### ISSUE THREAD

**Issue by Download** [Valve/fingerprintjs2#266]
Currently the tests include a call to `getTimezoneOffset` on a new Date object:

```js
keys.addPreprocessedComponent({key: "timezone_offset", value: new Date().getTimezoneOffset()});
```
https://github.com/Valve/fingerprintjs2/blob/1.5.1/fingerprint2.js#L174

The problem with this is that in countries with daylight savings, the result of getTimezoneOffset will change twice a year. Instead, set the date to some hardcoded value, then get the timezone offset of that fixed date:

```js
function getFixedTimezoneOffset() {
  var d = new Date()
  d.setUTCFullYear(1970)
  d.setUTCMonth(1)
  d.setUTCDate(1)
  d.setUTCHours(0)
  d.setUTCMinutes(0)
  d.setUTCSeconds(0)
  d.setUTCMilliseconds(0)
  return d.getTimezoneOffset()
}

keys.addPreprocessedComponent({key: "timezone_offset", value: getFixedTimezoneOffset()});

**Comment by jonashaag** [comment]
Agreed, or we could simply get the timezone name instead. Not sure what's better here. PR welcomed.

**Comment by Download** [comment]
Frankly, this is such a small change that the overhead of me doing the work for a PR seems to be unreasonably high compared to someone already working on it just fixing this issue as well. Sorry.
