### ISSUE TITLE
The fingerprint string will be changed when i edit the user-agent

### ISSUE THREAD

**Issue by babywhale** [Valve/fingerprintjs2#270]
I create the fingerprint string without any options, but it will be changed when I edit the user-agent by chrome console. Is that right ?

**Comment by jonashaag** [comment]
Yes, user agent is included in the fingerprint by default.

**Comment by babywhale** [comment]
I add the option excludeUserAgent:true, but the fingerprint can also be changed, it that right?

**Comment by jonashaag** [comment]
There are many circumstances that may cause the fingerprint to change. Does it change in the same browser if you don't change any settings? If so, what browser version an OS are you using?

**Comment by jonashaag** [comment]
There are many circumstances that may cause the fingerprint to change. Does it change for you when using the same browser without changing any settings? If so, which browser version and OS are you using?
