### ISSUE TITLE
Poor async error handling

### ISSUE THREAD

**Issue by petr-ujezdsky** [Valve/fingerprintjs2#287]
I am trying to integrate fingerprint2 in "safe" way to avoid any JS problems on client side.
The idea is to try compute FP using default (empty) options and in case of an error, modify options (eg. set `excludeWebGL` to `true`) and try to compute again.
I also have to migrate it into `Promise` to be compatible with the rest of my project.

Unfortunately the simplest solution
```
var fingerprint = new Promise(function(resolve, reject) {
  try {
    new Fingerprint2(options).get(resolve);
  } catch (e) {
    reject(e);
  }
});

fingerprint.then(alert, alert);
```
won't always work due to your `setTimeout` usage (https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L323). If the error occurs inside the `setTimeout` callback function, the JS just errors into console and the `done` callback is never called.

# Steps to reproduce:

1. Add code `pair = null` just before https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L97 (to simulate NPE)
```
pair = null
var value = pair.value
```
2. Watch the library do nothing with your callback and also not propagating the error up. Only printing error to console.
```
try {
  new Fingerprint2({}).get(alert);
} catch (e) {
  alert(e);
}
```

I have found this issue thanks to FF 52.5.3 (ESR). It blocks fingerprint in it's default configuration and gives these 2 errors:

- Error: WebGL: Disallowing antialiased backbuffers due to blacklisting.
- TypeError: pair is null - fingerprint2.js:97

# Solution
Simply add the `failed` callback along with the `done` callback. Enclose the inside of `get` function into `try-catch` block and call the `failed` callback in case of an error.
Also propagate the `failed` callback into the `fontsKey` and `jsFontsKey` functions. In the `jsFontsKey` function use `try-catch` in the same fashion as in the `get` function.

I will provide a pull request with this solution soon as this issue is blocker for my project.

**Comment by jonashaag** [comment]
The library actually should never throw any errors, so this shouldn't be necessary.

**Comment by petr-ujezdsky** [comment]
Well, due to the fingerprint-blocking mechanisms out there (extensions or natively in FF) the errors actually occur.

Here is an example with failing both master and v1.5.1:

1. Download chrome extension `Canvas defender` https://chrome.google.com/webstore/detail/canvas-defender/obdbgnebcljmgkoljcdddaopadkifnpm
2. Navigate to my jsfiddle examples:
  a) v 1.5.1 https://jsfiddle.net/pujezdsky/jtrqx9g0/1/
  b) master-HEAD https://jsfiddle.net/pujezdsky/4z6qozvk/2/

**Comment by jonashaag** [comment]
I'll open a new ticket for that issue. Are you OK with closing this ticket as "won't fix", or are you suggesting that fixing all crashes in fingerprint2 doesn't suffice and we additionally need to provide better support for handling errors?

**Comment by petr-ujezdsky** [comment]
I would definitely suggest proper error handling. Those 2 extensions will be fixed but then will come another one or even default browser setting (see Firefox) and we are back with some errors. The bad thing is that the JS can simply fail in the way I have described in the first post, leaving integrators (like me) without the chance to handle those errors.

**Comment by jonashaag** [comment]
> leaving integrators (like me) without the chance to handle those errors.

Well you should have JavaScript error reporting and then file tickets here for all exceptions you are getting in production.

I don't see how you'd work around all sorts of errors without having dozens of possible configurations that might or might not work for a specific client – are you planning on progressively excluding components until it stops being broken? So if you start with 30 components, worst case you'll run fingerprinting 30 times? You know fingerprinting can be quite CPU heavy and also take up to 500ms (all components enabled)?

**Comment by petr-ujezdsky** [comment]
The easiest way would be to use `Promise`s. You can leave the code as is (without the whole body `try-catch`) and use second promise instead of the `setTimeout` (the currently unhandleable part).
If the code fails, the promise is automatically rejected and could be properly handled by integrator.

Well, due to no error handling on your side you leave me no other chance :(. I am aware of the performance and thus I only try to exclude 2 mostly blocked components - canvas and webGL. Then I simply fallback to string `blocked` instead of actual FP. I think this is better behaviour than to error out to client and then wait for you to fix the issue.
Note that this happens only if some bad error occurs, like with the extensions I have mentioned.

Btw I compute the FP during the login process, hence the importance.
Imagine this simple code:
```
var doLogin = function(fingerprint) {
  // send fingerprint to server, along with credentials
}

// some button click handler
try {
  new Fingerprint2({}).get(doLogin);
} catch (e) {
  doLogin('blocked');
}
```

This is the only way to ensure the async fingerprint is calculated before the `doLogin` is invoked.
Now imagine anything goes wrong in your `setTimeout`'s function callback. It could be bug on your side (some NPE, anything) or something unforseen (blocking extension). The `doLogin` callback will never be invoked then. Which is really bad.
Note that I am again aware of the performance cost and the fingerprint can be pre-calculated before the button click via the Promises.

I have created an example from master version:
https://jsfiddle.net/pujezdsky/becqw50k/2/

**Comment by jonashaag** [comment]
I agree that we should switch the interface to something Promise based. In all projects I have duplicated Promise wrapping code similar to yours. Would you be willing to contribute a new Promise based interface to the library?

Note that the old `.get()` interface should remain as-is, i.e. non-Promise based, and that the old interface should still work even if your browser doesn't support Promises.

**Comment by petr-ujezdsky** [comment]
Yeah, sure :)

And how is your project released? Is every revision in master production-ready? I would love to see this Promises API also in some stable version (aka the 1.5.1 I try to use now).
I will definitely backport it into 1.5.1 on my side because of the issues. I can create another PR with it for you if you would like :)

**Comment by jonashaag** [comment]
No, master isn't production ready all the time. I promise to cut a new release as soon as we have the Promise API :)

**Comment by petr-ujezdsky** [comment]
Cool. Unfortunately I have to have this fixed during the next week, so I will work on Promise API in the stable version 1.5.1 for myself on monday (to be sure to make it to our release). Then i will merge it into the master and create PR for you.
I will switch to the new version you release a bit later, to be sure it is stable enough.

**Comment by jonashaag** [comment]
<3

**Comment by jonashaag** [comment]
Closing in favour of #388
