### ISSUE TITLE
Crash due to canvas anti fingerprint extensions

### ISSUE THREAD

**Issue by jonashaag** [Valve/fingerprintjs2#288]
From https://github.com/Valve/fingerprintjs2/issues/287#issuecomment-355623445

Here is an example with failing both master and v1.5.1:

Download chrome extension
a) Canvas defender https://chrome.google.com/webstore/detail/canvas-defender/obdbgnebcljmgkoljcdddaopadkifnpm
b) Or CanvasFingerprintBlock https://chrome.google.com/webstore/detail/canvasfingerprintblock/ipmjngkmngdcdpmgmiebdmfbkcecdndc
Navigate to my jsfiddle examples:
a) v 1.5.1 https://jsfiddle.net/pujezdsky/jtrqx9g0/1/
b) master-HEAD https://jsfiddle.net/pujezdsky/4z6qozvk/2/
See the error in alert window. It is odd that with Canvas defender, the second time you run the script (the RUN button), the FP is computed properly.

**Comment by petr-ujezdsky** [comment]
The #287 will provide fallback in case of an unpredicted error (aka fingerprint not available). With given examples above this issue should be fixed to provide at least some fingerprint (if possible).
