### ISSUE TITLE
Cannot read property 'getImageData' of null

### ISSUE THREAD

**Issue by nachitox** [Valve/fingerprintjs2#298]
Chrome 64 on Linux

1
File "<anonymous>" line 16 col 49 in HTMLCanvasElement.value [as toDataURL]
2
File /js/fingerprintjs2/fingerprint2.min.1507920697.js line 1 col 19837 in e.getWebglFp
3
File /js/fingerprintjs2/fingerprint2.min.1507920697.js line 1 col 4831 in e.webglKey
4
File /js/fingerprintjs2/fingerprint2.min.1507920697.js line 1 col 1316 in e.get

**Comment by jonashaag** [comment]
Please try the master version

**Comment by nachitox** [comment]
Thank you.
I see the `if (canvas.toDataURL)` now :)
