### ISSUE TITLE
Code optimization

### ISSUE THREAD

**Issue by sirian** [Valve/fingerprintjs2#299]
![image](https://user-images.githubusercontent.com/897643/35776803-2f51b4aa-09b4-11e8-8174-46b9a2921cab.png)

You could easily replace this huge block of code using loops. Like this

```javascript
for (const shader of ['VERTEX', 'FRAGMENT']) {
    for (const numType of ['FLOAT', 'INT']) {
        for (const numSize of ['HIGH', 'MEDIUM', 'LOW']) {
            for (const key of ['precision', 'rangeMin', 'rangeMax']) {
                const format = gl.getShaderPrecisionFormat(gl[shader + '_SHADER'], numSize + '_' + numType);
                result.push(`webgl ${shader} shader ${numType} ${numSize} ${key}:` + format[key]);
            }
        }
    }
}

**Comment by Valve** [comment]
thanks @sirian 
@jonashaag  what do you think?

**Comment by jonashaag** [comment]
Yeah we could merge that but I think the value it provides is rather low. And I'd like to see a PR that doesn't use ES6 features since we're not using ES6 in the library so far. So +0 from me if we have a PR.

**Comment by Valve** [comment]
thanks, I agree

**Comment by sirian** [comment]
@jonashaag I'm not talking about performance. I mean this approach significantly reduces file size (for example for this block - 5kb vs 400bytes)
And also this block may be optimized 
![image](https://user-images.githubusercontent.com/897643/36248689-66ea212a-1249-11e8-9adb-f0645f908259.png)

Unfortunately I haven't enough free time to make PR(

**Comment by ProcrastinatorCp** [comment]
@Valve , @jonashaag 
Hi, I would like to give it a try.

**Comment by jonashaag** [comment]
Cool! Im happy to assist.

**Comment by namanjain1812** [comment]
@jonashaag @Valve 
hi,is this issue solved?Would like to contribute if open

**Comment by ProcrastinatorCp** [comment]
@namanjain1812 , I assumed you were not working on it, therefore I created this PR. 

@jonashaag, 
Could you please review https://github.com/Valve/fingerprintjs2/pull/317 and comment.
