### ISSUE TITLE
expand screen property detection 

### ISSUE THREAD

**Issue by mhuisman** [Valve/fingerprintjs2#30]
including: 
pixel depth
~~working area~~
aspect ratio

as per https://www.browserleaks.com/javascript

**Comment by Valve** [comment]
Thanks, will do

**Comment by mhuisman** [comment]
disregard, closing

**Comment by Valve** [comment]
@mhuisman why have you closed the issue? Please share your observations

**Comment by mhuisman** [comment]
@Valve 

* aspect ratio is redundant/unnecessary, and is covered by existing screenResolutionKey method

* pixel depth is a IE-specific implementation of color depth

* working area represents the usable browser area (browser overall size - browser chrome) which changes when browser is resized.  this would introduce inconsistency into the fingerprint and make it less reproducible.

sorry for the inconvenience.
