### ISSUE TITLE
Preprocessor Error

### ISSUE THREAD

**Issue by guillaumeparis2000** [Valve/fingerprintjs2#301]
Hello,

I'm trying to test the preprocessor functionality but it give me an error with the example you give.
```js
"error"
"Script error. (line 0)"
```

I upload the example here: [https://jsbin.com/wohumit/edit?html,js,console](https://jsbin.com/wohumit/edit?html,js,console)

Thanks.

**Comment by jonashaag** [comment]
Please provide a jsbin/jsfiddle that reproduces the bug. Yours causes some other error for me.

**Comment by jonashaag** [comment]
```

"ReferenceError: Fingerprint2 is not defined
    at HTMLDocument.<anonymous> (wohumit.js:2:1)"
```

**Comment by guillaumeparis2000** [comment]
I provide a jsbin here: https://jsbin.com/wohumit/edit?html,js,console
I don't see the reference error you say: "ReferenceError: Fingerprint2 is not defined
    at HTMLDocument.<anonymous> (wohumit.js:2:1)".

When I had a console.log(Fingerprint2) it return the function so Fingerprint is disponible.

**Comment by jonashaag** [comment]
Please try a jsfiddle or a simple static website. Maybe it's jsbin

**Comment by guillaumeparis2000** [comment]
It seems that jsfiddle doesn't like it. I put it in codepen: https://codepen.io/cool2000/pen/xYqKmo
You can see an error in the browser console (not the codepen console):
```js
fingerprint2.min.js:1 Uncaught TypeError: Cannot read property 'join' of undefined
    at VM2126 fingerprint2.min.js:1
    at Array.forEach (<anonymous>)
    at each (VM2126 fingerprint2.min.js:1)
    at VM2126 fingerprint2.min.js:1
    at VM2126 fingerprint2.min.js:1
```

Thanks

**Comment by jonashaag** [comment]
Ah, got error due to adblock. Thanks for reporting.
