### ISSUE TITLE
function "isFontAvailable" is not working properly.

### ISSUE THREAD

**Issue by otanim** [Valve/fingerprintjs2#303]
Hi @Valve,
It appears that in my case **fingerprintjs2**  returned different hashes, after doing comparisons of `components` I found that the issue was in `js_fonts` component, in some random cases "Segoe UI" font name was included, in other cases it's not.

I'm sure that it should be somehow related to:
```
(fontSpans[i].offsetWidth !== defaultWidth[baseFonts[i]] || fontSpans[i].offsetHeight !== defaultHeight[baseFonts[i]])
```
of `isFontAvailable` function.

**OS**: Ubuntu 16.\*,
**WebPack**: v1.\*,
**FrameWork**: React.js.

**Comment by jonashaag** [comment]
Please try latest master. If that doesn't help could you try to play around with the detection string to make it work for your setup?

**Comment by otanim** [comment]
Hi @jonashaag, after some investigation, I found that this issue was related with the process of page loading.
To make sure that `isFontAvailable` function works correct, the whole function should be triggered after `window.onload`, otherwise some fonts might not be initialized and drawing on canvas will not work as it should be, in case if the particular font wasn't included on a user's system.
To fix this issue you need to trigger **fingerprintjs2**'s function like this:
```javascript
window.addEventListener('load', function() {
  //sources goes here
})
```
I would like to create a PR, but I'm afraid to mess up the commit because of possible indenting of 2nd level.

**Comment by jonashaag** [comment]
I don't think this should be solved in fingerprintjs2 then. Maybe you could add a note to the README that you should be running fingerprinting after load then?

(You should really be running ALL JS after load...)
