### ISSUE TITLE
[FEATURE REQUEST] I made an audio fingerprinting tool.

### ISSUE THREAD

**Issue by cozylife** [Valve/fingerprintjs2#305]
I ported the code from Princeton to an IFFE, modernized it, and got it packaged up on its own. Once I was done, I spent hours trying to integrate it into FingerprintJS2, but I couldn't get it working. (I'm an artisan in my trade as a s PHP engineer. When it comes to JS, I'm still pretty good, but I know I'm not the best.)

So, after a few hours of fighting the code, trying to get it to either use a callback or a Promise to get your software to wait for the audio fingerprinting tool to finish, I finally gave up. So, no PR.

However, I know that an audio fingerprinting tool is on your wish list (as per the README), and I built one. It's up to you to add it to your library. I have no intention of keeping the audio tool updated, so it's safe to just paste it into your script and modify as needed.

Here's the repo with my code and how to use it: https://github.com/cozylife/audio-fingerprint

**Comment by jonashaag** [comment]
Thanks for bringing this up!

From a quick look it seems like the fingerprint varies with different browsers on the same machine, so it's comparable to webgl/canvas fingerprints in that it's a means to fingerprint browsers that is hard to fake.

We could include this in the library. I think we should simplify/refactor the audio-fingerprint code a bit before merging; also it would be best if #294 is merged before this ticket, although not a necessity.

**Comment by jonashaag** [comment]
Thanks for bringing this up!

From a quick look it seems like the fingerprint varies with different browsers on the same machine, so it's comparable to webgl/canvas fingerprints in that it's a means to fingerprint browsers that is hard to fake.

We could include this in the library. I think we should simplify/refactor the audio-fingerprint code a bit before merging; also it would be best if #294 is merged before this ticket, although not a necessity.

**Comment by cozylife** [comment]
Thanks @jonashaag! Please keep me posted once it's refactored and added to the library.

**Comment by ProcrastinatorCp** [comment]
Hi, I would like to give it a try.

**Comment by jonashaag** [comment]
Cool! I'd like to see a version of the above code that doesn't use dozens of functions that are called only a single time. Get rid of these functions, inline their code, maybe add comments to separate the sections.

To integrate into fingerprint.js, have a look at how font fingerprinting is implemented with callbacks.

**Comment by ProcrastinatorCp** [comment]
@jonashaag 
Hi, I have integrated audio fingerprint from @cozylife's repo. Could you please take a look.
(cc : @cozylife )

**Comment by jonashaag** [comment]
It's not released yet, try master

**Comment by jonashaag** [comment]
It's not released yet, try master
