### ISSUE TITLE
Wrong version 1.6.1 on CDNs

### ISSUE THREAD

**Issue by hgc81538** [Valve/fingerprintjs2#309]
Version [1.6.1](https://github.com/Valve/fingerprintjs2/archive/1.6.1.zip) introduced ```navigator.deviceMemory```.

However, v1.6.1 on CDN of [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/fingerprintjs2/1.6.1/fingerprint2.min.js) and [jsdelivr](https://cdn.jsdelivr.net/npm/fingerprintjs2@1.6.1/dist/fingerprint2.min.js) is still v1.5.1 which doesn't have ```navigator.deviceMemory```.

Please fix the JS content on CDN. Thanks.

**Comment by jonashaag** [comment]
@valve I'm not familiar with how this CDN works

**Comment by Valve** [comment]
@jonashaag that's because the latest release is named incorrectly v1.6.1 (should be v.1.6.1). JSDeliver bot picks project releases automatically, but they should be named correctly

**Comment by jonashaag** [comment]
OK, released v.1.7.0
