### ISSUE TITLE
jsFontsKey performance improvement

### ISSUE THREAD

**Issue by atsafrir** [Valve/fingerprintjs2#31]
The jsFontsKey should store its' result in a cookie and check and return the value stored in that cookie if it exists, before doing the Font detection again. The jsFontsKey is performing a lot of Layout and rendering operation that takes for IOS UIWebview about 5 sec to perform, the following makes the page load very sluggish and effect battery life.

**Comment by s-chris** [comment]
As a stop gap consider making the call non-blocking with something like setTimeout(function () {}, 0); where function is the could running the fingerprintjs2 code. Another option is to reduce the number of fonts being enumerated but this will also limit the uniqueness of the fingerprint.

**Comment by Valve** [comment]
@atsafrir storing in a cookie is a good idea, but I'm concerned about the size of this cache. Let's say the jsFontsKey has detected 400 fonts, this will require storing the array of 400 long-ish strings in a cookie. What do you think?

@s-chris making it non-blocking is a good idea. Maybe I should do it in a web worker if it's available?

**Comment by s-chris** [comment]
@Valve web worker is good too, I have had success just using the setTimeout method on a page I am testing with, let me know if you do the web worker and I will check it out.

**Comment by atsafrir** [comment]
I still think it worth saving the information in a cookie, a file containing all the fonts is sized at 12k. I guess the final font file size will be smaller. even if it is 12k it is worth saving in a cookie. currently the code is doing a very intensive rendering and layout calculations which run on every page that uses fingerprintjs2.

**Comment by Valve** [comment]
@atsafrir I'll try to think of something. Thanks

**Comment by atsafrir** [comment]
Valve you can also have a file as small as 400 bytes for 400 fonts with string format:
"101000010001011 ..." 
char '1' in place i represent "font in array place i is supported" and char '0' in place i "represent font in array place i is not supported". so you don't need to worry about the cookie file size.
from this string you can reconstruct the supported font string faster than the rendering and layout calculation. 
cookies may be disabled by the browser but you will always check if the cookie exists or not. but most of the times cookies will be enabled and that will save the time needed for rendering and layout calculations, the page will load faster, and you'll reduce the battery consumption of the code in mobile devices etc ...

**Comment by s-chris** [comment]
@atsafrir @Valve 

I noticed a few other small changes that could improve the js font detection. 

1 - There is not a need to test all 3 base fonts once one of them has determined the font being tested is present. Using the detected flag you can easily reduce the # of loops.

2 - You don't have to append and remove the span inside the loop. I tested on Chrome, FF, IE and it worked fine without doing this. 

'''javascript

          h.appendChild(s);
		  
          for (var index in baseFonts) {
			// Once the font is detected, there is no need to test it against the remaining fonts. This will save some time based on the # of fonts presented. I noticed about 200-300ms savings
			if (!detected) {
				s.style.fontFamily = font + "," + baseFonts[index]; // name of the font along with the base font for fallback.
				//h.appendChild(s);
				var matched = (s.offsetWidth !== defaultWidth[baseFonts[index]] || s.offsetHeight !== defaultHeight[baseFonts[index]]);
				//h.removeChild(s);
				detected = detected || matched;
				
				// tracking font detection to debug
				if (DEBUG) {
					var baseFontInt = baseFontTrack[index];
					if (detected) baseFontInt++;
					baseFontTrack[index] = baseFontInt;
				}
				
			}
			
			
          }
		  h.removeChild(s);

'''

I also added some logging to track the results were consistent. Here is the console output before and after the change with only the jsfonts enabled. 

// Chrome Incognito before change
Skipping flash fonts detection per excludeFlashFonts configuration option
fingerprint2.js:47 Total fonts: 497
fingerprint2.js:47 monospace: 239
fingerprint2.js:47 sans-serif: 240
fingerprint2.js:47 serif: 240
(index):42 Time took to calculate the fingerprint: 536ms
(index):43 f8a878512d9be3022df9c33fda1df171

// Chrome Incognito after change
Skipping flash fonts detection per excludeFlashFonts configuration option
fingerprint2.js:47 Total fonts: 497
fingerprint2.js:47 monospace: 239
fingerprint2.js:47 sans-serif: 1
fingerprint2.js:47 serif: 0
(index):42 Time took to calculate the fingerprint: 298ms
(index):43 f8a878512d9be3022df9c33fda1df171


Notice the hash is the same. Savings is about 100-200ms

**Comment by mhuisman** [comment]
I don't agree with the cookie storage suggestion.  Fingerprintjs2 is a stateless utility library and should remain such.  Knowledge of whether the method has already been called for a particular device is an application concern.

+1 to making fingerprint composition asynchronous, although I'd recommend making it a config option so as to ensure trivial debugging in local dev environment.

**Comment by Valve** [comment]
So, I'm going to do it in background and parallelize it  with web workers (if available). If not, I'll just use setTimeout.

**Comment by Valve** [comment]
@atsafrir @s-chris made it with setTimeout. This does not solve the issue of performance though, because the total time to calculate the FP stays the same, so I'm leaving the issue open.

**Comment by Valve** [comment]
I'm thinking to maybe limit the number of detected fonts, like when 50 fonts are already detected, to return early from the loop, what do you guys think?

**Comment by Valve** [comment]
Fixed on d4e3cf4edb184b73dd31e2b4943b2680cd4762c9
