### ISSUE TITLE
Different fingerprint on page zooming

### ISSUE THREAD

**Issue by medskill** [Valve/fingerprintjs2#311]
Like in the title, the fingerprint is different when using browser zoom.

Before zoom :
Your browser fingerprint:
84cfb4202c5b9e07cd2a6b7dc49ae6e0
[...]
pixel_ratio = 1

After zoom:
Your browser fingerprint:
f2425d5f75a4e6c2d73b7a07e7621e5c
[...]
pixel_ratio = 0.8999999761581421

Personally i've excluded pixel_ratio verification to prevent this. 
What do you think about disabling pixel_ratio verification by default?

**Comment by jonashaag** [comment]
Which version of fingerprintjs did you use?

**Comment by DamodarSojka** [comment]
I have just used the demo today: http://valve.github.io/fingerprintjs2/
So Fingerprintjs2
