### ISSUE TITLE
Make sure that Fingerprint2() can not be overwritten !?!?

### ISSUE THREAD

**Issue by PaykomanVll** [Valve/fingerprintjs2#313]
Hello,

if a FP saved on Session/Cookie can the attacker manipulate the dom and overwrite the Function for return defined hash. That is sad then i will use FP on websocket for more secure but this required the original function can not be overwritten!

Can this be implemented?

**Comment by franck34** [comment]
@jonashaag kind of prototype hijacking example there http://ajaxref.com/ch7/xhrhijackfullprototype.html

As an attacker, if i use an headless browser (phantom, pupeter, ..) i can inject js after page loading. So i can override FP and put whaterever i want in the hash

@PaykomanVll thinking about websocket too. On my side:

* fp is dynamicaly obfuscated and used only on user session init
* fp hash is sent by ajax
* fp data sent by websocket
=> i didn't finish this part, but the goal should be to compare/control the hash received with xhr and recreate the hash with data sent in websocket. Must be the same.

Perhaps Object.freeze() is a good way to protect against fp hijacking ?

**Comment by jonashaag** [comment]
If users tamper with JavaScript engine, settings, objects etc. there's really nothing you can do. Users can akways fake their fingerprints. This is nothing we can solve in this library.

Feel free to discuss the matter further but I'm closing this as won't fix

**Comment by franck34** [comment]
i'll try Object.freeze() on my side

**Comment by franck34** [comment]
@PaykomanVll https://esdiscuss.org/topic/object-freeze-object-prototype-vs-reality

@jonashaag Yes we can solve it in this library, i mean, avoid prototype pollution in fact. Let me PR in a few days.
