### ISSUE TITLE
update npm registry for 1.8.0

### ISSUE THREAD

**Issue by Enalmada** [Valve/fingerprintjs2#315]
cdnjs is at 1.6.1 and in the ticket I opened to have it updated, they mentioned that you need to update your npm registry.  

https://github.com/cdnjs/cdnjs/issues/12718

Thanks,
Adam

**Comment by jonashaag** [comment]
@valve do you know what that means? What do we have to do?

**Comment by Valve** [comment]
I think they want us to publish to NPM (that is update the registry) can you handle please @jonashaag?
Let me know if I should do it

**Comment by jonashaag** [comment]
@Valve yeah can you do it since I don't have an npm account.

**Comment by Valve** [comment]
Fixed. Thanks @Enalmada for reporting
