### ISSUE TITLE
Different fingerprint in FF only in windows OS

### ISSUE THREAD

**Issue by varunjoshi12** [Valve/fingerprintjs2#318]
I am using finger print JS of browser with the help of which i got the one unique key of that browser but my problem is that when i changed my resolution from 100,90,80,67.I am getting different keys,but i want unique key on the different resolution as well.This issue is only occured in windows machine with firefox browser only.For this i have already remove resolution parameter but it is not working in windows.I have remove this below parameter from fingerprint.js.

keys = this.screenResolutionKey(keys)
keys = this.availableScreenResolutionKey(keys)
keys = this.hasLiedResolutionKey(keys)
keys = this.platformKey(keys)

But this changes is not working in windows(OS) with firefox browser.Except this it is working in windows with chrome,ubuntu with both chrome and firefox.

I have getting different id from different pixel in mozilla browser with windows OS.But i want a unique id from all browser resolution.

I am using finger print JS of browser with the help of which i got the one unique key of that browser but my problem is that when i changed my resolution from 100,90,80,67.I am getting different keys,but i want unique key on the different resolution as well.This issue is only occured in windows machine with firebox only.For this i have already remove resolution parameter but it is not working in windows.I have already remove this below parameter from fingerprint.js.

keys = this.screenResolutionKey(keys)
keys = this.availableScreenResolutionKey(keys)
keys = this.hasLiedResolutionKey(keys)
keys = this.platformKey(keys)

But this changes is not working in windows with firefox browser.Except this it is working in windows chrome,ubuntu chrome and firefox.I have taken the browser finger print code from the github.If any buddy have any knowledge about this fingerprintjs then please help me.

I have getting key from different pixel in mozilla browser with windows OS.But i want a unique id from all browser resolution.

90 resolution : fa9edf1ab49d7959c7ac8723eaaa67ba
80 resolution: fa8b7c02eb333c50ab46dce01b075703
67 resolution: fa8b7c02eb333c50ab46dce01b075703
100 resolution: fa9edf1ab49d7959c7ac8723eaaa67ba

**Comment by varunjoshi12** [comment]
@Valve  please help me.

**Comment by jonashaag** [comment]
Are you talking about zoom levels? 100, 67, etc. aren't display resolutions.

Please record the fingerprint at the different zoom levels using the jsfiddle provided in the issue template and post them here.

**Comment by varunjoshi12** [comment]
yes i am talking about the zoom levels.I have got the right JS as well,but it is not working on 50 resolution or below 50 resolution on windows in FF browser it is giving me a different key.

**Resolution on all pixel**

100%:-ac17dda002b5a3cf5123abaae710440b
90%:-ac17dda002b5a3cf5123abaae710440b
80%:-ac17dda002b5a3cf5123abaae710440b
67%:-ac17dda002b5a3cf5123abaae710440b
50%:-1034727a7b17f8c77fd5a2bcd35575f5


**Below is my link code link where you got the key:**
http://server1.lmsin.com/machineauth/test.php

**Here you will get the js:**
http://server1.lmsin.com/machineauth/fingerprint2.js

**Comment by jonashaag** [comment]
Please paste the full fingerprints using the jsfiddle.

**Comment by varunjoshi12** [comment]
actually jsfiddle is not working with fingerprint.js.But i am only using this two files (**test.php,fingerpint2.js**)for creating a browser fingerprint let me know what is the full fingerprint ?.Are you talking about the code or different keys.If you talking about the code then  you will get js code from by clicking below link:-
http://server1.lmsin.com/machineauth/fingerprint2.js

**code for test.php**

  <input type="text" name="machine_code" id="machine_code" value="">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <script src="fingerprint2.js"></script>
  <script>
   
     $(document).ready(function(){
        var d1 = new Date();
      var fp = new Fingerprint2();
      fp.get(function(result, components) {
        var d2 = new Date();
        var timeString = "Time took to calculate the fingerprint: " + (d2 - d1) + "ms";
        var details = "<strong>Detailed information: </strong><br />";
        if(typeof window.console !== "undefined") {
          console.log(timeString);
          console.log(result);
          for (var index in components) {
            var obj = components[index];
            var value = obj.value;
            var line = obj.key + " = " + value.toString().substr(0, 100);
            console.log(line);
            details += line + "<br />";
          }
        }
       document.querySelector("#machine_code").val = result
        $('#machine_code').val(result);
         
      });
      
    });
    
    
  </script>
</body>
</html>

**Comment by jonashaag** [comment]
No, please paste a full list of all components for both of the different fingerprints here. Use the code provided here: https://jsfiddle.net/L2gLq4rg/ or roll your own if you want

**Comment by varunjoshi12** [comment]
Actually my fingerprint.js is not taking from this link http://server1.lmsin.com/machineauth/fingerprint2.js
 ,hence i will not able to create a exact demo on jsfiddle but for the components i have pasted my code in html of jsfiddle.

50 pixel
https://jsfiddle.net/varunjoshi22/43wx2ub1/

67 pixel
https://jsfiddle.net/varunjoshi22/wpgwem2u/

**Comment by jonashaag** [comment]
Copy and paste your fingerprints here.

**Comment by jonashaag** [comment]
Creates with the master version of fingerprintjs, not your version, whatever that is.

**Comment by jonashaag** [comment]
Closing due lack of response
