### ISSUE TITLE
Travis doesn't run test suite

### ISSUE THREAD

**Issue by jonashaag** [Valve/fingerprintjs2#319]
@Valve the tests don't seem to be run on Travis. Any idea why? I'm not familiar with jasmine/Javascript testing.

**Comment by jonashaag** [comment]
Also, let's test node 9, 10?

**Comment by Valve** [comment]
Yeah, I'm going to look into it on the weekend

**Comment by jonashaag** [comment]
@Valve bump :)

**Comment by Valve** [comment]
Sorry Jonas, currently have no bandwidth to work on this

**Comment by Valve** [comment]
@jonashaag I looked in this, it broke after this commit: https://github.com/Valve/fingerprintjs2/commit/c3a67a4191aa6aafbfafd0e92fecb3ab2f1612f4

You can revert the changes that you did and it should help.

But overall phantomJS is dead, we should migrate to something newer, e.g. Chrome Headless.

**Comment by jonashaag** [comment]
Ugh, maybe the JS runtime doesn't support ES6. I'll have a look.

**Comment by Valve** [comment]
It doesn't, should be plain old JS
