### ISSUE TITLE
npm is listed as dependency for fingerprintjs2 package.

### ISSUE THREAD

**Issue by magizh** [Valve/fingerprintjs2#321]
I dont see a need for npm to be marked as a dependency for fingerprintjs2. Any particular reason it is there. This bloats up the consumer node_modules folder and yarn.lock file adding 2k lines.

Also I noticed that the src on github doesnt have it https://github.com/Valve/fingerprintjs2/blob/master/package.json

**Comment by jonashaag** [comment]
@valve tried to fix this on npmjs.com but I couldn't figure out how

**Comment by magizh** [comment]
@jonashaag  thanks for the update. For what it is worth version 1.6.1 doesn't have the npm as dependency.

**Comment by richRemer** [comment]
If I'm not mistaken, the problem is that you can't overwrite an existing version number in the npm repos.  Just bump the version to 1.8.1 and publish again.

**Comment by richRemer** [comment]
Does this project have a release cycle?  Any word on when this will get fixed?  This is a major pain in the ass for anyone with a transitive dependency.

**Comment by Valve** [comment]
@richRemer no release cycle, it's a hobby project. Let me know what I should do. I don't know what a "transitive dependency" is either. I programmed in JS mostly when NPM didn't exist, so don't know many things. Please help me figure this out.

**Comment by djagya** [comment]
@Valve as @richRemer said, you can fix it by bumping the version to 1.8.1 and publishing the package

**Comment by Valve** [comment]
published 1.8.1 on npmjs: https://www.npmjs.com/package/fingerprintjs2

Let me know if t his fixed the issue @djagya @richRemer @magizh

**Comment by djagya** [comment]
@Valve seems to be fixed, thanks a lot!
