### ISSUE TITLE
Adding a semicolon at the end of the non minificated file

### ISSUE THREAD

**Issue by PierreJeanTilkee** [Valve/fingerprintjs2#333]
hello and thanks for this awesome lib !

i had a very little issue with the non minificated lib when i minified all my files : https://cdnjs.cloudflare.com/ajax/libs/fingerprintjs2/1.8.0/fingerprint2.js

adding a semicolon at line 1362 fixed it.

have a nice day

**Comment by jonashaag** [comment]
Not a bug in the lib, rather in your setup

**Comment by wesleifreitas** [comment]
is true, example:
https://stackoverflow.com/questions/42036349/uncaught-typeerror-intermediate-value-is-not-a-function
