### ISSUE TITLE
audioKey doesn't work on old mobile phone

### ISSUE THREAD

**Issue by nouc23** [Valve/fingerprintjs2#339]
My device is:
SAMSUNG I9100

It doesnt support AudioContext.

`Unhandled Promise rejection: AudioContext is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: AudioContext is not a function(…) TypeError: AudioContext is not a function
    at Object.Fingerprint2.audioKey (...)`

**Comment by jonashaag** [comment]
Fixed in master
