### ISSUE TITLE
audio-fingerprint error on iexplorer

### ISSUE THREAD

**Issue by ParleyRo** [Valve/fingerprintjs2#341]
Hi,

I'm getting a critical error on IExplorer 11
![error1fingerprint](https://user-images.githubusercontent.com/24639871/42755627-ac8c2c80-8901-11e8-9763-2fb51b166977.JPG)
![error1fingerprint_code](https://user-images.githubusercontent.com/24639871/42755628-acbc9276-8901-11e8-81d2-d35587e95f22.JPG)

Can you solve this?

**Comment by jonashaag** [comment]
Which version of fingerprintjs did you use?

**Comment by ParleyRo** [comment]
hi,

Fingerprintjs2 0.7.4

**Comment by jonashaag** [comment]
Try master

**Comment by jonashaag** [comment]
Just an honest question, why didn't you use the issue template provided by GitHub?

**Comment by ParleyRo** [comment]
thanks, it works now.

I didnt use the template because it didnt felt like it's my case. I'm sorry about that. I thought if show you the error it's more explanatory
