### ISSUE TITLE
AvailableScreenResolution detection causes different hashes

### ISSUE THREAD

**Issue by anotherCoward** [Valve/fingerprintjs2#352]
**ALL** BUG REPORTS WITHOUT PULL REQUEST MUST USE THIS TEMPLATE. BUG REPORTS NOT USING THE TEMPLATE ARE SUBJECT TO BEING CLOSED WITHOUT COMMMENT.

### Problem description

AvailableScreenResolution detection causes different hashes if opened on different monitors. Disabling it, generates equal hashes.

### Fingerprintjs2 version and devices used

1.8.0
Win 10 Chrome 67 and Win 10 jxbrowser v49

### Minimal reproducing example

Disable/Enable excludeAvailableScreenResolution

**Comment by jonashaag** [comment]
Please verify with master
