### ISSUE TITLE
Suggestion: Add timezone from the Internationalization API if available

### ISSUE THREAD

**Issue by SleepProgger** [Valve/fingerprintjs2#356]
The [Internationalization API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) provides, besides some other maybe interesting data, the time zone the user is in.
This data contains more information as a simple `new Date().getTimezoneOffset()` does.

Example from my system:
`Intl.DateTimeFormat().resolvedOptions()`
->
`Object { locale: "en-US", calendar: "gregory", numberingSystem: "latn", timeZone: "Europe/Berlin", month: "numeric", day: "numeric", year: "numeric" }`

**Comment by jonashaag** [comment]
PR welcome

**Comment by SleepProgger** [comment]
Awesome, i'll send an PR sometime the next week.
I assume only the timeZone and disabled by default to not suddenly produce different hashes for the same user ?

**Comment by SleepProgger** [comment]
Added in #364
