### ISSUE TITLE
Different signature on same machine

### ISSUE THREAD

**Issue by varunjoshi12** [Valve/fingerprintjs2#370]
Hello,
I am using Valve fingerprintjs2 for browser authentication.But it is giving me different id on same machine
it is not happened frequently but occurring this error in random case.For this i have also save the browser and other information but both the browser information are same but signature key is different.I am posting the information below please help me to resolve this issue.For this i am using 

My JS Url:
http://server1.lmsin.com/machineauth/fingerprint2.js

<strong>Detailed information: </strong><br />user_agent = Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.<br />timezone_offset = -330<br />regular_plugins = Chrome PDF Plugin::Portable Document Format::application/x-google-chrome-pdf~pdf,Chrome PDF Viewer::<br />js_fonts = Arial,Arial Black,Arial Narrow,Arial Unicode MS,Book Antiqua,Bookman Old Style,Calibri,Cambria,Cambr<br />

**Key**:658a83e0df743d4db554679e67b3ee25  

<strong>Detailed information: </strong><br />user_agent = Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.<br />timezone_offset = -330<br />regular_plugins = Chrome PDF Plugin::Portable Document Format::application/x-google-chrome-pdf~pdf,Chrome PDF Viewer::<br />js_fonts = Arial,Arial Black,Arial Narrow,Arial Unicode MS,Book Antiqua,Bookman Old Style,Calibri,Cambria,Cambr<br />

**Key**:4d2c79138aaae5b11c0fabd2b1a3d101

Thanks in Advance

**Comment by varunjoshi12** [comment]
@Valve

**Comment by varunjoshi12** [comment]
@jonashaag Please help me to resolve this issue and let me know why it is closed is there any solution for this issue.

**Comment by jonashaag** [comment]
Please use the issue template

**Comment by varunjoshi12** [comment]
Please can you provide the url of issue template.

**Comment by jonashaag** [comment]
It is shown in the issue text editor when you create a new issue
