### ISSUE TITLE
AudioKey doesn't work in IE11

### ISSUE THREAD

**Issue by theindra** [Valve/fingerprintjs2#377]
### Problem description

When trying to get a fingerprint with Internet Explorer 11 (v11.228.17134.0) on Windows 10 I get the following error:

DE: "SCRIPT445: Das Objekt unterstützt diese Aktion nicht."
EN: "SCRIPT445: Object doesn't support this action"

It happens in line 119: 

> var context = new AudioContext(1, 44100, 44100)

### Fingerprintjs2 version and devices used
Bug happens with fingerprint version 1.8.1
It works with version 1.6.1

**Comment by jonashaag** [comment]
Should be fixed in master

**Comment by ChadKillingsworth** [comment]
Can we get a release with this in it? 1.8.1 throws errors in IE.
