### ISSUE TITLE
How configure script to obtain one device print on diffrent web browsers?

### ISSUE THREAD

**Issue by Plachon** [Valve/fingerprintjs2#381]
I'm looking for a script which will give me the one device print on different web browser. Which options should be disable to the best detecting device without web browser sensitivity. I know that detecting will be not optimal for reduce the collision number.

**Comment by jonashaag** [comment]
Here's my current understand of the options. No guarantees it's 100% correct.

<table>
<thead>
<tr><th>Option</th><th>Browser dependent</th></tr>
</thead>
<tr><td>userAgent</td><td>yes</td></tr>
<tr><td>language</td><td>no</td></tr>
<tr><td>colorDepth</td><td>no</td></tr>
<tr><td>deviceMemory</td><td>no</td></tr>
<tr><td>pixelRatio</td><td>no</td></tr>
<tr><td>hardwareConcurrency</td><td>no</td></tr>
<tr><td>screenResolution</td><td>no</td></tr>
<tr><td>availableScreenResolution</td><td>no</td></tr>
<tr><td>timezoneOffset</td><td>no</td></tr>
<tr><td>timezone</td><td>no</td></tr>
<tr><td>sessionStorage</td><td>yes</td></tr>
<tr><td>localStorage</td><td>yes</td></tr>
<tr><td>indexedDb</td><td>yes</td></tr>
<tr><td>addBehavior</td><td>yes</td></tr>
<tr><td>openDatabase</td><td>yes</td></tr>
<tr><td>cpuClass</td><td>no</td></tr>
<tr><td>platform</td><td>no</td></tr>
<tr><td>doNotTrack</td><td>yes</td></tr>
<tr><td>plugins</td><td>yes</td></tr>
<tr><td>canvas</td><td>yes in practise</td></tr>
<tr><td>webgl</td><td>yes in practise</td></tr>
<tr><td>webglVendorAndRenderer</td><td>no (?)</td></tr>
<tr><td>adBlock</td><td>yes</td></tr>
<tr><td>hasLiedLanguages</td><td>no</td></tr>
<tr><td>hasLiedResolution</td><td>no</td></tr>
<tr><td>hasLiedOs</td><td>no</td></tr>
<tr><td>hasLiedBrowser</td><td>no</td></tr>
<tr><td>touchSupport</td><td>no</td></tr>
<tr><td>customEntropyFunction</td><td>-</td></tr>
<tr><td>fonts</td><td>no (most of the time)</td></tr>
<tr><td>audio</td><td>?</td></tr>
<tr><td>enumerateDevices</td><td>?</td></tr>
</table>
