### ISSUE TITLE
Upgrade plan for fingerprintjs2

### ISSUE THREAD

**Issue by GrosSacASac** [Valve/fingerprintjs2#382]
I have plans to make an upgrade to fingerprintjs2 over the next few days, I have read most of the existing issues, and have a good idea where I am going. I will first make a pull request with non breaking changes so it should be accepted without too many problem, then another one with breaking changes which if accepted will have positive effects for the long term evolution of this project.

It seems v2 branch is stopped.
Consider to remove it eventually.

Saw some interesting commits but not sure if they have been done in master branch too,
since the v2 branch is ahead AND behind the master branch, anyway I think I captured the most interesting parts of v2 branch (see below).

#### Semver Backwards compatible changes

- [x] fix html with https://validator.w3.org/
- [x] from v2 [test cleanup after flash removal](https://github.com/Valve/fingerprintjs2/commit/322001a20314c79e6d8b415d3adea4befa1beff1)
- [x] from v2 [no need to reassign keys all the time](https://github.com/Valve/fingerprintjs2/commit/57cdd13eb2e05614a66b4e1901c821cdd9ab82d6) [bis](https://github.com/Valve/fingerprintjs2/commit/7534c727d2b86e1d6468c7aeec64209316bcc473)
- [x] rename variable oncompleteTimeout 
- [x] COMBINE README AND WIKI https://github.com/Valve/fingerprintjs2/issues/262
- [x] from v2 [`push({key, value}) -> push(key, value);`]
- [x] check if https://chrome.google.com/webstore/detail/canvasfingerprintblock/ipmjngkmngdcdpmgmiebdmfbkcecdndc  makes crash(https://github.com/Valve/fingerprintjs2/commit/b8fd6f605b39d42c1755a78f522036a036d57baf )
- [x] https://github.com/Valve/fingerprintjs2/issues/316
 * <del>from v2 [avoid switch statements](https://github.com/Valve/fingerprintjs2/commit/017c86f4912174c95f22b3b7f170777f9d9e4b12)</del>
 * <del>generate the list of options from the code</del>
 * </del>use more descriptive, potentially longer variable names, the minifier can equalize after all</del>
 * improve documentation

#### Semver Breaking Changes (please discuss)

- [x] https://github.com/Valve/fingerprintjs2/pull/291 introduce promise, and better error handling
(https://github.com/Valve/fingerprintjs2/commit/b53c2a23b64b01bc375704b283b8dab2a31ecb1b) that already allows import of hash function
 * [drop IE9 support](https://github.com/Valve/fingerprintjs2/issues/331)
 * Object.assign instead of extend
 * hash function should be in a separate file, independent import, application code should decide if wants to hash or not, not library code, v2 also [had commit]
 * leverage fingerprintjs as a platform todo: explain how 

### Not categorized (later)

 * https://github.com/Valve/fingerprintjs2/issues/283
 * https://github.com/Valve/fingerprintjs2/issues/201
 * https://github.com/Valve/fingerprintjs2/issues/176
 * https://github.com/Valve/fingerprintjs2/issues/169

**Comment by jonashaag** [comment]
Thanks for the effort! Please make separate PRs for any changes if applicable. This makes code reviews much easier.

**Comment by jonashaag** [comment]
> improve documentation

Always a good idea :)

> from v2 [test cleanup after flash removal](https://github.com/Valve/fingerprintjs2/commit/322001a20314c79e6d8b415d3adea4befa1beff1)

> from v2 [no need to reassign keys all the time](https://github.com/Valve/fingerprintjs2/commit/57cdd13eb2e05614a66b4e1901c821cdd9ab82d6) 

This is bike shedding, no need to change.

> https://github.com/Valve/fingerprintjs2/commit/7534c727d2b86e1d6468c7aeec64209316bcc473)

Prefer @sleepprogger's fork's changes to this.

> from v2 [avoid switch statements](https://github.com/Valve/fingerprintjs2/commit/017c86f4912174c95f22b3b7f170777f9d9e4b12)

This is ok, no need to change.

> rename variable oncompleteTimeout

why though

> generate the list of options from the code

Also prefer @SleepProgger's fork to this

> use more descriptive, potentially longer variable names, the minifier can equalize after all

OK with that in general.



> hash function should be in a separate file, independent import, application code should decide if wants to hash or not, not library code, v2 also [had commit](https://github.com/Valve/fingerprintjs2/commit/b53c2a23b64b01bc375704b283b8dab2a31ecb1b) that already allows import of hash function

OK with me.

> [drop IE9 support](https://github.com/Valve/fingerprintjs2/issues/331)

👍

> Object.assign instead of extend

OK if that's supported by most browsers

> #291 introduce promise, and better error handling

👍

> leverage fingerprintjs as a platform todo: explain how

Not sure what this means?

**Comment by GrosSacASac** [comment]
> Not sure what this does TBH
> 

> > from v2 no need to reassign keys all the time
https://github.com/GrosSacASac/fingerprintjs2/commit/2f71415acbe2c081a154ec52b31f0b14a3a52758

**Comment by GrosSacASac** [comment]
Ok thanks, 
Small PR made https://github.com/Valve/fingerprintjs2/pull/383

For the rest I will make individual PR and issues as requested

**Comment by 415DomSmith** [comment]
Big fan of 
> hash function should be in a separate file, independent import, application code should decide if wants to hash or not, not library code, v2 also had commit that already allows import of hash function.

Looking forward to your changes.

**Comment by GrosSacASac** [comment]
Splitting into multiple files, with treeshaking support would be the next step after https://github.com/Valve/fingerprintjs2/pull/388 id merged

**Comment by GrosSacASac** [comment]
https://github.com/Valve/fingerprintjs2/issues/394 Opened

I will not have much time in the upcomming weeks so feel free to work on it

**Comment by GrosSacASac** [comment]
Closing, as individual issues do  exist, I will not have time in the near future.
