### ISSUE TITLE
"§"  sometimes become  "Â§".

### ISSUE THREAD

**Issue by gazhikaba** [Valve/fingerprintjs2#39]
For now, I don't find out why.
That happens in different pages with one browser.
I compare all values, all of them is same, except  "§"  -> "Â§".

-------
Could I ask why not use some normal character? 
Is there has special reason? Thank you very much.

**Comment by Valve** [comment]
@gazhikaba or no, no special reason, just a typo, I wanted to use tilde (~), but I miss it sometimes when working on an external keyboard. I'll fix it today and release a new minor version.

**Comment by Valve** [comment]
Fixed in 0.1.3
