### ISSUE TITLE
publish new version

### ISSUE THREAD

**Issue by ewief** [Valve/fingerprintjs2#392]
maybe its time to publish a new version to npm, as current 1.8.1 is a bit outdated regarding bug fixes

**Comment by jonashaag** [comment]
done

**Comment by ewief** [comment]
New version seems to be missing dist folder

**Comment by jonashaag** [comment]
try now

**Comment by ewief** [comment]
all good now, but without bug fixes.
I tried to compile master.
It compiled, worked and no lint errors.

**Comment by jonashaag** [comment]
Which fixes are you referring to?

**Comment by bighappyface** [comment]
@jonashaag how about publishing v2.0.0 on NPM as well?

**Comment by jonashaag** [comment]
It's there https://www.npmjs.com/package/fingerprintjs2/v/2.0.3
