### ISSUE TITLE
NPM Version Mismatch

### ISSUE THREAD

**Issue by boulosda** [Valve/fingerprintjs2#398]
### problem description

- the latest npm version does not match the latest github release

### minimal reproducing example

visit [fingerprint2js](https://www.npmjs.com/package/fingerprintjs2) to see the current release as 1.8.5 while the latest github release is 2.0.0

this may not be a mistake but if not is the latest 1.8.5 release just for compatibility? Should we manually set the install version to 2.0.3, the version released just before 1.8.5, if we want to be on the latest 2.0.0 github release?

thanks for your help

**Comment by jonashaag** [comment]
Thanks, fixed, latest tag is now 2.0.3

1.8.X is the 1.8 bug fix series
