### ISSUE TITLE
how is fingerprintjs2 working now

### ISSUE THREAD

**Issue by dodolzg** [Valve/fingerprintjs2#40]
From http://valve.github.io/blog/2013/07/14/anonymous-browser-fingerprinting/, it notes:
browser fingerprinting is not good with mobile browsers, unless you want to distinguish Android users from iPhone ones.

From https://gitter.im/Valve/fingerprintjs2/archives/2015/03/09, it notes:
 This library will try to make every effort to work well on mobile.

What is the accurate in mobile inlucde android and ios now?
I'm not sure whether to use fingerprintjs2 on mobile or not, thanks.

**Comment by Valve** [comment]
Hi @dodolzg,

I would love myself to have that stat data, but I don't, yet. We're not using it in our company (yet).
However, there are companies that are using it already: http://libscore.com/#Fingerprint2

So you may have a better luck asking them. 
Thanks!

**Comment by dodolzg** [comment]
Thanks!
