### ISSUE TITLE
Different plugins for chrome and opera

### ISSUE THREAD

**Issue by Agronya** [Valve/fingerprintjs2#406]
I test fingerprint in last chrome and opera, they different and i see that Google Chrome use work "chrome" in plugins string, but opera use "chromium".

Chrome: 

Your browser fingerprint:
c7a66c5f55ed058d755751b7b588ec9c

Time took to calculate the fingerprint: 164 ms

Detailed information:

userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.10
language = ru-RU
colorDepth = 24
deviceMemory = 8
hardwareConcurrency = 4
screenResolution = 1920,1080
availableScreenResolution = 1920,1040
timezoneOffset = -180
timezone = Europe/Moscow
sessionStorage = true
localStorage = true
indexedDb = true
addBehavior = false
openDatabase = true
cpuClass = not available
platform = Win32
plugins = Chrome PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chrome PDF Viewer,,ap
canvas = canvas winding:yes,canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAgA
webgl = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAN/UlEQVR4Xu2dQYhkRxnHv3rds4uIaM
webglVendorAndRenderer = Google Inc.~ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
adBlock = false
hasLiedLanguages = false
hasLiedResolution = false
hasLiedOs = false
hasLiedBrowser = false
touchSupport = 0,false,false
fonts = Arial,Arial Black,Arial Narrow,Book Antiqua,Bookman Old Style,Calibri,Cambria,Cambria Math,Century,C
audio = 124.0434474653739

Opera:

Your browser fingerprint:
16c2cfdb99bd6ffaeed72e590da679d9

Time took to calculate the fingerprint: 332 ms

Detailed information:

userAgent = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Saf
language = ru-RU
colorDepth = 24
deviceMemory = 8
hardwareConcurrency = 4
screenResolution = 1920,1080
availableScreenResolution = 1920,1040
timezoneOffset = -180
timezone = Europe/Moscow
sessionStorage = true
localStorage = true
indexedDb = true
addBehavior = false
openDatabase = true
cpuClass = not available
platform = Win32
plugins = Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer
canvas = canvas winding:yes,canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAgA
webgl = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAN/UlEQVR4Xu2dQYhkRxnHv3rds4uIaM
webglVendorAndRenderer = Google Inc.~ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
adBlock = false
hasLiedLanguages = false
hasLiedResolution = false
hasLiedOs = false
hasLiedBrowser = false
touchSupport = 0,false,false
fonts = Arial,Arial Black,Arial Narrow,Book Antiqua,Bookman Old Style,Calibri,Cambria,Cambria Math,Century,C
audio = 124.0434474653739

**Comment by jonashaag** [comment]
Thanks for the report. Interesting. However I don't think this is something we should be worried about. When you have multiple browsers you're likely to have different plugins in these browsers anyways, so it doesn't really help re-identifying the same user.

**Comment by Valve** [comment]
Agree, this is targeted at **a** browser fingerprinting, impossible to make it consistent across multiple browsers. You'd need additional server-side code to coordinate and reconcile the fingerprints
