### ISSUE TITLE
finger print fails to keep save ID when using inspect on browser 

### ISSUE THREAD

**Issue by IbrahimJakmour** [Valve/fingerprintjs2#408]
### Scenario

- What's the scenario, what happens and what did you expect to happen? 
- What device and browser are you using?
- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)

### Fingerprint data

If applicable, provide the FULL DATA of all fingerprints involved using this jsfiddle https://jsfiddle.net/L2gLq4rg/85/.
Alternatively, provide a jsfiddle that reproduces the bug.

**Comment by IbrahimJakmour** [comment]
finger print fails to keep save ID when using inspect on browser and changing the size of screen to mobile or less i was using it to see my new users who logg in while developping it i saw a fail in keeping the same id when switching from desktop to mobile browser from the same browser

**Comment by jonashaag** [comment]
That’s expected behavior, exclude the resolution component if not wanted
