### ISSUE TITLE
Failed to get key 'timezone' in Google Chrome 71.0.3578.80 on Windows 7

### ISSUE THREAD

**Issue by ema394** [Valve/fingerprintjs2#410]
### Scenario

- What causes the fingerprint to change?
Timezone key is undefined on Google Chrome (release 71.0.3578.80) with Windows 7 as OS so this causes the fingerprint to change.
- What device and browser are you using?
Google Chrome 71.0.3578.80 on Windows 7 - U.A. Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)
2.0.3

### Fingerprint data

Provide the FULL DATA of both/all fingerprints using this jsfiddle https://jsfiddle.net/L2gLq4rg/85/.
Alternatively, provide a jsfiddle that reproduces the bug.

**Comment by jonashaag** [comment]
What's the result of evaluating `new window.Intl.DateTimeFormat().resolvedOptions().timeZone` in that environment?

**Comment by ema394** [comment]
The result is "undefined"

**Comment by jonashaag** [comment]
Interesting. What's your system timezone?

**Comment by jonashaag** [comment]
Can you post the output of `new window.Intl.DateTimeFormat().resolvedOptions()`

**Comment by ema394** [comment]
> 
> 
> Interesting. What's your system timezone?

Europe/Rome

**Comment by jonashaag** [comment]
OK no idea how this happens. Marking as needinfo, maybe someone else has seen the same behaviour.

**Comment by ema394** [comment]
> 
> 
> Can you post the output of `new window.Intl.DateTimeFormat().resolvedOptions()`

![ss_bug](https://user-images.githubusercontent.com/15741431/49861409-0b6bcc00-fdfc-11e8-8124-738cc77a813c.png)

**Comment by ema394** [comment]
It's a known issue in Chrome 71 that only affects Windows 7. The fix will be included in next minor patch update, to be released soon.
