### ISSUE TITLE
Please fix npm latest version

### ISSUE THREAD

**Issue by dotnetCarpenter** [Valve/fingerprintjs2#415]
### Scenario

- What version of fingerprintjs are you using? 2.0.3
- Latest version on npm is 1.8.6

When I do `npm outdated --depth=0` I get:
```
Package                Current          Wanted  Latest  Location
fingerprintjs2           2.0.3           2.0.3   1.8.6
```

2.0.3 is published to npm https://www.npmjs.com/package/fingerprintjs2, so I wonder if you used [dist-tag](https://docs.npmjs.com/cli/dist-tag)?

There is an answer on SO regarding global installed npm packages that states that latest dist-tag is used as _latest_. https://stackoverflow.com/a/33835041 

Similar to the outdated #232

**Comment by dotnetCarpenter** [comment]
@jonashaag If you didn't use `npm dist-tag` then just close this. I must be a npm issue. Let's hope they get around to fix it someday. :-S

**Comment by jonashaag** [comment]
I don't think I did. If you tell me how to fix your problem (still not sure what the problem actually is?) I'm happy to fix it. Not an npm pro!

**Comment by dotnetCarpenter** [comment]
It seems to be a known issue with npm. https://github.com/npm/www/issues/89#issuecomment-268575927
Unfortunately there is no time frame for a fix.

**Comment by dotnetCarpenter** [comment]
I quickly made an issue at https://npm.community/t/timeframe-for-fixing-latest-not-being-semver-latest/4207 to ask about a timeframe for a fix.
