### ISSUE TITLE
Re-publish v2.x to NPM

### ISSUE THREAD

**Issue by motss** [Valve/fingerprintjs2#417]
Referring to #416, the latest package shows `1.8.6` as the `latest` however the package is already `v2.x`. Please do a re-publish again to rectify the issue. New users or existing users need `v2.x` while installing the package from NPM.

**Comment by shangtianjin** [comment]
是的，希望尽快把2.X发布到NPM上面吧

**Comment by jonashaag** [comment]
OK, republished as 2.0.4, please check if everything's ok

**Comment by millimoose** [comment]
@jonashaag The current 2.0.4 I'm getting from NPM doesn't include the `dist` folder, which breaks builds entirely.

**Comment by lihan** [comment]
@millimoose Got the same problem, maybe use the folk until they fix it. 
`yarn add lihan/fingerprintjs2#fix-build-error`

**Comment by jonashaag** [comment]
OK, try 2.0.5

**Comment by millimoose** [comment]
Seems ok on my end with 2.0.6 now, thanks!|
