### ISSUE TITLE
NPM published 2.0.5 does not have a dist folder

### ISSUE THREAD

**Issue by bradacina** [Valve/fingerprintjs2#421]
It looks like version 2.0.5 on NPM does not contain a dist folder.

Version 2.0.3 did have one. We referenced the .js.min file inside the dist folder during our CI process which of course started breaking all of a sudden.

PS: so much for semantic versioning and patch releases ;)

**Comment by jonashaag** [comment]
Can you try 2.0.6?

**Comment by Valve** [comment]
```
➜  ~ mkdir temp42
➜  ~ cd temp42 
➜  temp42 npm i fingerprint2 -D
➜  temp42 ls node_modules/fingerprintjs2/dist 
fingerprint2.min.js
```
