### ISSUE TITLE
It doesn't  work in Chrome For Mac 

### ISSUE THREAD

**Issue by harry-sunhao** [Valve/fingerprintjs2#434]
### Scenario

- What's the scenario, what happens and what did you expect to happen? 
The button is not working on this website https://valve.github.io/fingerprintjs2/. 
- What device and browser are you using?
Mac Chrome 72.0.3626.119
- What version of fingerprints are you using? (Bug reports not applicable to fingerprint master are subject to be closed without comment.)
Fingerprintjs2 2.0.6
### Fingerprint data

If applicable, provide the FULL DATA of all fingerprints involved using this jsfiddle https://jsfiddle.net/L2gLq4rg/85/.
Alternatively, provide a jsfiddle that reproduces the bug.

**Comment by jonashaag** [comment]
Are you using an ad blocker?

**Comment by harry-sunhao** [comment]
> Are you using an ad blocker?
Oh. Yes I forgot it. I will be double check with no ad blocker

**Comment by harry-sunhao** [comment]
I close the Adblock. It is working
