### ISSUE TITLE
window.ontouchstart issue

### ISSUE THREAD

**Issue by interactivepulse** [Valve/fingerprintjs2#443]
Experienced different fingerprint values on the same browser. Found a conflict in another function that was using window.ontouchstart before the fingerprint was generated. I checked across mousemove,mousedown, keypress and onclick and no issues. Just seems a conflict if using the ontouchstart elsewhere before running the fingerprint.

**Comment by jonashaag** [comment]
Thanks for the report. Please provide the full fingerprint data as described in the issue template.
