### ISSUE TITLE
Instructions to Debug Font Detection

### ISSUE THREAD

**Issue by nebi-frame** [Valve/fingerprintjs2#444]
Hi, I saw that lots of the people are facing the issue for list of fonts from the fingerprintjs2.
And we know from several top tier papers that, list of fonts give huge entropy still today.
I'm experienced developer, want to invest my time into this to debug the font detection.
Anyone can guide me how to debug font detection?

**Comment by jonashaag** [comment]
Basically trial and error on multiple browsers and OSes. If you find errors in recognition play around with the CSS styles we’re applying to the text elements.
