### ISSUE TITLE
A new way to fingerprint font using canvas

### ISSUE THREAD

**Issue by nebi-frame** [Valve/fingerprintjs2#445]
Hi guys, I stumbled upon this project : https://webtransparency.cs.princeton.edu/webcensus/index.html#canvas-font-fp
They offer a different way to detect fonts, it seems promising to me ? 
What are your thoughts on this?
Should fingerprintjs2 use this approach instead of div>span ?

**Comment by jonashaag** [comment]
Interesting. If someone wanted to put in the work and compare the two methods that’d be awesome!

**Comment by nebi-frame** [comment]
I'm willing to do this, are u guys open to pull requests?

**Comment by nebi-frame** [comment]
Actually I already have a demo just need to format it before sending pr

**Comment by jonashaag** [comment]
Sure, awesome!
