### ISSUE TITLE
Remove or document collection of Google Analytics in index.html

### ISSUE THREAD

**Issue by mathewcohle** [Valve/fingerprintjs2#446]
### Scenario

- What's the scenario, what happens and what did you expect to happen? 

I opened locally [index.html](https://github.com/Valve/fingerprintjs2/blob/2.0.6/index.html) to test my browser fingerprint (I thought this file is replacement for mentioned `spec_runner.html` which I was not able to find in the repository) and only then I've find out that it collects [Google Analytics](https://github.com/Valve/fingerprintjs2/blob/2.0.6/index.html).

I would expect that running such test locally would not trigger collection of data or that such action is at least documented.

- What device and browser are you using?

Would happen on any device/browser.

- What version of fingerprintjs are you using? 

2.0.6

**Comment by Valve** [comment]
yeah, you can remove it, please submit a PR and I'll merge it @mathewcohle
