### ISSUE TITLE
Trying to understand logic behind getHasLiedOs.

### ISSUE THREAD

**Issue by michaelklem** [Valve/fingerprintjs2#447]
### Scenario

- Issue is when generating a fingerprint from https://fingerprintjs.com/ from my iphone 7, the hasLiedOs attribute is false. I don't understand the reasoning behind the hasLiedOs logic.
- iPhone 7 using OS 12.1.4
- I am using what ever version is on https://fingerprintjs.com and version 2.0.5 on my own web site with the same results for hasLiedOs.

### Fingerprint data

If applicable, provide the FULL DATA of all fingerprints involved using this jsfiddle https://jsfiddle.net/L2gLq4rg/85/.
I could not provide details from the jsfiddle site since it was not usable on my iphone. Unable to view all the FP data. Here is the console log data from your fingerprint web site:

[Log] time – 223 (index.js, line 36)
[Log] fingerprint hash – "e6f3e2cefaae6454fbc8137e240715a4" (index.js, line 37)
[Log] userAgent = Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Ve (index.js, line 42)
[Log] language = en-US (index.js, line 42)
[Log] colorDepth = 32 (index.js, line 42)
[Log] deviceMemory = not available (index.js, line 42)
[Log] hardwareConcurrency = not available (index.js, line 42)
[Log] screenResolution = 667,375 (index.js, line 42)
[Log] availableScreenResolution = 667,375 (index.js, line 42)
[Log] timezoneOffset = 420 (index.js, line 42)
[Log] timezone = America/Los_Angeles (index.js, line 42)
[Log] sessionStorage = true (index.js, line 42)
[Log] localStorage = true (index.js, line 42)
[Log] indexedDb = true (index.js, line 42)
[Log] addBehavior = false (index.js, line 42)
[Log] openDatabase = true (index.js, line 42)
[Log] cpuClass = not available (index.js, line 42)
[Log] platform = iPhone (index.js, line 42)
[Log] plugins =  (index.js, line 42)
[Log] canvas = canvas winding:yes,canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAAA (index.js, line 42)
[Log] webgl = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAAAXNSR0IArs4c6QAAC/VJREFUeAHtnU (index.js, line 42)
[Log] webglVendorAndRenderer = Apple Inc.~Apple A10 GPU (index.js, line 42)
[Log] adBlock = false (index.js, line 42)
[Log] hasLiedLanguages = false (index.js, line 42)
[Log] hasLiedResolution = false (index.js, line 42)
[Log] hasLiedOs = true (index.js, line 42)
[Log] hasLiedBrowser = false (index.js, line 42)
[Log] touchSupport = 0,true,true (index.js, line 42)
[Log] fonts = Arial,Arial Hebrew,Arial Rounded MT Bold,Courier,Courier New,Georgia,Helvetica,Helvetica Neue,Palati (index.js, line 42)
[Log] audio = 35.10893253237009 (index.js, line 42)

In the getHasLiedOs, I added debug logs to see the values of the platform and os variables. For my iphone 7 these were platform = iphone and os = iOS. 

In the 2.0.5 source, in file fingerprint2.js at line 1151 there are these lines:
    } else if ((platform.indexOf('mac') >= 0 || platform.indexOf('ipad') >= 0 || platform.indexOf('ipod') >= 0 || platform.indexOf('iphone') >= 0) && os !== 'Mac' && os !== 'iOS') {
      return true
    } else if ((platform.indexOf('win') === -1 && platform.indexOf('linux') === -1 && platform.indexOf('mac') === -1) !== (os === 'Other')) {
      return true
    }

The first else if statement is skipped because platform = 'iphone' and os = 'iOS', but the next else if statement causes the getHasLiedOs function to return true. Is this a bug or an expected behavior?

Thank you.

**Comment by Valve** [comment]
@michaelklem it's pretty hard to follow which specific line returns true in your case. Can you please link to a line the source which returns true for you?

**Comment by michaelklem** [comment]
Hi.
In the 2.0.6 source code, the line that returns true for my iphone is found [here](https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L1160).

**Comment by Valve** [comment]
thanks @michaelklem I'll work on understanding why it's happening

**Comment by Valve** [comment]
@michaelklem I'm confirming the bug, thanks for reporting! Will fix it today or tomorrow.
