### ISSUE TITLE
Question: Firefox receives protections against fingerprinting

### ISSUE THREAD

**Issue by Daijobou** [Valve/fingerprintjs2#456]
Will this have an effect on Fingerprintjs2?

News: https://blog.mozilla.org/futurereleases/2019/04/09/protections-against-fingerprinting-and-cryptocurrency-mining-available-in-firefox-nightly-and-beta/

**Comment by HuiiBuh** [comment]
If looks like the only block the domain the scripts get served from. If you host the script yourself you shoud be OK.

```
To combat these threats, we are pleased to announce new protections against fingerprinters and cryptominers. In collaboration with Disconnect, we have compiled lists of domains that serve fingerprinting and cryptomining scripts. Now in the latest Firefox Nightly and Beta versions, we give users the option to block both kinds of scripts as part of our Content Blocking suite of protections.
```

**Comment by Valve** [comment]
You can rename the script and embed it into your scripts using NPM package. Should work that way. Closing because not a technical issue, but more of a code/project organization. Please feel free to reopen with additional questions/comments.

**Comment by Daijobou** [comment]
Here a new one https://blog.mozilla.org/security/2020/01/07/firefox-72-fingerprinting/
