### ISSUE TITLE
How to include Fingerprint 2 in Vue.js app?

### ISSUE THREAD

**Issue by rabichawila** [Valve/fingerprintjs2#461]
i'm trying to use the awesome library in my vue.js app, but i cannot help myself find a way to import it.

i installed it with:
`npm install fingerprintjs2`

then i tried to use:

```
import * as Fingerprint2 from 'fingerprintjs2'
Vue.use(Fingerprint2)
```

but i get this error:
**Uncaught Error: 'new Fingerprint()' is deprecated, see** [https://github.com/Valve/fingerprintjs2#upgrade-guide-from-182-to-200](https://github.com/Valve/fingerprintjs2#upgrade-guide-from-182-to-200)

then i try to read that link and cannot understand any line.

**Comment by jonashaag** [comment]
I don’t think we support Vue.use

**Comment by chris-aeviator** [comment]
I happen to get this running successfully in vue - will post the code lateron. The error is easy to solve by reading the github link, `fingerprint(this)` will error while `fingerprint.get(this, res => console.log(res))` will give you a fringerprint (unhashed though). Note: I've set this up as a nuxt.js plugin, and access it via `Vue.prototype.$fingerprint = […]`

**Comment by rabichawila** [comment]
> I happen to get this running successfully in vue - will post the code lateron. The error is easy to solve by reading the github link, `fingerprint(this)` will error while `fingerprint.get(this, res => console.log(res))` will give you a fringerprint (unhashed though). Note: I've set this up as a nuxt.js plugin, and access it via `Vue.prototype.$fingerprint = […]`

Great, i am waiting for the sample code.

**Comment by chris-aeviator** [comment]
@rabichawila I'm using nuxt.js here and try to sumup with little time available, feel free to ask me if it does not work out for you:

1) I put `fingerprint2.js` into `/plugins/fingersprint/script/` (can be simpler)
2) I load it not via plugins but with babel in `nuxt.config.js`
``` 
 build: {
		transpile: [
      'feathers-vuex',
      '~plugins/fingerprint/script/fingerprint2'
		],
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
    }
  },

```
3) In `/plugins/fingerprint/index.js` I define a vue prototype  to access fingerprintjs as $fingerprint

```


const Fingerprint2 = require('fingerprintjs2');

const fingerprint = {
  fingerprint : (vueInstance, endpoint, slug, isDev) => {
    const{ $axios, $route } = vueInstance
    Fingerprint2.get((components) => {
      const murmur = Fingerprint2.x64hash128(components.map((pair) => { return pair.value }).join(), 31)
      const headers = {'Content-Type': 'application/json'}
      // For testing:
      console.log('your fp: ' + murmur)
      $axios.post(`${endpoint}`, {
        fingerprint: murmur,
        slug: `${slug}/${$route.path}`,
        action: 'visited',
        created_at: new Date()
      }, {headers: headers})
      .then(response => {
        // if (isDev){
          console.log('200: Pushed fingerprint to database successfully!', response.data)
        // }
      })
      .catch(e => {
        if (isDev){
          console.log(e)
        }
      })
    })
  }
}


export default fingerprint

```
In any component I want to use I can now access the fingerprint function. This is an exemplary log function in my `/pages/index.vue`

```
    async log(msg) {
      let finger = await this.$fingerprint()

      const {Log} = this.$FeathersVuex.api
      console.log('finger', finger)
      const log = new Log ({
        msg :msg,
        thumb: finger.thumb,
        user: finger.data
      })
      log.create()
    }

``` 
** NOTE: there is more code in these snippets than neccessary to run fingerprint, I'm copy pasting my log example here, I hope it still helps you :)**

**Comment by rabichawila** [comment]
Finally got it working with ease:

// plugins/fingerprint.js

```
const Fingerprint2 = require('fingerprintjs2');
 
export default ({app}, inject) => {
    inject('fingerPrint2', Fingerprint2);
}
```
// nuxt.config.js

```
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
    { src : "~/plugins/fingerprint", ssr: false },
],
```

In component

```
    mounted(){

        let vue = this
        this.$fingerPrint2.get({
                    canvas: true,
                    ie_activex: true,
                    screen_resolution: true
        }, function(components){
            var values = components.map(function (component) { return component.value })
            var murmur = vue.$fingerPrint2.x64hash128(values.join(''), 31)

            console.log(murmur);
            //you can update your data var
           // this.token = murmur
            
        });

    }

```

**Comment by cybergrom** [comment]
installed it:
```javascript
npm install fingerprintjs2
```

in main.js:
```javascript
import * as Fingerprint2 from 'fingerprintjs2'
Vue.prototype.$fingerprint = Fingerprint2;
```
in components

```javascript
data() {
        return {
                finger: ''
        }
},
created() {
        this.$fingerprint.get((components) => {
                this.finger = this.$fingerprint.x64hash128(components.map((pair) => { return pair.value }).join(), 31)
                console.log(this.finger)
        });
}
```

**Comment by SwapnilSoni1999** [comment]
@cybergrom loads of thanks <3

**Comment by Gilbert-dotcom** [comment]
How can i read fingerprint in quasar app using vue 2?
