### ISSUE TITLE
Audio fingerprint timed out

### ISSUE THREAD

**Issue by ngoyal16** [Valve/fingerprintjs2#468]
Audio fingerprint timed out

Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-J200G Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.5 Chrome/38.0.2125.102 Mobile Safari/537.36

**Comment by camilosw** [comment]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1

**Comment by Valve** [comment]
It happens, increase the timeout here https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L235
to 3000
