### ISSUE TITLE
How can I add self-filed

### ISSUE THREAD

**Issue by 0c0c0f** [Valve/fingerprintjs2#470]
### Scenario

Add self-filed webdriver
    var webdriver = function (done, options) {
        done(navigator.webdriver == null ? options.NOT_AVAILABLE : navigator.webdriver)
    }
    var components = [
        {key: 'webdriver', getData: webdriver},

### Fingerprint data

when tested by changing useragent ,the finger is not ringht.

how can i add self-filed on fp2?

![image](https://user-images.githubusercontent.com/34776076/60067774-895f4700-973e-11e9-92e9-9bd6d0d13032.png)
![image](https://user-images.githubusercontent.com/34776076/60067778-90865500-973e-11e9-9b86-eaf959b0cf73.png)

**Comment by jonashaag** [comment]
Sorry please take a few minutes to write a proper question or bug report with more details and proper English sentences. Going to close this; feel free to open new bug report.
