### ISSUE TITLE
Add private field on fp2

### ISSUE THREAD

**Issue by 0c0c0f** [Valve/fingerprintjs2#471]
### Scenario
I want fp2 collection more fileds，the below webdriver field is add by me。

var components = [
        {key: 'webdriver', getData: webdriver},
        {key: 'userAgent', getData: UserAgent},
        {key: 'webdriver', getData: webdriver},
        {key: 'language', getData: languageKey},
        {key: 'colorDepth', getData: colorDepthKey},
        {key: 'deviceMemory', getData: deviceMemoryKey},
        {key: 'pixelRatio', getData: pixelRatioKey},
        {key: 'hardwareConcurrency', getData: hardwareConcurrencyKey},
        {key: 'screenResolution', getData: screenResolutionKey},
        {key: 'availableScreenResolution', getData: availableScreenResolutionKey},
        {key: 'timezoneOffset', getData: timezoneOffset},
        {key: 'timezone', getData: timezone},
        {key: 'sessionStorage', getData: sessionStorageKey},
        {key: 'localStorage', getData: localStorageKey},
        {key: 'indexedDb', getData: indexedDbKey},
        {key: 'addBehavior', getData: addBehaviorKey},
        {key: 'openDatabase', getData: openDatabaseKey},
        {key: 'cpuClass', getData: cpuClassKey},
        {key: 'platform', getData: platformKey},
        {key: 'doNotTrack', getData: doNotTrackKey},
        {key: 'plugins', getData: pluginsComponent},
        {key: 'canvas', getData: canvasKey},
        {key: 'webgl', getData: webglKey},
        {key: 'webglVendorAndRenderer', getData: webglVendorAndRendererKey},
        {key: 'adBlock', getData: adBlockKey},
        {key: 'hasLiedLanguages', getData: hasLiedLanguagesKey},
        {key: 'hasLiedResolution', getData: hasLiedResolutionKey},
        {key: 'hasLiedOs', getData: hasLiedOsKey},
        {key: 'hasLiedBrowser', getData: hasLiedBrowserKey},
        {key: 'touchSupport', getData: touchSupportKey},
        {key: 'fonts', getData: jsFontsKey, pauseBefore: true},
        {key: 'fontsFlash', getData: flashFontsKey, pauseBefore: true},
        {key: 'audio', getData: audioKey},
        {key: 'enumerateDevices', getData: enumerateDevicesKey}
    ]

### Fingerprint data

After add webdriver filed，the finger  can easy bypass through change useragent below。

![image](https://user-images.githubusercontent.com/34776076/60104005-2ea40a80-9793-11e9-9eac-097d0e5d811b.png)
![image](https://user-images.githubusercontent.com/34776076/60104017-3499eb80-9793-11e9-96e1-5c429a073e61.png)

**Comment by jonashaag** [comment]
Sorry unless you're going to write complete English sentences and give more details we cannot work on your ticket.

If anyone understands what this person is saying please feel free to tell.
