### ISSUE TITLE
Not working on latest FF

### ISSUE THREAD

**Issue by santaclaus21** [Valve/fingerprintjs2#473]
### Scenario
hash getted by fingerprint 2.1 and latest FF is always different.
It is working fine on Chrome 75.
Device - PC, Win10. 

even "click here to generate...." on https://fingerprintjs.com/ gives always new device fingerprint on every new open FF.

**Comment by Valve** [comment]
@santaclaus21 can you please provide which component is different for you each time?

**Comment by santaclaus21** [comment]
It is very interesting... but problem sometimes exist and sometimes not. I cannot expain that...
