### ISSUE TITLE
fingerprintjs2 + TOR = false positive

### ISSUE THREAD

**Issue by member777** [Valve/fingerprintjs2#476]
Hi! In TOR (onion), fingerprintjs2 has a lot of false positive detection. The biggest part of TOR users are detecting now as multiple (same users). I have tried 7 devices (fully different) and 5 of them detected as same (false positive).
I think, it's because of WebGL disabling  - https://www.bleepingcomputer.com/news/software/tor-browser-851-released-with-webgl-fingerprinting-fix/
Problem exists from in Tor Browser >8.5.1

1. Maybe to correct this?
2. Or to turn off tor (onion) at all. I mean to add Tor Browser to exeptions at all.

Because of this false positive detections, is hard to know, where is real fingerprintjs2 detection and where is false positive.

**Comment by fartwhif** [comment]
maybe you should talk to the Chicoms.

**Comment by Valve** [comment]
I'm afraid, that's outside of the scope of this library. If you don't want to run it in Tor browsers, please disable it for Tor. Getting into tug-of-war with Tor project developers is outside of this library scope and ambitions.
