### ISSUE TITLE
Fingerprintjs2 help

### ISSUE THREAD

**Issue by jiyanmizah** [Valve/fingerprintjs2#477]
the code doesn't work like this for me to work this way

how do I run code like below

 <script src="fingerprint2.js"></script>
  <h1>Fingerprintjs2</h1>
  <script>
     Fingerprint2.get(function(components) {
     var murmur = Fingerprint2.x64hash128(components.map(function (pair) { return pair.value }).join(), 31)
    })
	document.write(murmur);
  </script>

**Comment by Valve** [comment]
@jiyanmizah unfortunately we don't provide programming help in issues. Please use websites like stackoverflow for this purpose. Please only report bugs and suggest feature requests using GitHub issues.
