### ISSUE TITLE
Question: Where to get more info about the components?

### ISSUE THREAD

**Issue by d3r3kr0b3rts** [Valve/fingerprintjs2#479]
This is really great! I like having everything in a single array, it's very easy to use even for someone who's not very familiar with js.

Where can I find more information about the components? For example what is hardwareConcurrecy or indexedDb? I assume the "haslied" components are all detection measures for spoofing? Is there a single resource where I can read about all of the components or should I just search the web for them individually?

Thanks for the great work.

**Comment by jonashaag** [comment]
Use the source, Luke!

Really that’s the best documentation. There’s also a list of components in the readme.
