### ISSUE TITLE
deprecation notice for new install of latest version 

### ISSUE THREAD

**Issue by RadBoris** [Valve/fingerprintjs2#480]
### Scenario

- What's the scenario, what happens and what did you expect to happen? 
New install of the latest version on a hapi server. The deprecation notice asks for upgrade:

{ AssertionError [ERR_ASSERTION]: Invalid plugin options {
  "plugin" [1]: function (options) {\n    throw new Error(\"'new Fingerprint()' is deprecated, see https://github.com/Valve/fingerprintjs2#upgrade-guide-from-182-to-200\")\n  }
}

- What device and browser are you using? 
MacBook Mojave v 10.14.6; Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

Model Name:	MacBook Air
  Model Identifier:	MacBookAir6,2
  Processor Name:	Intel Core i7
  Processor Speed:	1.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  Boot ROM Version:	117.0.0.0.0
  SMC Version (system):	2.13f15

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)

2.1.0

### Fingerprint data
Cannot run the code; no fingerprint data

If applicable, provide the FULL DATA of all fingerprints involved using this jsfiddle https://jsfiddle.net/L2gLq4rg/85/.
Alternatively, provide a jsfiddle that reproduces the bug.

**Comment by jonashaag** [comment]
And, did you read the upgrade guide?

**Comment by RadBoris** [comment]
I certainly read the upgrade guide -- the question is what is there to upgrade if I am using the latest version???

Are you referring to the three sentences that describe upgrading from 1.8? How is that relevant in my case?
