### ISSUE TITLE
Anticipated issues due to WebKit Tracking Prevention Policy?

### ISSUE THREAD

**Issue by lightstrike** [Valve/fingerprintjs2#482]
Are there any anticipated issues with using this library given WebKit's recently published [tracking prevention policy](https://webkit.org/tracking-prevention-policy/)?

**Comment by Valve** [comment]
ITP is mostly about cookie lifetimes, link decoration and local storage.
AFAIK, ITP isn't concerned about fingerprinting, at least not yet. Their main focus is tracking domain classification and severe cookie lifetime limitations.
Closing this, please feel free to reopen with additional questions/commetns @lightstrike
