### ISSUE TITLE
RequireJS error : Mismatched anonymous define() module. and solution

### ISSUE THREAD

**Issue by superzhangzl** [Valve/fingerprintjs2#488]
using requirejs , i got this error.

`require.min.js:76 Uncaught Error: Mismatched anonymous define() module:`

requirejs version: 2.5.3

this is a demo page
```html
<!DOCTYPE html>
<html>

<head>
  <script src="./lib/require.min.js"></script>
  <script src="./lib/fingerprint2.js"></script>
</head>

<body>
  <h1>TEST</h1>
</body>

</html>
```
i find a solution from stackoverflow.
[sulation](https://stackoverflow.com/questions/15371918/mismatched-anonymous-define-module)

i changed two place
![6](https://user-images.githubusercontent.com/19573210/66828317-4cd08900-ef83-11e9-943e-1ad279ff8402.jpg)

nice ! it work

**Comment by jonashaag** [comment]
Is this something we should fix in fpjs? If so, how?

**Comment by superzhangzl** [comment]
modify thie [line](https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L21), just like picture above. add two underline before "define".
but I did not perform a comprehensive test

**Comment by jonashaag** [comment]
Closing then, if someone has more insight into what’s going on here please open PR with fix and explanation
