### ISSUE TITLE
iOS 13 CNA change my fingerprint after Facebook login (hasLiedOs)

### ISSUE THREAD

**Issue by m-lancieri** [Valve/fingerprintjs2#489]
### Scenario

- What causes the fingerprint to change?
This is my fingerprint config:
`                var FPOptions = {
                    excludes: { localStorage: true, enumerateDevices: true, canvas: true, hasLiedOs: true, webdriver: true}
                }`

I have a page that opens in the CNA of iOS 13 when I connect to a WiFi network

On the same page I also configured the facebook sdk with a like button. When I touch the button I get redirected to the facebook login and then sent back to my site.
When I go back to my site I find the "hasLiedOs" fingerprint, although it is disabled

If in the configuration I leave "hasLiedOs" it changes anyway before and after the login

- What device and browser are you using?
iOS 13 CNA on iPhone XR

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)
2.1.0

### Fingerprint data

Before Facebook login

> [{"key":"userAgent","value":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"},{"key":"language","value":"it-IT"},{"key":"colorDepth","value":32},{"key":"deviceMemory","value":"not available"},{"key":"pixelRatio","value":3},{"key":"hardwareConcurrency","value":"not available"},{"key":"screenResolution","value":[812,375]},{"key":"availableScreenResolution","value":[812,375]},{"key":"timezoneOffset","value":-120},{"key":"timezone","value":"Europe/Rome"},{"key":"sessionStorage","value":true},{"key":"indexedDb","value":true},{"key":"addBehavior","value":false},{"key":"openDatabase","value":false},{"key":"cpuClass","value":"not available"},{"key":"platform","value":"iPhone"},{"key":"doNotTrack","value":"not available"},{"key":"plugins","value":[]},{"key":"webgl","value":["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAABLKADAAQAAAABAAAAlgAAAABJS0H3AAAL80lEQVR4Ae2dTagk1RXHq96MCDFZiaISkYQoDCjowlUWU2+VRQJZhCwCZhFCFgGzyEIUXHQ3hqzEhXHhQlBcZJFF4kKyiJB+WSSKQz6YgUxgAhN9OH6BiorBzLyunPvmla+npj/q49atc8/9NTRdVX3r3nN/5/Dve0/dqs4yXhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCAQjUJZZIe9psAZpCAIQgEBXAkeCVbrPrnVwHgQgAIEgBESo5vJ2glUGaZBGkiGwk0xP6egoBES0pqM0TKMQgAAEmhBYHI2uqlEWotWEGmUgAIHgBC5L3mqFYLnp4TS4MTQIAQhAYBOBK5K/WiNYJOE3geO7RgTIYTXCRCFPBOae6qEaCEAAAv0JyAir3DDCcqMsRKs/ZmqAAAT6EnD5qwaCRT6rL2jOhwAE+hMQwZo3FCxEqz9uaoAABPoQaClYJOH7wE703DzRftPtAQiIYJUuoNyVnKaBleeNiw5gMVXGRoCrhLF5TKm9/+143yBJeKUOVWoWgqXUMbGZJYFUdLSZJzt0BMdpEIBARwL/k4S7mxK2SLq7HNbye9qxaU6DAAQg0I7A5yI+PQWLK4ftkFMaAhDoQsDlrzwJFo+j6eKAhM4hh5WQswfsauGrbpLwvkjarAfBsunX0L067bFBkvAeYVIVBCBQIyBTwtLXlHApET+tNcMuBCAAgX4EXP5qIMEiCd/PNSbPZkpo0q3hOrXovv6qiZGTJoUokw4BBCsdXw/SUwkgn/mr62wkCX8dEg5AAAJdCXwm+asBp4TVwtJpV/s4DwIQgMAhgU8kfxVIsMhnEXOHBJgSEgh9CBR9Tm557kSmh9OW51DcGAEEy5hDQ3ZHHiEzaP5qRV+caBUrjnMoEQJNH1uUCA662YbAp5K/cr941TOwlrcHDKw9eYbWbhs7KWuHACMsO74M2hOXvwra4HFjrIQ/ZpHcFoKVnMtNdJh8lgk30gkIBCIgI6y5mxIGvErorhTW39NA3aUZJQQGTDUo6SFmDELg46P81XLeank7YGDtSk5rb5BOUqk6AkwJ1blEv0Efjpe/WgVnvuogx2wSQLBs+jWpXrE+Kyl301kItCPwkeSv3JRQQQ5rOac1bdcLSsdIIGCqIUY82LyKgAjW4forNzxfzlstb48UWDPJZ01X2cwxGwSYEtrwY7BeKMtf1fvtljsU9YPs2yGAYNnxJT25SoAkvOFIQLAMO3egrk0GqtdbtTLKQrS80dRVEYKlyx9Y44cAt+/44aiuFgRLnUv0GvT+1fxQodfCayxz+azpNUfYiZ4AghW9C+nABgIk4TfAifGrka4+x4gKmz+Q3JAETOGCxv3SVe/l/WrbfWp5yVIHTeZowRKlHYywonQbRrchQBK+DS3dZREs3f5RY53LX5UyulJjUDtDSMK346W2NIKl1jUY5pkASXjPQMeoDsEag3qcbapff9UAK6LVAJLmIgiWZu9g2xAELAjvEFyiqBPBisJN4xr5dlzrr7bCIgm/FZHaAgiWWtdg2IAESMIPCHfIqhGsIekaqftkllmcRpHPijA+EawInYbJ3gggWt5QhqmIFcBhOEfdynvywL5qBbv7hVveru9X38UUWKyEjyc8GWHF46tRLD1KuI/SdqhGScKHIt2/nZh+CPv3lhpaE3hnkc135CphNXKqj6jq+1W5CANrlp/g6Q6tAyTwCZJP5QWBDQQO5Du5JyeB16T8XKa7NyJamn0d4Q+hZpz2bHvns6t/OFGNnOojqvp+VS7awCqzWX4ToqU1kqONK61ALdm1/0lW3JDJlFA6VQlRfbu+X5WLPLB286/wb9IaY5kpoUavKLHpxIHJ9VdN6Lp1Z3tNClImLAEEKyzvuFq7Epe5Hq0tyvezaX4LU0OPTL1UFfnI3QsDKllD4NK7x3+YWk316lPA+n5VzkRgLSSfdTuitSY8RjnMCGsU7Pob3d/PiizdEVbloEm5L/m7OxGtCsjYnyZ+CMeGaLH9S28e/rdf4UZQ60ZRm74zFVgH2W7+NXJaGuKcEZYGL2i0wa2/4lURmMuGKQ2uOhbbJ06IzWOB7H3rwvr7B13QVKOrdaMvg4E1y+9mahgo/NY2wwhrLZp0v9g/nxUZI6x6AEzK8zLMOoVo1cGE3EewQtKOpK3FlazYMThE8oB/Up4T0boP0fLAslMVhGUnbLZP2j+7+YbnRKeEx05fSBL+AZLwx0DCbTHCCsc6npZkhBWPsaNYShJ+FOxZhmCNBF5rsxdfFbFi/dVW95Rnsnn+YLa7tSAFvBJAsLziNFDZgtFVQy8W5Z/l9p1vks9qyMtLMQTLC0Y7lZxYZKezhZ3+DNyTSfknScKfRrQG5vxF9STdv0DBhiPwxt72+weTT7rXQ6WUJPwuSfg6liH2GWENQTXSOi++wvqrjq4r5Ly9judyWgsCCFYLWOaLuvwV08G2bp7l32JK2BZa1/IIVldyFs87kPwVr2YE3KOUv41QNYPlrxSC5Y9l/DWx/mq7D51QfReh2g5qmBII1jBco6v14u/IX210mnuY3/cQqo2MAnyJYAWAHEUTbrEo14yvd5UbUX0foboezDhHEKxxuKtrtZQ/nECvltzihOoHCNUSERWbCJYKNygw4oAV7odecFO/HyJUCiJypQkI1kosaR288LyIVer3D4pQOa/nP0KsNEc/gqXZOyFtS/mBfW7692OEKmS4dW0LwepKztB5+ZVk/zB1lv8EoYoplBGsmLw1lK3prb+a5T9FqIYKpyHrRbCGpBtB3Rd+ldD6Kzf1+xlCFUFYrjURwVqLJpEvUlh/5YTq5wiVhYhGsCx4sUcfylLWX1m94dktUXgEoeoRHupORbDUuSSwQRbzV25E9ShCFTiSgjSHYAXBrLOR80+sX39VisnRrXwXoXKk88cRK50R198qBKs/w7hrsLL+yk3/JghV3MG43XoEazsjsyVOWFh/lYtQTREqs0Fa6xiCVQOS1G7co6tZ/guEKql4lc4iWKl5/Ki/5x/LCnlCQxFdnsqNqH6JUCUatghWqo4/vNk5JrVyV/6eRKiSjdejjjPCSjUC5PlXkVwGnOVPIVSphmm93whWnUgq+/pXuM/ypxGqVMKxaT8RrKakDJU797Csv9L6l/SSo3Ko82cQK0Mh560rCJY3lBFVpPdhfbP8WYQqokgKbiqCFRz5+A0qXH81y59DqMaPDP0WIFj6feTfQi3rr9yVvxcQKv8OtlsjgmXXtyt7du4hWX8lNzyPuqLBraV6EaFa6SAObiSAYG3EY/TL8UZYs/zXCJXRqArSLQQrCGY9jeSXR3h+u5v6/Qah0hMF8VqCYMXru26Wh7xC6ITqtwhVN0dx1ioCCNYqKpaPBfjDVHmW1szlyPKXECvLoTRG3xCsMaiP1Oa576x/YJ8vk5xYnXwZofLFk3quJYBgXcvD9p67f3Col1z5u+H3CNVQeKn3KgEEK6VIcH824Z597PHlRlRf+gNC5REpVW0ggGBtgGPtq/Kyv/VXTqi+/EeEylqMaO8PgqXdQ57s+3vh5w9TFzL1u3kPofLkFqppSQDBagks1uJ9118tZInCLX9BqGL1vxW7ESwrntzWj46r293U79bXEKptePk+DAEEKwzn8Vtpuf6qlKmfy8/f8TpiNb7zsKAigGBVJAx/nrm/3forN/276x8IleGQiLZrCFa0rmtu+E7zp4vO7jqLUDUnS8nQBBCs0MRHaG/nIDu9af2Vy1N9/Z8I1QiuocmWBBCslsBiLL72+VeSp7rnXwhVjD5N1WYEy7jnz3xj5fqr2al/I1TGXW+yewiWSbcudUqeLlrtuanfvf9BqCoefEIAAsoI/O3ObP7XryJSytyCORCAwCoCZ25DrFZx4RgEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQ8Evg/XH3+LlOzzhkAAAAASUVORK5CYII=","extensions:EXT_blend_minmax;EXT_sRGB;OES_texture_float;OES_texture_float_linear;OES_texture_half_float;OES_texture_half_float_linear;OES_standard_derivatives;EXT_shader_texture_lod;EXT_texture_filter_anisotropic;OES_vertex_array_object;OES_element_index_uint;WEBGL_lose_context;WEBKIT_WEBGL_compressed_texture_pvrtc;WEBGL_depth_texture;ANGLE_instanced_arrays;WEBGL_debug_renderer_info","webgl aliased line width range:[1, 16]","webgl aliased point size range:[1, 511]","webgl alpha bits:8","webgl antialiasing:yes","webgl blue bits:8","webgl depth bits:24","webgl green bits:8","webgl max anisotropy:16","webgl max combined texture image units:8","webgl max cube map texture size:4096","webgl max fragment uniform vectors:64","webgl max render buffer size:4096","webgl max texture image units:8","webgl max texture size:4096","webgl max varying vectors:8","webgl max vertex attribs:16","webgl max vertex texture image units:8","webgl max vertex uniform vectors:128","webgl max viewport dims:[4096, 4096]","webgl red bits:8","webgl renderer:WebKit WebGL","webgl shading language version:WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)","webgl stencil bits:0","webgl vendor:WebKit","webgl version:WebGL 1.0","webgl unmasked vendor:Apple Inc.","webgl unmasked renderer:Apple GPU","webgl vertex shader high float precision:23","webgl vertex shader high float precision rangeMin:127","webgl vertex shader high float precision rangeMax:127","webgl vertex shader medium float precision:23","webgl vertex shader medium float precision rangeMin:127","webgl vertex shader medium float precision rangeMax:127","webgl vertex shader low float precision:23","webgl vertex shader low float precision rangeMin:127","webgl vertex shader low float precision rangeMax:127","webgl fragment shader high float precision:23","webgl fragment shader high float precision rangeMin:127","webgl fragment shader high float precision rangeMax:127","webgl fragment shader medium float precision:23","webgl fragment shader medium float precision rangeMin:127","webgl fragment shader medium float precision rangeMax:127","webgl fragment shader low float precision:23","webgl fragment shader low float precision rangeMin:127","webgl fragment shader low float precision rangeMax:127","webgl vertex shader high int precision:0","webgl vertex shader high int precision rangeMin:31","webgl vertex shader high int precision rangeMax:30","webgl vertex shader medium int precision:0","webgl vertex shader medium int precision rangeMin:31","webgl vertex shader medium int precision rangeMax:30","webgl vertex shader low int precision:0","webgl vertex shader low int precision rangeMin:31","webgl vertex shader low int precision rangeMax:30","webgl fragment shader high int precision:0","webgl fragment shader high int precision rangeMin:31","webgl fragment shader high int precision rangeMax:30","webgl fragment shader medium int precision:0","webgl fragment shader medium int precision rangeMin:31","webgl fragment shader medium int precision rangeMax:30","webgl fragment shader low int precision:0","webgl fragment shader low int precision rangeMin:31","webgl fragment shader low int precision rangeMax:30"]},{"key":"webglVendorAndRenderer","value":"Apple Inc.~Apple GPU"},{"key":"adBlock","value":false},{"key":"hasLiedLanguages","value":false},{"key":"hasLiedResolution","value":false},{"key":"hasLiedBrowser","value":false},{"key":"touchSupport","value":[5,true,true]},{"key":"fonts","value":["Arial","Arial Hebrew","Arial Rounded MT Bold","Courier","Courier New","Georgia","Helvetica","Helvetica Neue","Palatino","Times","Times New Roman","Trebuchet MS","Verdana"]},{"key":"fontsFlash","value":"swf object not loaded"},{"key":"audio","value":"35.10893253237009"}]

After Facebook login

> [{"key":"userAgent","value":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"},{"key":"language","value":"it-IT"},{"key":"colorDepth","value":32},{"key":"deviceMemory","value":"not available"},{"key":"pixelRatio","value":3},{"key":"hardwareConcurrency","value":"not available"},{"key":"screenResolution","value":[812,375]},{"key":"availableScreenResolution","value":[812,375]},{"key":"timezoneOffset","value":-120},{"key":"timezone","value":"Europe/Rome"},{"key":"sessionStorage","value":true},{"key":"indexedDb","value":true},{"key":"addBehavior","value":false},{"key":"openDatabase","value":false},{"key":"cpuClass","value":"not available"},{"key":"platform","value":"iPhone"},{"key":"doNotTrack","value":"not available"},{"key":"plugins","value":[]},{"key":"webgl","value":["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAABLKADAAQAAAABAAAAlgAAAABJS0H3AAAL80lEQVR4Ae2dTagk1RXHq96MCDFZiaISkYQoDCjowlUWU2+VRQJZhCwCZhFCFgGzyEIUXHQ3hqzEhXHhQlBcZJFF4kKyiJB+WSSKQz6YgUxgAhN9OH6BiorBzLyunPvmla+npj/q49atc8/9NTRdVX3r3nN/5/Dve0/dqs4yXhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCAQjUJZZIe9psAZpCAIQgEBXAkeCVbrPrnVwHgQgAIEgBESo5vJ2glUGaZBGkiGwk0xP6egoBES0pqM0TKMQgAAEmhBYHI2uqlEWotWEGmUgAIHgBC5L3mqFYLnp4TS4MTQIAQhAYBOBK5K/WiNYJOE3geO7RgTIYTXCRCFPBOae6qEaCEAAAv0JyAir3DDCcqMsRKs/ZmqAAAT6EnD5qwaCRT6rL2jOhwAE+hMQwZo3FCxEqz9uaoAABPoQaClYJOH7wE703DzRftPtAQiIYJUuoNyVnKaBleeNiw5gMVXGRoCrhLF5TKm9/+143yBJeKUOVWoWgqXUMbGZJYFUdLSZJzt0BMdpEIBARwL/k4S7mxK2SLq7HNbye9qxaU6DAAQg0I7A5yI+PQWLK4ftkFMaAhDoQsDlrzwJFo+j6eKAhM4hh5WQswfsauGrbpLwvkjarAfBsunX0L067bFBkvAeYVIVBCBQIyBTwtLXlHApET+tNcMuBCAAgX4EXP5qIMEiCd/PNSbPZkpo0q3hOrXovv6qiZGTJoUokw4BBCsdXw/SUwkgn/mr62wkCX8dEg5AAAJdCXwm+asBp4TVwtJpV/s4DwIQgMAhgU8kfxVIsMhnEXOHBJgSEgh9CBR9Tm557kSmh9OW51DcGAEEy5hDQ3ZHHiEzaP5qRV+caBUrjnMoEQJNH1uUCA662YbAp5K/cr941TOwlrcHDKw9eYbWbhs7KWuHACMsO74M2hOXvwra4HFjrIQ/ZpHcFoKVnMtNdJh8lgk30gkIBCIgI6y5mxIGvErorhTW39NA3aUZJQQGTDUo6SFmDELg46P81XLeank7YGDtSk5rb5BOUqk6AkwJ1blEv0Efjpe/WgVnvuogx2wSQLBs+jWpXrE+Kyl301kItCPwkeSv3JRQQQ5rOac1bdcLSsdIIGCqIUY82LyKgAjW4forNzxfzlstb48UWDPJZ01X2cwxGwSYEtrwY7BeKMtf1fvtljsU9YPs2yGAYNnxJT25SoAkvOFIQLAMO3egrk0GqtdbtTLKQrS80dRVEYKlyx9Y44cAt+/44aiuFgRLnUv0GvT+1fxQodfCayxz+azpNUfYiZ4AghW9C+nABgIk4TfAifGrka4+x4gKmz+Q3JAETOGCxv3SVe/l/WrbfWp5yVIHTeZowRKlHYywonQbRrchQBK+DS3dZREs3f5RY53LX5UyulJjUDtDSMK346W2NIKl1jUY5pkASXjPQMeoDsEag3qcbapff9UAK6LVAJLmIgiWZu9g2xAELAjvEFyiqBPBisJN4xr5dlzrr7bCIgm/FZHaAgiWWtdg2IAESMIPCHfIqhGsIekaqftkllmcRpHPijA+EawInYbJ3gggWt5QhqmIFcBhOEfdynvywL5qBbv7hVveru9X38UUWKyEjyc8GWHF46tRLD1KuI/SdqhGScKHIt2/nZh+CPv3lhpaE3hnkc135CphNXKqj6jq+1W5CANrlp/g6Q6tAyTwCZJP5QWBDQQO5Du5JyeB16T8XKa7NyJamn0d4Q+hZpz2bHvns6t/OFGNnOojqvp+VS7awCqzWX4ToqU1kqONK61ALdm1/0lW3JDJlFA6VQlRfbu+X5WLPLB286/wb9IaY5kpoUavKLHpxIHJ9VdN6Lp1Z3tNClImLAEEKyzvuFq7Epe5Hq0tyvezaX4LU0OPTL1UFfnI3QsDKllD4NK7x3+YWk316lPA+n5VzkRgLSSfdTuitSY8RjnMCGsU7Pob3d/PiizdEVbloEm5L/m7OxGtCsjYnyZ+CMeGaLH9S28e/rdf4UZQ60ZRm74zFVgH2W7+NXJaGuKcEZYGL2i0wa2/4lURmMuGKQ2uOhbbJ06IzWOB7H3rwvr7B13QVKOrdaMvg4E1y+9mahgo/NY2wwhrLZp0v9g/nxUZI6x6AEzK8zLMOoVo1cGE3EewQtKOpK3FlazYMThE8oB/Up4T0boP0fLAslMVhGUnbLZP2j+7+YbnRKeEx05fSBL+AZLwx0DCbTHCCsc6npZkhBWPsaNYShJ+FOxZhmCNBF5rsxdfFbFi/dVW95Rnsnn+YLa7tSAFvBJAsLziNFDZgtFVQy8W5Z/l9p1vks9qyMtLMQTLC0Y7lZxYZKezhZ3+DNyTSfknScKfRrQG5vxF9STdv0DBhiPwxt72+weTT7rXQ6WUJPwuSfg6liH2GWENQTXSOi++wvqrjq4r5Ly9judyWgsCCFYLWOaLuvwV08G2bp7l32JK2BZa1/IIVldyFs87kPwVr2YE3KOUv41QNYPlrxSC5Y9l/DWx/mq7D51QfReh2g5qmBII1jBco6v14u/IX210mnuY3/cQqo2MAnyJYAWAHEUTbrEo14yvd5UbUX0foboezDhHEKxxuKtrtZQ/nECvltzihOoHCNUSERWbCJYKNygw4oAV7odecFO/HyJUCiJypQkI1kosaR288LyIVer3D4pQOa/nP0KsNEc/gqXZOyFtS/mBfW7692OEKmS4dW0LwepKztB5+ZVk/zB1lv8EoYoplBGsmLw1lK3prb+a5T9FqIYKpyHrRbCGpBtB3Rd+ldD6Kzf1+xlCFUFYrjURwVqLJpEvUlh/5YTq5wiVhYhGsCx4sUcfylLWX1m94dktUXgEoeoRHupORbDUuSSwQRbzV25E9ShCFTiSgjSHYAXBrLOR80+sX39VisnRrXwXoXKk88cRK50R198qBKs/w7hrsLL+yk3/JghV3MG43XoEazsjsyVOWFh/lYtQTREqs0Fa6xiCVQOS1G7co6tZ/guEKql4lc4iWKl5/Ki/5x/LCnlCQxFdnsqNqH6JUCUatghWqo4/vNk5JrVyV/6eRKiSjdejjjPCSjUC5PlXkVwGnOVPIVSphmm93whWnUgq+/pXuM/ypxGqVMKxaT8RrKakDJU797Csv9L6l/SSo3Ko82cQK0Mh560rCJY3lBFVpPdhfbP8WYQqokgKbiqCFRz5+A0qXH81y59DqMaPDP0WIFj6feTfQi3rr9yVvxcQKv8OtlsjgmXXtyt7du4hWX8lNzyPuqLBraV6EaFa6SAObiSAYG3EY/TL8UZYs/zXCJXRqArSLQQrCGY9jeSXR3h+u5v6/Qah0hMF8VqCYMXru26Wh7xC6ITqtwhVN0dx1ioCCNYqKpaPBfjDVHmW1szlyPKXECvLoTRG3xCsMaiP1Oa576x/YJ8vk5xYnXwZofLFk3quJYBgXcvD9p67f3Col1z5u+H3CNVQeKn3KgEEK6VIcH824Z597PHlRlRf+gNC5REpVW0ggGBtgGPtq/Kyv/VXTqi+/EeEylqMaO8PgqXdQ57s+3vh5w9TFzL1u3kPofLkFqppSQDBagks1uJ9118tZInCLX9BqGL1vxW7ESwrntzWj46r293U79bXEKptePk+DAEEKwzn8Vtpuf6qlKmfy8/f8TpiNb7zsKAigGBVJAx/nrm/3forN/276x8IleGQiLZrCFa0rmtu+E7zp4vO7jqLUDUnS8nQBBCs0MRHaG/nIDu9af2Vy1N9/Z8I1QiuocmWBBCslsBiLL72+VeSp7rnXwhVjD5N1WYEy7jnz3xj5fqr2al/I1TGXW+yewiWSbcudUqeLlrtuanfvf9BqCoefEIAAsoI/O3ObP7XryJSytyCORCAwCoCZ25DrFZx4RgEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQ8Evg/XH3+LlOzzhkAAAAASUVORK5CYII=","extensions:EXT_blend_minmax;EXT_sRGB;OES_texture_float;OES_texture_float_linear;OES_texture_half_float;OES_texture_half_float_linear;OES_standard_derivatives;EXT_shader_texture_lod;EXT_texture_filter_anisotropic;OES_vertex_array_object;OES_element_index_uint;WEBGL_lose_context;WEBKIT_WEBGL_compressed_texture_pvrtc;WEBGL_depth_texture;ANGLE_instanced_arrays;WEBGL_debug_renderer_info","webgl aliased line width range:[1, 16]","webgl aliased point size range:[1, 511]","webgl alpha bits:8","webgl antialiasing:yes","webgl blue bits:8","webgl depth bits:24","webgl green bits:8","webgl max anisotropy:16","webgl max combined texture image units:8","webgl max cube map texture size:4096","webgl max fragment uniform vectors:64","webgl max render buffer size:4096","webgl max texture image units:8","webgl max texture size:4096","webgl max varying vectors:8","webgl max vertex attribs:16","webgl max vertex texture image units:8","webgl max vertex uniform vectors:128","webgl max viewport dims:[4096, 4096]","webgl red bits:8","webgl renderer:WebKit WebGL","webgl shading language version:WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)","webgl stencil bits:0","webgl vendor:WebKit","webgl version:WebGL 1.0","webgl unmasked vendor:Apple Inc.","webgl unmasked renderer:Apple GPU","webgl vertex shader high float precision:23","webgl vertex shader high float precision rangeMin:127","webgl vertex shader high float precision rangeMax:127","webgl vertex shader medium float precision:23","webgl vertex shader medium float precision rangeMin:127","webgl vertex shader medium float precision rangeMax:127","webgl vertex shader low float precision:23","webgl vertex shader low float precision rangeMin:127","webgl vertex shader low float precision rangeMax:127","webgl fragment shader high float precision:23","webgl fragment shader high float precision rangeMin:127","webgl fragment shader high float precision rangeMax:127","webgl fragment shader medium float precision:23","webgl fragment shader medium float precision rangeMin:127","webgl fragment shader medium float precision rangeMax:127","webgl fragment shader low float precision:23","webgl fragment shader low float precision rangeMin:127","webgl fragment shader low float precision rangeMax:127","webgl vertex shader high int precision:0","webgl vertex shader high int precision rangeMin:31","webgl vertex shader high int precision rangeMax:30","webgl vertex shader medium int precision:0","webgl vertex shader medium int precision rangeMin:31","webgl vertex shader medium int precision rangeMax:30","webgl vertex shader low int precision:0","webgl vertex shader low int precision rangeMin:31","webgl vertex shader low int precision rangeMax:30","webgl fragment shader high int precision:0","webgl fragment shader high int precision rangeMin:31","webgl fragment shader high int precision rangeMax:30","webgl fragment shader medium int precision:0","webgl fragment shader medium int precision rangeMin:31","webgl fragment shader medium int precision rangeMax:30","webgl fragment shader low int precision:0","webgl fragment shader low int precision rangeMin:31","webgl fragment shader low int precision rangeMax:30"]},{"key":"webglVendorAndRenderer","value":"Apple Inc.~Apple GPU"},{"key":"adBlock","value":false},{"key":"hasLiedLanguages","value":false},{"key":"hasLiedResolution","value":false},{"key":"hasLiedOs","value":true},{"key":"hasLiedBrowser","value":false},{"key":"touchSupport","value":[5,true,true]},{"key":"fonts","value":["Arial","Arial Hebrew","Arial Rounded MT Bold","Courier","Courier New","Georgia","Helvetica","Helvetica Neue","Palatino","Times","Times New Roman","Trebuchet MS","Verdana"]},{"key":"fontsFlash","value":"swf object not loaded"},{"key":"audio","value":"35.10893253237009"}]

**Comment by Valve** [comment]
thanks @m-lancieri , we'll need to port the hasLied* rules from the pro version, they're more accurate there.

**Comment by m-lancieri** [comment]
When will the correction be available?
Thanks

**Comment by Valve** [comment]
@m-lancieri I don't know. I currently don't have time to work on the open-source version, a pull request would be welcome!

**Comment by Valve** [comment]
@m-lancieri we just merged several fixes into master, can you please re-test it?
It's not released to NPM yet, but we'll release it if your tests are successful

**Comment by Valve** [comment]
Closing as CNA is outside the scope of this library, since not a real browser people would use.
