### ISSUE TITLE
How to verify the ID

### ISSUE THREAD

**Issue by loveunique** [Valve/fingerprintjs2#490]
I get a ID from fingerprintjs2 and I want to verify it , but I don't know how to verify it? Can you help me? Thank you!!

**Comment by jonashaag** [comment]
What does it mean to verify?

**Comment by loveunique** [comment]
If someone want to attack our system and send a lot of ids which were not genated by fingerprintjs2, how can I to know that ids that I received were vaild

**Comment by jonashaag** [comment]
You can not.
