### ISSUE TITLE
hasLiedOs meta issue

### ISSUE THREAD

**Issue by jonashaag** [Valve/fingerprintjs2#497]
Tracking all hasLiedOs issues.

#489
#495
#396
#494
#493
#396
#496

**Comment by jonashaag** [comment]
@mads1980 if you have time to work on a fix I'm very happy to review and assist.

**Comment by mads1980** [comment]
Hi @jonashaag we'll gladly patch based on our findings. Please indicate procedure to contribute. Do we need commit privileges?

**Comment by jonashaag** [comment]
Great!

Simply fork the repo, make the changes, and send a pull request.

**Comment by mads1980** [comment]
Done! Please check the following PR:
https://github.com/Valve/fingerprintjs2/pull/499

**Comment by Valve** [comment]
@jonashaag I will probably only be able to review it next week, but please don't merge yet, I'll definitely review it.

**Comment by Valve** [comment]
closing as all but one are resolved.
