### ISSUE TITLE
Changing Fingerprints in FireFox Using React Serve

### ISSUE THREAD

**Issue by lloy0076** [Valve/fingerprintjs2#498]
### Scenario

- What causes the fingerprint to change?

Run this under `react-scripts start`:

* https://github.com/lloy0076/fingerprint-test

I used [release 1.1.0](https://github.com/lloy0076/fingerprint-test/releases/tag/1.1.0).

You can also do `yarn run build` and `serve -s build` if you have `serve` version 11.2.0.

- What device and browser are you using?

Windows 10 with FireFox 70.0.1 (64 Bit).

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)

`"fingerprintjs2": "^2.1.0",`

```
fingerprintjs2@^2.1.0:
  version "2.1.0"
  resolved "https://registry.yarnpkg.com/fingerprintjs2/-/fingerprintjs2-2.1.0.tgz#21dc3fee27d3b199056ef8eb873debccd8e06323"
  integrity sha512-H1k/ESTD2rJ3liupyqWBPjZC+LKfCGixQzz/NDN4dkgbmG1bVFyMOh7luKSkVDoyfhgvRm62pviNMPI+eJTZcQ==
```

### Fingerprint data

> [{"key":"userAgent","value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"},{"key":"webdriver","value":false},{"key":"language","value":"en-US"},{"key":"colorDepth","value":24},{"key":"deviceMemory","value":"unknown"},{"key":"pixelRatio","value":1},{"key":"hardwareConcurrency","value":6},{"key":"screenResolution","value":"1920;1080"},{"key":"availableScreenResolution","value":"1920;1050"},{"key":"timezoneOffset","value":300},{"key":"timezone","value":"America/New_York"},{"key":"sessionStorage","value":1},{"key":"localStorage","value":1},{"key":"indexedDb","value":1},{"key":"cpuClass","value":"unknown"},{"key":"platform","value":"Win32"},{"key":"doNotTrack","value":"unspecified"},{"key":"plugins","value":[]},{"key":"canvas","value":"canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAgAElEQVR4nO3dcYykZ33g+Z+9dmZjvHETTwTjBdP2CDQIRvS6EwaQ0Q26W0dEt1HrNtxixEHrPFPZ8aylPpFDBhJ5khNY1uXSuwdCadBer3aAXRGdmuyxTmazoTnZO…
Fingerprint.js:59

And again:

> [{"key":"userAgent","value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"},{"key":"webdriver","value":false},{"key":"language","value":"en-US"},{"key":"colorDepth","value":24},{"key":"deviceMemory","value":"unknown"},{"key":"pixelRatio","value":1},{"key":"hardwareConcurrency","value":6},{"key":"screenResolution","value":"1920;1080"},{"key":"availableScreenResolution","value":"1920;1050"},{"key":"timezoneOffset","value":300},{"key":"timezone","value":"America/New_York"},{"key":"sessionStorage","value":1},{"key":"localStorage","value":1},{"key":"indexedDb","value":1},{"key":"cpuClass","value":"unknown"},{"key":"platform","value":"Win32"},{"key":"doNotTrack","value":"unspecified"},{"key":"plugins","value":[]},{"key":"canvas","value":"canvas winding:yes~canvas fp:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAgAElEQVR4nO3dcYykZ33g+Z+9dmZjvHETTwTjBdP2CDQIRvS6EwaQ0Q26W0dEt1HrNtxixEHrPFPZ8aylPpFDBhJ5khNY1uXSuwdCadBer3aAXRGdmuyxTmazoTnZO…
Fingerprint.js:59

What does this give?

## The BUG

On FireFox on the same machine I'll see:

* d34225c9aafa456109ef2e940e9d5b2a
* afb021c7ea341508a44d58b1d86dcc23
* 530f38dd7156811e6503668b2eb18e69

These may not relate to the above snippets and the hash changes every refresh - they are just 3 samples of different hashes. I expected them to be the same!

This happens if you use `serve -s build` from a build too.

## Does it Work on Chrome

Yes.

I can refresh as many times as I want and the hash doesn't change.

* 148d2397e9543d23164c543ee78e92bd on Chrome.

## TO NOTE

If I serve this under Apache from a `yarn run build` (I.E. I build it and then use a web server to serve it) this works as expected...

**Comment by lloy0076** [comment]
The built files:

[build.zip](https://github.com/Valve/fingerprintjs2/files/3913265/build.zip)

**Comment by jonashaag** [comment]
Thanks for the excellent and almost complete bug report! <3

Can you please post two *full* fingerprints. You are probably getting different canvas fingerprints, but it's impossible to see in the shortened version.

**Comment by lloy0076** [comment]
You're likely correct; I'll need to do that a little later tonight.On Dec 2, 2019 4:11 PM, Jonas Haag <notifications@github.com> wrote:Thanks for the excellent and almost complete bug report! <3
Can you please post two full fingerprints. You are probably getting different canvas fingerprints, but it's impossible to see in the shortened version.

**Comment by lloy0076** [comment]
They're rather, well long so I've attached as files.

[full-2.txt](https://github.com/Valve/fingerprintjs2/files/3913648/full-2.txt)
[full-1.txt](https://github.com/Valve/fingerprintjs2/files/3913649/full-1.txt)

**Comment by lloy0076** [comment]
I think it's:

> {"key":"audio","value":"35.7383295930922"},{"key":"enumerateDevices","value":"id=UBwXwG5qENJ++ZHXdfM/KUfpmLZx/aTiwmEz6LNYC0w=;gid=AG7SK3d98Tccrskzc7XjlcF80/ItqL1+KG7HMZsuwRg=;videoinput;;id=6rpZ+quTqyZaHDFWs0L4JDMyoC9QnuuJT5gS335daYU=;gid=DaxZFpEGocW2g79rZ4fCbto6FJw1BBf7d1T8su/83YE=;audioinput;;id=guL9w9oBMCwNAuBlGrUwSY7PHv6Z5F+WqMCVzdrnHUM=;gid=4RV7nHhHXoKY+ZRHmZzZOK+5HBh17nKZaUDA3JS4WXo=;audioinput;;id=1FdD+9g07W6TMJabLoan8x63p4WcOvlGjmmLx94g/X4=;gid=xxgKOsbzGdHFPmI5ys/iW8bORamdhq8j/1STlmeSCvM=;audioinput;"}

and

> {"key":"audio","value":"35.7383295930922"},{"key":"enumerateDevices","value":"id=UBwXwG5qENJ++ZHXdfM/KUfpmLZx/aTiwmEz6LNYC0w=;gid=R3M3eIVSOaqtwirzZ0c0WdM6eLjNW+oPiawiNVaLolc=;videoinput;;id=6rpZ+quTqyZaHDFWs0L4JDMyoC9QnuuJT5gS335daYU=;gid=mqkTJ+/iQjVyNOmHcHGTq5IzDxiv9R3+T1rgtBqsd+s=;audioinput;;id=guL9w9oBMCwNAuBlGrUwSY7PHv6Z5F+WqMCVzdrnHUM=;gid=K4hCR964WWxjOfs+Q5MMj1KO3KHXhrA7Z/fI/w7fCug=;audioinput;;id=1FdD+9g07W6TMJabLoan8x63p4WcOvlGjmmLx94g/X4=;gid=grZjpce7EnKy82vDHiMp+FtsUmWG2be6HnTt7B1xmHA=;audioinput;"}

The value **before** `videoInput` key is different but why would that be different under `serve` and whatever `react-scripts tart` uses...

**Comment by lloy0076** [comment]
I meddled with my tests, see:

https://github.com/lloy0076/fingerprint-test/tree/feature/is-it-enumerate-devices

Where the difference is:

```
            let excludes = {
                webgl: false,
                enumerateDevices: true,
    
            };
```

...and the package works as expected.

So I don't know if this is so much a bug as it is unexpected behaviour caused by a third party way of running things.

**Comment by lloy0076** [comment]
https://github.com/Valve/fingerprintjs2/wiki/Browser-independent-options has a `?` in the column for `enumerateDevices` - so it would seem the jury, so to speak, is out on this particular component.

**Comment by lloy0076** [comment]
Further info:

* https://gist.github.com/lloy0076/e795f9b40983992b2ab917b6d338eca7

**Comment by jonashaag** [comment]
Curious. What components are different (or not) when using the Vue (non-Vue) version?

**Comment by jkilts-netcloud** [comment]
@lloy0076 Your Vue component seems to load after 250ms regardless of the platform, whereas the documentation shows an example usage for FingerPrint2 as either 500 ms or just waiting for requestIdleCallback.  Have you tried with requestIdleCallback?

**Comment by lloy0076** [comment]
@jk-net-c See https://gist.github.com/f75646e64f478f48098c4efb920bf060

I got:

![image](https://user-images.githubusercontent.com/1174532/73122032-deba3b80-3f4d-11ea-9d85-09a440b7a3ce.png)

The hash/fingerprint changes on reload.

PS. It seems to be:

> gid=Y+FABqfJEPT2HuouxZZtTLZ304ZiFht93yxSji/ZGBw=;audioinput;;id=FN5bv3+urLfxgERZwWS2lNY9eOkcwmxd9Hi29Sl6LsQ=;gid=wRNXeoO4RQeGRwNNnOxU7LjV+HDIZfDl/BV4F+dO5As=;audioinput;"}]

Which is in the key `enumeratedDevices`.

I **confirmed** it's `enumeratedDevices` by setting the excludes for that to true.

**Comment by lloy0076** [comment]
I don't believe this is a bug with fingerprint itself; so I'm going to close it as the original opener.

Please feel free to re-open and ask me any further questions if needed.
