### ISSUE TITLE
Use something like ua-parser.js

### ISSUE THREAD

**Issue by Techmind** [Valve/fingerprintjs2#5]
Cause using navigator.userAgent is a bad idea - every browser restart can cause it to change (modern browsers(firefox/chrome/mobile) use auto-update). Thanks for your work =)

**Comment by Valve** [comment]
I agree, for now it's possible to just skip the UA in FP detection, but I leave the issue open to do a no-version stipped down UA

**Comment by jugglingcats** [comment]
+1

Chrome for example is updated three of four times a month. It would be great if there were a way to ignore the minor version number in the UA string during FP generation

**Comment by Valve** [comment]
I agree completely, it's just I want to keep this lib a no-dependencies library, so this rules out depending on ua-parser.js. Building my own UA parser seems like a long and error-prone thing to do. So I can't decide which way to go here.

**Comment by Techmind** [comment]
1) Add some sort of flag or build option to gulpfile for example, so if somebody wants better precision (everybody wants it, so this is kinda guaranteed to be always in "true" state) - he can have ua-parser built-in/integrated. 

2) Or add some sort of callback to post-process the user-agent string and add example with ua-parser.

**Comment by Valve** [comment]
@Techmind I guess you're right. Custom build is the way to go. For those who want UA parsing - they should build the lib with it.

**Comment by jugglingcats** [comment]
FWIW I think having multiple build options is overkill and might confuse your bower install. Could you detect the presence of ua-parser.js and use it if loaded? Then people can just load it before fingerprintjs. I think Techmind's option 2 is also worth doing in any case... people might have very specific requirements and want to roll their own.

**Comment by Techmind** [comment]
@Valve also some plugin detection also depends on user-agent (some plugins change UA - this matters for mobile "a lot" cause it is hard to extract features and every little bit counts =)) - so it will be significant dependency anyway.

**Comment by leeoniya** [comment]
@Valve 

Can you provide a callback that lets us parse the UA ourselves and return whatever string we want to be hashed? (as @Techmind suggested). It seems like a trivial thing to add which involves no forced dependencies, no code bloat and no maintenance overhead. It's surprising to see this issue still open and users being forced to disable UA sniffing completely when the fix is simple.

**Comment by Valve** [comment]
@leeoniya plugins or callbacks are the way to go, I agree. Creating a simple system to preprocess any FP source should solve a lot of issues. I've been working on this to go into version 2, but never finished. Will try to do over the course of the current month

**Comment by Valve** [comment]
A callback/plugin system is being worked on, so you will be able to pre/post process any FP components. Closing in favor of https://github.com/Valve/fingerprintjs2/issues/177
