### ISSUE TITLE
Dont return the unique id

### ISSUE THREAD

**Issue by rastolho** [Valve/fingerprintjs2#500]
### Scenario

when i use this part of code to take the unique id, the method dont return me the unique id:
 Fingerprint2.get(function (result, components) {
            console.log(components);
            console.log(result);
        })

### Fingerprint data
0: {key: "userAgent", value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWeb…L, like Gecko) Chrome/78.0.3904.108 Safari/537.36"}
1: {key: "webdriver", value: "not available"}
2: {key: "language", value: "en-US"}
3: {key: "colorDepth", value: 24}
4: {key: "deviceMemory", value: 8}
5: {key: "hardwareConcurrency", value: 8}
6: {key: "screenResolution", value: Array(2)}
7: {key: "availableScreenResolution", value: Array(2)}
8: {key: "timezoneOffset", value: 0}
9: {key: "timezone", value: "Europe/Lisbon"}
10: {key: "sessionStorage", value: true}
11: {key: "localStorage", value: true}
12: {key: "indexedDb", value: true}
13: {key: "addBehavior", value: false}
14: {key: "openDatabase", value: true}
15: {key: "cpuClass", value: "not available"}
16: {key: "platform", value: "Win32"}
17: {key: "plugins", value: Array(3)}
18: {key: "canvas", value: Array(2)}
19: {key: "webgl", value: Array(65)}
20: {key: "webglVendorAndRenderer", value: "Google Inc.~ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)"}
21: {key: "adBlock", value: false}
22: {key: "hasLiedLanguages", value: false}
23: {key: "hasLiedResolution", value: false}
24: {key: "hasLiedOs", value: false}
25: {key: "hasLiedBrowser", value: false}
26: {key: "touchSupport", value: Array(3)}
27: {key: "fonts", value: Array(48)}
28: {key: "audio", value: "124.04344884395687"}

**Comment by jonashaag** [comment]
Please describe in more detail what you are expecting and what happens instead

**Comment by rastolho** [comment]
I expect take the browser unique id like that: 05b5ff03c801b16b011dccdadbd5e3f9

**Comment by jonashaag** [comment]
Please provide a full non-working example JS file

**Comment by idlinnes** [comment]
```
Fingerprint2.get(components => {
     const hash = Fingerprint2.x64hash128(components.map(({ value }) => value).join(''),31)
})
```

**Comment by rastolho** [comment]
Thanks was that, i just find later
