### ISSUE TITLE
how to get the function response value?

### ISSUE THREAD

**Issue by reedinthinking** [Valve/fingerprintjs2#505]
### des
I write a function(getinfo()) to get the components and get the murmur,and then , I use the function getinfo(),but the response value is undefined.
'''sh
function getinfo(){
    var result = Fingerprint2.get(function(components) {
           ...
           return components;
    }
    return result;
}
var info = getinfo();//but the info is undefined
console.log(info);//but the info is undefined.I want get the value
'''

**Comment by reedinthinking** [comment]
how to get the function response value?

**Comment by jonashaag** [comment]
It's a callback, you can't return the value like that because it's asynchronous. See https://stackoverflow.com/questions/6847697/how-to-return-value-from-an-asynchronous-callback-function
