### ISSUE TITLE
Changing fingerprint on refresh when excluding the language

### ISSUE THREAD

**Issue by mrharindra** [Valve/fingerprintjs2#508]
### Scenario
`
var options = {excludes: {language: true};
Fingerprint2.get( options, function(components) {
			var values = components.map(function (component) { return component.value })
			          var murmur = Fingerprint2.x64hash128(values.join(''), 31)
			          console.log(murmur);
				});

`
Chrome: Version 79.0.3945.88
Windows: 10

fingerprintjs version: fingerprintjs2-2.1.0

### Fingerprint data
FULL DATA of both/all fingerprints using this jsfiddle https://jsfiddle.net/L2gLq4rg/85/.
0309f3fab95dfd79c40e37e88e64052b

jsfiddle that reproduces the bug.
https://jsfiddle.net/0b19a6ed/

**Comment by jonashaag** [comment]
Please post full fingerprints here and also have a look at what components are different

**Comment by mrharindra** [comment]
@jonashaag 
If excluding the language  'var options = {excludes: {language: true};'
These keys are added -pixelRatio, doNotTrack, fontsFlash, enumerateDevices
The value of 'enumerateDevices' are changing every time

Please see the deferences
_fingerprint1.txt_ and _fingerprint2.txt_  are generated with excluding
where as _fingerprit3_without_exclude.txt_ is created without excluding

[fingerprint1.txt](https://github.com/Valve/fingerprintjs2/files/3992533/fingerprint1.txt)
[fingerprint2.txt](https://github.com/Valve/fingerprintjs2/files/3992534/fingerprint2.txt)
[fingerprit3_without_exclude.txt](https://github.com/Valve/fingerprintjs2/files/3992535/fingerprit3_without_exclude.txt)

**Comment by jonashaag** [comment]
Yeah that’s a known issue on Windows. See other tickets with similar reports.
