### ISSUE TITLE
Fingerprint Hash value changes on Page refresh if userAgent is excluded

### ISSUE THREAD

**Issue by storesbuzz** [Valve/fingerprintjs2#509]
### Fingerprint Hash value changes on Page refresh if userAgent is excluded

- userAgent is added in excludes: {userAgent: true} field of options
- Ubuntu 19.4 and browser Chrome/79.0.3945.88
- "fingerprintjs2": "^2.1.0",

### Fingerprint data

#Case 1:
```
    var options = {
      excludes: {userAgent: true}
    }

    Fingerprint2.get(options, function (components) {
      var values = components.map(function (component) { return component.value })
      var murmur = Fingerprint2.x64hash128(values.join(''), 31);

      console.log('hash ',values, murmur);
    })
```

On each page refresh 'murmur' value changes.

#Case 2:
```
    var options = { }

    Fingerprint2.get(options, function (components) {
      var values = components.map(function (component) { return component.value })
      var murmur = Fingerprint2.x64hash128(values.join(''), 31);

      console.log('hash ',values, murmur);
    })
```
No change in 'murmur' value and thats good.

But I am excluding userAgent because I observed fingerprint changes when browser updates and Chrome updates keep on coming each month.

When tried comparing for Case 1 values before and after refresh, observed last component : 30, value changes on each refresh where I have added excludes: {userAgent: true}.

On load 

```
30: Array(5)
0: "id=default;gid=93f3f0a3e7a4d76c06bcc3df3358479eca0a3de2beeb6987054bfd834ed2113e;audioinput;"
1: "id=734d821d61fcb9e621b57854b2f200cda73449c89b72a0e61cad5528e9d7275b;gid=38ab2f69c010f02bd4fd9e27e81582520f6ec4577f5dae057c71dd8eea88c03d;audioinput;"
2: "id=7e73d0b28f168f1bb66b7687553793cccb5b78ac002a0008a00d5fab28d68ef5;gid=25f879b419127ec40d1f55f7e37a8cdf629467ea3df53cfb029774a1e300c1a8;videoinput;"
3: "id=default;gid=default;audiooutput;"
4: "id=f604fde64ee0d3c0c1981ac7515b65307c00b5ea7e3a115d04b060b578e3b4b0;gid=38ab2f69c010f02bd4fd9e27e81582520f6ec4577f5dae057c71dd8eea88c03d;audiooutput;"
length: 5
```

On Refresh

```
30: Array(5)
0: "id=default;gid=f065537c44994016d7dced11e101e92488c79ed6dcc35d2afe1fcab2225f208c;audioinput;"
1: "id=734d821d61fcb9e621b57854b2f200cda73449c89b72a0e61cad5528e9d7275b;gid=858ed64f07a010e2175d5b5ce97a19c605256113be3422c8aa2a27f31c3fb95c;audioinput;"
2: "id=7e73d0b28f168f1bb66b7687553793cccb5b78ac002a0008a00d5fab28d68ef5;gid=a01f8d182b359cc8dbf52bbfaa950f15f16235a439f415c6d0d5355f5ab728fc;videoinput;"
3: "id=default;gid=default;audiooutput;"
4: "id=f604fde64ee0d3c0c1981ac7515b65307c00b5ea7e3a115d04b060b578e3b4b0;gid=858ed64f07a010e2175d5b5ce97a19c605256113be3422c8aa2a27f31c3fb95c;audiooutput;"
length: 5
```

I am using Fingerprint for first time, Correct me if doing something wrong.

**Comment by storesbuzz** [comment]
For now, I am going for a workaround as 'preprocessor' and using - userAgentMinusVersion. Here i don't see a change in fingerprint on refresh.

```
    Fingerprint2.get({
      preprocessor: function(key, value) {
        if (key == "userAgent") {
          var parser = UAParser(value); // https://github.com/faisalman/ua-parser-js

          console.log('parser ',parser);
          var userAgentMinusVersion = parser.os.name + ' ' + parser.browser.name
          return userAgentMinusVersion
        }
        return value
      }
    }, function (components) {
      var values = components.map(function (component) { return component.value })
      var murmur = Fingerprint2.x64hash128(values.join(''), 31);

      console.log('hash ',values, murmur);
    })
```

**Comment by jonashaag** [comment]
I suspect the differences are random. Please test in the exact same browser, and multiple times. Sometimes the first fingerprint generation differs from the others.

If you can reproduce please provide  jsfiddle with the exact code that reproduces the error

**Comment by storesbuzz** [comment]
Thanks for response @jonashaag , yes I am using same browser but if I refresh 10 times it gives me 10 different fingerprints only when I have excluded userAgent.

I am using this with react 16.9 and using inside componentDidMount. Anyways now i don't a reason to remove userAgent completely as i can use preprocessor and remove the version from it.

```
  componentDidMount() {

    //  Device Fingerprint and Device details
    Fingerprint2.get({
      preprocessor: function(key, value) {
        if (key == "userAgent") {
          var parser = UAParser(value);
          var userAgentMinusVersion = parser.os.name + ' ' + parser.browser.name
          return userAgentMinusVersion
        }
        return value
      }
    }, (components) => this.props.setDeviceKey(Fingerprint2.x64hash128(components.map((component) => component.value).join(''), 31), deviceName() ));
  }
```

**Comment by jonashaag** [comment]
Depending on what you want to do with the fingerprints including any kind of user agent derived data may be a bad idea

**Comment by jonashaag** [comment]
Btw the component in your first post is enumerateDevices, this is known to be unstable sometimes, see https://github.com/Valve/fingerprintjs2/wiki/Stable-options

**Comment by storesbuzz** [comment]
I am using fingerprint to identify login from new (non-trusted) device. Can you please explain what can go wrong by including any kind of user agent derived data? Because it's a critical section of my project.

Also, your shared link is not working.

**Comment by jonashaag** [comment]
Fixed the link.

If it's critical, maybe you should pay a consultant.

Note that fingerprints can be easily faked (as can anything that is generated in the client). Maybe you should set an encrypted cookie in the browser to tell your website the browser is trusted (=> any browser without cookie is untrusted). But not sure what's your use case exactly; as I said, pay a consultant.
