### ISSUE TITLE
too improve accuracy, should I enable all of these:canvas, screen resolutin, activeX?

### ISSUE THREAD

**Issue by bylijinnan** [Valve/fingerprintjs2#51]
Thanks

**Comment by Valve** [comment]
@bylijinnan  they're all enabled by default. Available options exist to selectively disable some of those.

The only thing which is disabled by default, is Flash font enumeration, because JS fonts enumeration works better.
I'll update the readme now to reflect this.

**Comment by Valve** [comment]
https://github.com/Valve/fingerprintjs2#all-fingerprinting-sources-are-enabled-by-default-ie-you-dont-need-to-explicitly-configure-the-library-to-include-them

**Comment by mhuisman** [comment]
It depends on what you mean by 'accuracy'.  Some fingerprint keys are browser-specific and susceptible to change over time -- user agent, installed plugin list, etc.

Other fingerprint keys are device-specific and unlikely to change -- canvas key, operating system, viewport dimensions.

**Comment by NJseo** [comment]
The whole notion of a single fingerprint is flawed
