### ISSUE TITLE
getting the folllowing error

### ISSUE THREAD

**Issue by adaboina21** [Valve/fingerprintjs2#510]
[ { key: 'userAgent',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'webdriver',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'language',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'colorDepth',
    value: 'ReferenceError: window is not defined' },
  { key: 'deviceMemory',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'hardwareConcurrency',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'screenResolution',
    value: 'ReferenceError: window is not defined' },
  { key: 'availableScreenResolution',
    value: 'ReferenceError: window is not defined' },
  { key: 'timezoneOffset', value: 480 },
  { key: 'timezone',
    value: 'ReferenceError: window is not defined' },
  { key: 'sessionStorage', value: 'error' },
  { key: 'localStorage', value: 'error' },
  { key: 'indexedDb', value: 'error' },
  { key: 'addBehavior',
    value: 'ReferenceError: document is not defined' },
  { key: 'openDatabase',
    value: 'ReferenceError: window is not defined' },
  { key: 'cpuClass',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'platform',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'plugins',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'canvas',
    value: 'ReferenceError: document is not defined' },
  { key: 'webgl',
    value: 'ReferenceError: document is not defined' },
  { key: 'webglVendorAndRenderer',
    value: 'ReferenceError: document is not defined' },
  { key: 'adBlock',
    value: 'ReferenceError: document is not defined' },
  { key: 'hasLiedLanguages',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'hasLiedResolution',
    value: 'ReferenceError: window is not defined' },
  { key: 'hasLiedOs',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'hasLiedBrowser',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'touchSupport',
    value: 'ReferenceError: navigator is not defined' },
  { key: 'fonts',
    value: 'ReferenceError: document is not defined' },
  { key: 'audio',
    value: 'ReferenceError: navigator is not defined' } ]

**Comment by adaboina21** [comment]
Any solution why did you close this

**Comment by jonashaag** [comment]
Please open new issue with "Other bugs" template

**Comment by adaboina21** [comment]
i am using this in angular but still same issue

**Comment by adaboina21** [comment]
https://npm.runkit.com/device-uuid
