### ISSUE TITLE
Can you add the check browser mode function

### ISSUE THREAD

**Issue by 1174133584** [Valve/fingerprintjs2#511]
like this，Can judge **Incognito** or **Not Incognito**：
```
if ('storage' in navigator && 'estimate' in navigator.storage) {
	const {usage, quota} = await navigator.storage.estimate();
    console.log(`Using ${usage} out of ${quota} bytes.`);

	if(quota < 120000000){
        console.log('Incognito')
    } else {
        console.log('Not Incognito')
    }	
} else {
	console.log('Can not detect')
}

```

**Comment by jonashaag** [comment]
Thanks for the hint. 

Can you check and send the quota values of a handful of browsers?

**Comment by Valve** [comment]
@1174133584 thanks for your suggestion.
We'll not be adding incognito mode detection for 2 reasons.

1. The code that you suggested only works for Chrome 76+. Our library is compatible with all major browsers and we'll not be adding code that only works in a single browser (and in some versions only). Adding proper incognito mode detection for all browsers requires a lot of code and is outside of the scope of this library.

2. Fingerprint.js PRO (the professional version) has incognito mode detection already. Adding it here would dilute the difference and value proposition for the PRO.

**Comment by jonashaag** [comment]
Looks like more compatible browsers? https://caniuse.com/#search=estimate

**Comment by Valve** [comment]
sorry, I wasn't clear: this method of detecting the incognito mode with  the local storage quota is working in Chrome.

While local storage quota is available in more browsers, it's not useful for incognito detection there @jonashaag
