### ISSUE TITLE
Minimized version wrong?

### ISSUE THREAD

**Issue by Daijobou** [Valve/fingerprintjs2#54]
Only a question.

In full version
https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js
you can find the variable "NODEBUG" or the string:
this.log("Skipping flash fonts detection per excludeFlashFonts configuration option");

in minimized version
https://github.com/Valve/fingerprintjs2/blob/master/dist/fingerprint2.js
this is missing... 

is this really the minimized version of full?

**Comment by Valve** [comment]
@Daijobou it is intended this way. It's called conditional minification (https://github.com/mishoo/UglifyJS2#conditional-compilation).

The reason I did this is to not have the minified version bloated with logging messages. You can add as many logging messages as you want, but this will not affect the minified version size.

**Comment by Daijobou** [comment]
Thanks. Thats perfect. :)
