### ISSUE TITLE
very slow on FF for Android

### ISSUE THREAD

**Issue by Valve** [Valve/fingerprintjs2#59]
5-15 times slower on FF for android than on Chrome for android.
Investigate.

**Comment by flugsio** [comment]
Some minor testing, and excludeJsFonts: true fixes it in firefox on android. Also, in some other browsers it seems to be 50-75% faster by excluding this.

**Comment by Valve** [comment]
@flugsio, yes, I know that js fonts is the slowest thing there, cannot really figure out how to make it faster, except for limiting the number of detected fonts.

**Comment by Valve** [comment]
Fixed in d4e3cf4edb184b73dd31e2b4943b2680cd4762c9
