### ISSUE TITLE
Canvas bug in Safari

### ISSUE THREAD

**Issue by arakcheev** [Valve/fingerprintjs2#62]
I got two different fingerprints in my Safari 8. When I loaded [fingerprintjs2](http://valve.github.io/fingerprintjs2/) the first time the fingerprint was ```4a6fd73681de95e22d6021eddb0ea2a3```, if I clicked btn again i got ```66a9c3707479d6f532dc5959f8da0f72```.

This is diff of these two cases https://www.diffchecker.com/rw0vf5cy.
```javascript
  result.push("canvas fp:" + canvas.toDataURL());
```
If I comment ```canvas.toDataURL()```  fingerprints are identical.

**Comment by Valve** [comment]
@arakcheev, confirming the issue. I get a different FP second time I click the button, will try to fix it soon.

**Comment by Valve** [comment]
@arakcheev, fixed in https://github.com/Valve/fingerprintjs2/releases/tag/0.6.0
