### ISSUE TITLE
Safari 3 fingerprints

### ISSUE THREAD

**Issue by webhat** [Valve/fingerprintjs2#63]
I'm running Safari (Version 8.0.7 (10600.7.12)) without Flash it seems to alternate between 3 different fingerprints for the same browser in the same session.

I'm using the example code from the `README.md`:

```javascript
(function () {
  new Fingerprint2().get(function(result){
      console.log(result);
  });
})();
```

**Comment by Valve** [comment]
Duplicate of #62
