### ISSUE TITLE
Text in canvas affected by CSS(font "no-real-font-123", character"\ud83d\ude03")

### ISSUE THREAD

**Issue by gazhikaba** [Valve/fingerprintjs2#66]
When set  the font as "no-real-font-123", the canvas will paint the text as default font, is that right?
But I found the default font could be changed by CSS, and also "\ud83d\ude03" will become □□ sometimes.

Then I got different fingerprint on two page with same browser, because CSS of two page are different they got different font in canvas.

I'm not good at CSS, so I'm not find out the reason.

Is there have a remind list like "Don't do it in your CSS"?

And here is one thing that I found can't do.
If set style of span like:
```css
span  {
 //some thing
}
```
That will make jsFontsKey get nothing, because it use span to detect fonts.
Following way is OK.
```html
<style>
.style-of-span {
  //something
}
</style>
<span class='style-of-span'> Bili</span>
```

**Comment by Valve** [comment]
@gazhikaba thanks, very good observations. Will look into it.

**Comment by Valve** [comment]
@gazhikaba regarding the default font change. Do you mean that the same web page changes its default font once in a while? Why does it do that, it does not make sense to me at all, never seen this in real life.  Regarding span element css styling I cannot reproduce it.

**Comment by gazhikaba** [comment]
@Valve  We want to collect fingerprint from several site, and we don't want to change them, only add the JS library. So we need the fingerprint is same in every page.

**Comment by Valve** [comment]
@gazhikaba , got it. The only solution I can think of now is to add a special configuration option, like 'options.dontUseFakeFontInCanvas = true'. If this option is set to true, fake font will not be used, instead, I'll use the 'Arial', which is ubiquitous, so you'll get consistent results. Please let me know it it works for you and I'll implement it.

**Comment by gazhikaba** [comment]
@Valve It works, and I'm not add option, just change the font to "Arail".
Thank you.

**Comment by Valve** [comment]
@gazhikaba , I cannot change the font to Arial, because it will reduce the entropy for users that use it on one site. I'll add this option for you.

**Comment by Finesse** [comment]
> and also "\ud83d\ude03" will become □□ sometimes

The issue for this problem: https://github.com/fingerprintjs/fingerprintjs/issues/588
