### ISSUE TITLE
excludePlugins options key missing

### ISSUE THREAD

**Issue by qrzbrz** [Valve/fingerprintjs2#68]
Sometimes different fingerprints appear when plugins are taken into account. Currently almost every option can be disabled, except plugin. I could solve it by adding an "expludePlugins" option and changing pluginsKey() to the following, could you maybe merge it?
//-----
pluginsKey: function(keys) {
      if (!this.options.excludePlugins) { // only when not excluded
	      if(this.isIE()){
	        keys.push(this.getIEPluginsString());
	      } else {
	        keys.push(this.getRegularPluginsString());
	      }
      }
      return keys;
    },
//---
Thanks,
wfR ChrisA

**Comment by mhuisman** [comment]
+1

**Comment by Valve** [comment]
Guys. I'm on vacation will merge next week

**Comment by Valve** [comment]
Done, fixed in https://github.com/Valve/fingerprintjs2/releases/tag/0.7.3

**Comment by qrzbrz** [comment]
works perfect, thanks!
