### ISSUE TITLE
Default Fingerprint2() result different in two tabs in the same browser

### ISSUE THREAD

**Issue by bperry-zos** [Valve/fingerprintjs2#69]
Hi, I am trying to determine why a fingerprint generated by two different tabs in the same browser would be different.

I have a javascript heavy web app and a basic HTML page both generating a fingerprint in the same browser but different tabs. I cannot for the life of me have the tabs create the same fingerprint.

What in the current tab would dictate a different fingerprint being generated? I did not see anything that was dependent on what was currently rendered.

Any insights are appreciated. I have played with disabling various options in both to no avail.

**Comment by Valve** [comment]
Hey, @bperry-zos, I've been out of the country, will look into the issue now, thanks for reporting!

**Comment by bperry-zos** [comment]
Hi @Valve 

The browsers I have been testing in is chrome and firefox on Linux.

If I load the default sample fingerprinting page that comes with fingerprintjs2 in two different tabs, I get the same fingerprint.

If I use the javascript-heavy web app and the sample page in two different tabs in the same browser with the exact same options, I do not get the same fingerprint. It seems to be something related to the javascript-heavy web app.

**Comment by Valve** [comment]
@bperry-zos, unfortunately I need more details to diagnose the issue, you could help me with that, like commenting out the keys one by one from here: (https://github.com/Valve/fingerprintjs2/blob/88159bd4163f39937f362fcf61b53f9605efcde0/fingerprint2.js#L83-L104)

Once you figure out which key causes different results, try commenting out the code line by line from that key function. This way you'll be able to figure out what's causing your behavior and also see what data difference causes this.

**Comment by bperry-zos** [comment]
Sure thing, will take a bit, but will debug which key is causing the discrepancy. This is a step in the right direction.

**Comment by bperry-zos** [comment]
Closing for now until I have time to do more testing.

**Comment by skeep** [comment]
So I also had same problem and I found what was causing issue in my case. Documenting here incase someone else also face the same problem.

In my case I had switched on "Device Toolbar" which was causing different value for `touchSupport`. When I switched off "Device Toolbar" the fingerprint start coming correctly.
