### ISSUE TITLE
Webgl for fingerprint instead of canvas (or with canvas).

### ISSUE THREAD

**Issue by Techmind** [Valve/fingerprintjs2#7]
Didn`t have time to test if stuff like this
https://github.com/kmowery/canvas-fingerprinting.git
(https://github.com/kmowery/canvas-fingerprinting/tree/master/static/experiments/webgl-teapot)
correlates with canvas fingerprint.

Both fingerprints (canvas/webgl) produce hash for [graphic_card, current_driver_version, browser_wrapper_code] vector. So there should be some sort of  correlation, so maybe a separate option for "webgl" fingerprint should exist.

**Comment by Valve** [comment]
Thanks, will look into it.
