### ISSUE TITLE
Too many collisions

### ISSUE THREAD

**Issue by sachinahuja** [Valve/fingerprintjs2#71]
I am in the middle of rolling out fingerprinting via this lib to about a million odd users. During testing we have been seeing a lot of collisions (upwards of 15%). Interestingly these collisions are across geographies - which means that the underlying values are different (at least the language and timezone will be different). Any ideas?

**Comment by Valve** [comment]
Please give more data, an example of 2 data sets that produce a collision, to start with.

**Comment by commerce-experts** [comment]
Hi sachinahuja,
very interesting as I experienced something similar but with lower collision rates at around 8-10%. How do you determine if a collision is a "real" collision? Because in my case it turned out that quite a large ratio of these collisions where indeed the same device.

**Comment by sachinahuja** [comment]
@Valve what kind of data are you looking for ... the elements that went into the fingerprint?
@commerce-experts the way we are detecting 'real' collision is based on cookies. If a FP-cookie combo returns .. only then we mark it as a confirmed collision.

**Comment by Valve** [comment]
@sachinahuja yes, array of data before hashing

**Comment by commerce-experts** [comment]
@sachinahuja - so after my device deleated all cookies (which happens depending on the browser quite frequently) and a revisit to your site you would treat my fingerprint as a collision :-)
It is by for not so easy to reveal real collisions since there is currently no bulletproof client side persistence layer available.

**Comment by sachinahuja** [comment]
@Valve these are devices in the wild, i'll try to get some data for you later today though

@commerce-experts no, if you clear cookies and come back to the site, it will NOT be treated as a collision - we'll simply create a new cookie and treat this as the previous user. However, if the original cookie ever came back - identifying that this was not a cookie-clearing scenario, but in fact a different device that we assumed was a cookie-clear scenario -- we'll mark it as a confirmed collision.

**Comment by ErikAGriffin** [comment]
Is there a lot of collisions? I don't have the means to test this at the moment, but I'm curious as to what a general collision rate is

**Comment by Valve** [comment]
@ErikAGriffin it's actually hard to measure. To measure the true number of collisions, some unique cookie should be saved along with FP2 value to be able to measure. I had an impression that @sachinahuja had this kind of data

**Comment by Valve** [comment]
@sachinahuja did you have any progress on collecting the data?

**Comment by subbarao** [comment]
I am getting same fingerprint  for different user agents.


Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Win64; x64; Trident/7.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.3072
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729;
Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
These values are computed from server user agent.
how can this be possible?

**Comment by Valve** [comment]
>> These values are computed from server user agent.

I don't understand this part. Could you also please provide the rest of the FP components? (The latest version allows to get them in the call to `#get` method)

**Comment by subbarao** [comment]
we are tracking both fingerprint and user agent from request headers. we get same fingerprint for above 4 different browsers. how is it possible?

**Comment by subbarao** [comment]
I can not store all of them on server side.

**Comment by Valve** [comment]
4 collisions per how many fingerprints?

**Comment by Valve** [comment]
Hashing functions do have collisions, it's normal, see this SO answer: http://programmers.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed/145633#145633

The OP had 6 collisions per ~ 200K words with Murmur hash.

**Comment by subbarao** [comment]
we have multiple collisions on sample size of 4k

**Comment by subbarao** [comment]
Does user agent spoofers can cause wrong results?

**Comment by Valve** [comment]
Yes, it can, when one replaces the user agent HTTP header but keeps the navigator.userAgent
