### ISSUE TITLE
console.log(keys) returns error

### ISSUE THREAD

**Issue by graemeblackwood** [Valve/fingerprintjs2#72]
When trying to log the results of the fingerprint (Fingerprintjs2 0.7.4), I see an error in both Chrome 44.0.2 and Firefox 40.0.3:

"Uncaught ReferenceError: keys is not defined(anonymous function) @ index.html:83(anonymous function) @ fingerprint2.js:108(anonymous function) @ fingerprint2.js:389"

**Comment by Valve** [comment]
@graemeblackwood  please provide the altered source code which throws the error in a gist

**Comment by graemeblackwood** [comment]
https://gist.github.com/graemeblackwood/5db647a03dd129a98c77

It works if I put it inside the function in JS, but I can't find any documentation that shares how to print the keys in the console when initiating the plugin.

**Comment by Valve** [comment]
@graemeblackwood, ah got it. Keys are not accessible from the outside, it's meant this way. Otherwise any script can just set keys to an empty array. If you want to print the keys, you need to add the line right into the fp2.js source code

**Comment by graemeblackwood** [comment]
Ok, so my other approach (on line 105) was correct then. Was the resetting of the keys an observed problem with fp1.js?

**Comment by Valve** [comment]
It was not, but I generally don't want to expose any internal data structures to the outside world. This will make it far too easy for any browser extension to disable it.
