### ISSUE TITLE
Computer identification

### ISSUE THREAD

**Issue by icetronics** [Valve/fingerprintjs2#73]
Hi,
First of all, this is a great plugin! :)

Would there be an easy way to eliminate browser-specific checks and use Fingerprintjs2 to ID computers with a fair preciseness? I would like to use this plugin to generate the same fingerprint on a machine even opened in different browsers.

Thanks in advance!

Zsolt

**Comment by dcrockwell** [comment]
On this page: https://github.com/Valve/fingerprintjs2/wiki/List-of-options

It says you can use the `excludeBrowserAgent` option. Perhaps that would be enough?

**Comment by Valve** [comment]
Hi, @icetronics , thanks for using the library.

Computer (aka device) identification is much more complex than excluding a user agent. This library is strictly for browser identification, not devise identification. If you want a commercial identification solution, I suggest you use augur.io, these guys have a really good solution to do what you want. They can identify people, not browsers or devices, even if they have multiple browsers on multiple devices.

If you want to roll it yourself, then you need some kind of persistence mechanism, for example evercookie to store the identifiers, plus a server-side component to generate identifiers and sync them across browsers/devices. If no identifier is available, you generate a FP for the device and use it as a second, weaker identifier. I think some level of heuristics should be involved here.

Overall, FP.js2 is only a client-side lib to do browser identification, not more. It can be a part of a more complex identification solution if you wish, but it's a lot more work to implement it, so I suggest trying Augur.io

**Comment by icetronics** [comment]
Thanks for the tips, guys!
