### ISSUE TITLE
Screen resolution reported height by width. Standard is width by height

### ISSUE THREAD

**Issue by graemeblackwood** [Valve/fingerprintjs2#75]
This is a simple issue really – fingerprintJS2 reports screen res height x width, e.g. 1024 x 1280, which is portrait. The standard method is width by height, which would be 1280 x 1024.

It would be good to have this updated before fingerprintjs2 gains much more traction because it will affect the hashing.

**Comment by Valve** [comment]
Please explain how this is important. It's an internal implementation detail, not for reporting or outside usage.

**Comment by graemeblackwood** [comment]
Is that because you only intend for the hashed fingerprint to be consumed?

In order to be able to compare devices over time and use probability to determine whether they are the same device, I need to be able to record the individual properties, weight them and assigned an level of importance to each.

So far, the order of those values doesn't matter.

But there will be false positives where manual analysis needs to be performed. In this case, the device properties will be reviewed by a human, and presenting them in a standard format becomes relevant.

I could modify fingerprintjs2 for my own use, but it doesn't seem like a major change, except perhaps that it would break internal compatibility with the hash values already generated by existing users of this plugin.

**Comment by graemeblackwood** [comment]
Thanks!

**Comment by Valve** [comment]
You're welcome! :+1:
