### ISSUE TITLE
describe what 'tampering' means in the README.md

### ISSUE THREAD

**Issue by mhuisman** [Valve/fingerprintjs2#76]
> Has the user tampered with its languages
> Has the user tampered with its screen resolution
> Has the user tampered with its OS
> Has the user tampered with its browser

It isn't intuitive/clear what this actually means.  It is difficult for the end user to know whether she wants to enable them or not without a clear understanding of what it is detecting.

**Comment by renatoargh** [comment]
+1

**Comment by Valve** [comment]
Oh me oh my, so little time. Would you guys be able to do that with a PR? I need to finally release production version of FP2 and for that I have 2 blocking issues.

**Comment by Valve** [comment]
Done, now the bullets have those tiny superscript links that lead to a wiki page with the explanation. Please expand on / improve on this wiki page if necessary.
