### ISSUE TITLE
Using the AdBlock test not working for me

### ISSUE THREAD

**Issue by biglevel** [Valve/fingerprintjs2#77]
After playing around with this tool for the last couple hours, I discovered that detection doesn't work for AdBlock in Chrome on Mac OS. I've been on the hunt for finding an alternative solution, and nothing comes close to being nearly as elegant as the idea that has already been implemented. Other solutions I've stumbled across require loading another file with a trigger word (ie: "ad") being in the filename. It would be nice to not have to load another file to see if it gets blocked, but I'm starting to believe that it might be necessary.

**Comment by Valve** [comment]
@biglevel thanks for letting me know, will look into it now

**Comment by Valve** [comment]
Crazy, my attempts to trick AdBlock lead to nothing, this will require to really peruse their source code

**Comment by plaperdr** [comment]
Hey, I'm just adding my 2 cents on the subject.
The following code which is already included in fingerprintjs is fine in itself but it must be in an external file for it to be properly blocked by ad blockers. I'm using the same code on [AmIUnique.org](https://amiunique.org) and it works very well.
```javascript
var ads = document.createElement("div");
ads.setAttribute("id", "ads");
document.body.appendChild(ads);
```
To my understanding, when AdBlock looks into the DOM of a webpage, it does not analyse each JavaScript instructions. However, it does look at the "src" of scripts like `<script type="text/javascript" src="advert.js"></script>` and it blocks anything suspicious.
```javascript
return document.getElementById("ads") ? false : true;
```
will return false if the external file is blocked and true if it is not.
If you are interested in what triggers the blocking, take a look at the [EasyList filter](https://easylist-downloads.adblockplus.org/easylist.txt) which is one of the most widely used list by ad blockers. For the example writtent above, the "/advert." rule will block the external JS file making the detection of the blocker possible.
I don't know if there is an easier method to detect ad blockers so regarding fingerprintjs, this would mean that a second file would have to be distributed along the main one.

**Comment by biglevel** [comment]
Sorry I'm late to the party with my reply. Yes, I'm just using regular AdBlock. Like @plaperdr pointed out, it's not watching the DOM. I can confirm that if an external request is made, this version of AdBlock will catch and block it.

**Comment by Valve** [comment]
Thanks @biglevel . This leaves the issue open, if we want an additional hassle with loading external script just to be able to detect AdBlock or not. I think I'll disable AdBlock in the next version to avoid confusion. For people who want to be able to detect the presence of AdBlock, there are other JS scripts to do that: for example https://github.com/sitexw/FuckAdBlock

**Comment by Valve** [comment]
I've removed the AdBlock detection code, because It is not working. This change will go in v2.0.0
