### ISSUE TITLE
fingerprint2 in add-on sdk Firefox 'TypedArray data over Xrays is slow' function getWebglFp()

### ISSUE THREAD

**Issue by Jnull** [Valve/fingerprintjs2#78]
This is a minor bug to using WebGL fingerprint method in Add-on sdk for firefox, if you exclude WebGL the error message goes away. 

Here is my add-on sdk code: http://pastebin.com/k4xVzrZM  //main.js
Here is the pastebin of the error: http://pastebin.com/jYQ3WD3D

If i disable WebGL like this the problem is resolved. 
var options = {excludeWebGL: true};
new Fingerprint2(options).get(function(result){
  console.log(result);
});

Firefox suggests:  

Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.uti
ls.cloneInto().

fingerprint2.js:600:17|Fingerprint2.prototype.getWebglFp

If this is a performant issue with Fingerprint2 itself,  maybe its possible to change the TypedArray in the future.

**Comment by Valve** [comment]
thanks!, will look into it

**Comment by Jnull** [comment]
This is a separate problem with the add-on sdk so I'll just append it here. 
option:   {excludeAdBlock : true}  prevents an extra div element from being added to pages when using the tabs module and "contentScriptsFile: ./script.js" property.   No idea why or how this is happen at all.

**Comment by Jnull** [comment]
Found the page explaining xray's, this issue is invalid for fingerprint2, so closing it. 
https://developer.mozilla.org/en-US/docs/Xray_vision

**Comment by Valve** [comment]
Thanks
