### ISSUE TITLE
options list update on wiki

### ISSUE THREAD

**Issue by Jnull** [Valve/fingerprintjs2#79]
https://github.com/Valve/fingerprintjs2/wiki/List-of-options

 Line 112:       if(!this.options.excludeUserAgent) {
	Line 122:       if(!this.options.excludeLanguage) {
	Line 128:       if(!this.options.excludeColorDepth) {
	Line 134:       if(!this.options.excludeScreenResolution) {
	Line 163:       if(!this.options.excludeTimezoneOffset) {
	Line 169:       if(!this.options.excludeSessionStorage) {
	Line 175:       if(!this.options.excludeSessionStorage) {
	Line 181:       if(!this.options.excludeIndexedDB) {
	Line 188:       if(!this.options.excludeAddBehavior) {
	Line 194:       if(!this.options.excludeOpenDatabase) {
	Line 200:       if(!this.options.excludeCpuClass) {
	Line 206:       if(!this.options.excludePlatform) {
	Line 212:       if(!this.options.excludeDoNotTrack) {
	Line 218:       if(!this.options.excludeCanvas && this.isCanvasSupported()) {
	Line 224:       if(this.options.excludeWebGL) {
	Line 240:       if(!this.options.excludeAdBlock) {
	Line 246:       if(!this.options.excludeHasLiedLanguages){
	Line 252:       if(!this.options.excludeHasLiedResolution){
	Line 258:       if(!this.options.excludeHasLiedOs){
	Line 264:       if(!this.options.excludeHasLiedBrowser){
	Line 270:       if(this.options.excludeJsFonts) {  //positive match?
	Line 277:       if(this.options.excludeFlashFonts) {  //positive match?
	Line 393:       if(!this.options.excludePlugins){
	Line 474:       if(!this.options.excludeTouchSupport){

https://raw.githubusercontent.com/Valve/fingerprintjs2/master/fingerprint2.js

**Comment by Valve** [comment]
thanks! :+1:

**Comment by Jnull** [comment]
Awesome! Thank you.
