### ISSUE TITLE
HSTS supercookie for IOS

### ISSUE THREAD

**Issue by tracylms** [Valve/fingerprintjs2#8]
a new technique named "HSTS supercookie" seems to be able to fingerprint iOS devices pretty well

**Comment by Valve** [comment]
Thanks, will look into it.

**Comment by nowned** [comment]
Here is some more details
http://www.radicalresearch.co.uk/lab/hstssupercookies/

Looks like Firefox has patched it now but Chrome has not

**Comment by commerce-experts** [comment]
On my iOS devices the HSTS supercookie doesn't work anymore

**Comment by Valve** [comment]
ok, thanks, I'll close the issue
