### ISSUE TITLE
Multi Monitor Support

### ISSUE THREAD

**Issue by igor-im** [Valve/fingerprintjs2#83]
Are you still looking into this? 
How precise does it have to be? 

In my tests, I am able to detect multi monitor as long as the window is not open in the leftmost monitor. But I'm wondering if I should bother continuing reasearching this

**Comment by Valve** [comment]
I think Flash integration is required to reliably detect multiple monitors, don't know how to do it reliably in pure JS

**Comment by Valve** [comment]
I don't think it's possible to do it reliably now in JS, so closing the issue.

**Comment by PatSpiegel** [comment]
its possible
example (monitor in left)
availTop	0 
availLeft	-1280

**Comment by igor-im** [comment]
@PatSpiegel That's the way I had it, however, the issue becomes when the window is on the left most monitor, you get 0 on all values. Unless the person rearranged monitors and didn't align them properly you may then get top or availTop 10 or something :) But ye unfortunately on the leftmost one I don't think it's possible to detect, which makes this while possible, not reliable
