### ISSUE TITLE
Prevent GPU Flopping

### ISSUE THREAD

**Issue by rawberg** [Valve/fingerprintjs2#96]
When fingerprintjs2 runs with the default options it causes the GPU on MacBook Pros to flop from integrated mode to discrete mode.

This has a negative impact on user experience. Can this be prevented by disabling certain options?

Steps to reproduce:
- install gfxCardStatus
- set gfxCardStatus to dynamic switching
- visit [http://valve.github.io/fingerprintjs2/|http://valve.github.io/fingerprintjs2/]
- click "Get my fingerprint"
- see gfxCardStatus notification when it switches to discrete mode briefly while fingerprint is calculated

**Comment by Valve** [comment]
Most likely this happens during WebGL fingerprint calculation. To avoid this, please disable the WebGL component.

**Comment by rawberg** [comment]
setting excludeWebGL to false resolves this. thank you!
